/** Reviewed images only: clients send identifiers/proofs, never image bytes or URLs. */
export class PhotoInputError extends Error {
  constructor(public readonly code = 'INVALID_PHOTO_PUBLICATION_INPUT') { super(code); this.name = 'PhotoInputError'; }
}
export type PhotoProof = {jobId: string; jobRevision: string; sourceHash: string; imageHash: string; overlayVersion: string};
export type PhotoPreview = PhotoProof & {productId: string; productName: string; ready: boolean; reason: string | null; beforeUrl: string | null; sourceUrl: string; draftUrl: string};
export type PhotoCommand = ({action:'apply'; operationId:string; confirmed:true} & PhotoProof) | {action:'undo'; operationId:string; confirmed:true; publicationId:string};
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function fail(): never { throw new PhotoInputError(); }
function object(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) return fail(); return v as Record<string, unknown>; }
function exact(v: Record<string, unknown>, keys: string[]) { if (Object.keys(v).length !== keys.length || Object.keys(v).some(k => !keys.includes(k))) fail(); }
function id(v: unknown): string { if (typeof v !== 'string' || !UUID.test(v)) return fail(); return v.toLowerCase(); }
function rev(v: unknown): string { if (typeof v !== 'string' || !/^(0|[1-9][0-9]{0,18})$/.test(v) || BigInt(v) > 9223372036854775807n) return fail(); return v; }
function hash(v: unknown): string { if (typeof v !== 'string' || !/^[a-f0-9]{64}$/.test(v)) return fail(); return v; }
export function readPhotoCommand(value: unknown): {action: 'preview'|'apply'|'undo'; payload: Record<string, unknown>} {
  const v = object(value);
  if (v.action === 'preview') { exact(v, ['action','jobId']); return {action:'preview',payload:{jobId:id(v.jobId)}}; }
  if (v.action === 'undo') { exact(v,['action','operationId','confirmed','publicationId']); if (v.confirmed !== true) return fail(); return {action:'undo',payload:{operationId:id(v.operationId),confirmed:true,publicationId:id(v.publicationId)}}; }
  if (v.action !== 'apply') return fail();
  exact(v,['action','operationId','confirmed','jobId','jobRevision','sourceHash','imageHash','overlayVersion']);
  if (v.confirmed !== true) return fail();
  return {action:'apply',payload:{operationId:id(v.operationId),confirmed:true,jobId:id(v.jobId),jobRevision:rev(v.jobRevision),sourceHash:hash(v.sourceHash),imageHash:hash(v.imageHash),overlayVersion:rev(v.overlayVersion)}};
}
export function photoApplyCommand(p: PhotoPreview, operationId: string): PhotoCommand {
  if (p.ready !== true) throw new PhotoInputError(p.reason || 'STUDIO_SOURCE_CHANGED');
  const {jobId,jobRevision,sourceHash,imageHash,overlayVersion} = p;
  const command: PhotoCommand = {action:'apply',operationId,confirmed:true,jobId,jobRevision,sourceHash,imageHash,overlayVersion};
  readPhotoCommand(command); return command;
}
/** Public URLs are generated by the backend; do not load external model URLs. */
export function publicPhotoPath(v: unknown): string | null {
  if (typeof v !== 'string' || !/^\/api\/menu-photo\/[a-f0-9-]{36}\/[a-f0-9-]{36}$/.test(v)) return null;
  const [, , , product, asset] = v.split('/');
  return UUID.test(product ?? '') && UUID.test(asset ?? '') ? v : null;
}
