// Pure extraction/review/adapter contracts. No live AI call and no user menu.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const out='test-results/ai-menu-unit';fs.mkdirSync(out,{recursive:true});
for(const name of ['contracts','review','provider']){let s=fs.readFileSync('lib/ai-menu/'+name+'.ts','utf8').replace("import 'server-only';",'').replace("import {getVercelOidcToken} from '@vercel/oidc';","const getVercelOidcToken=()=>{throw Error('No test secret');};").replaceAll("from './contracts'","from './contracts.mjs'");fs.writeFileSync(out+'/'+name+'.mjs',ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const c=await import('../'+out+'/contracts.mjs'),r=await import('../'+out+'/review.mjs'),p=await import('../'+out+'/provider.mjs');
const id='55555555-5555-4555-8555-555555555555';
const item={name:'Peynirli Börek',category:'Kahvaltı',description:'Peynirli',serving:'Porsiyon',priceMinor:'15000',options:[],sourcePage:1,sourceText:'Peynirli Börek 150 TL',warnings:[]};
const draft={currency:'TRY',items:[item],warnings:[]};
for(const [txt,price] of [['150','15000'],['150,50','15050'],['0.01','1'],['1.2','120'],['0001,20','120'],['','null']])test('exact cents '+txt,()=>assert.equal(c.tlToMinor(txt),price==='null'?null:price));
for(const v of ['1.234','1,000.00','1e3','-10','NaN','1000001','1 000'])test('ambiguous or invalid price rejected '+v,()=>assert.throws(()=>c.tlToMinor(v)));
test('100000 amount roundtrips without money floats',()=>{for(let n=0;n<100000;n++)assert.equal(c.tlToMinor(c.minorToTl(String(n))),String(n));});
test('legible structured data accepted',()=>assert.deepEqual(c.validateDraft(draft),draft));
for(const bad of [{...draft,currency:'USD'},{...draft,items:[{...item,priceMinor:15000}]},{...draft,items:[{...item,priceMinor:'150.00'}]},{...draft,items:[{...item,sourcePage:9}]},{...draft,items:[{...item,name:''}]},{...draft,items:Array(101).fill(item)}])test('invalid output cannot enter draft '+JSON.stringify(bad).slice(0,85),()=>assert.throws(()=>c.validateDraft(bad)));
test('unknown price stays null',()=>assert.equal(c.validateDraft({...draft,items:[{...item,priceMinor:null}]}).items[0].priceMinor,null));
test('single exact Turkish match, not fuzzy destructive merge',()=>{assert.equal(c.matchProduct('  PEYNİRLİ   BÖREK ',[{id,name:item.name}]),id);assert.equal(c.matchProduct('Peynirli Börek',[{id,name:item.name},{id:'other',name:item.name}]),null);assert.equal(c.matchProduct('Peynirli',[{id,name:item.name}]),null);});
test('all initial matches are suggestions/skip, never approved',()=>{const rows=r.initialReview(draft,[{id,name:item.name,categoryKey:'kahvalti',updatedAt:'2026-09-19T00:00:00Z'}]);assert.equal(rows[0].action,'skip');assert.equal(rows[0].reviewed,false);assert.equal(rows[0].targetId,id);assert.equal(rows[0].categoryKey,'kahvalti');assert.equal(r.validateReview(rows)[0].action,'skip');});
test('review rejects missing target snapshot',()=>{const row=r.initialReview(draft,[])[0];assert.throws(()=>r.validateReview([{...row,action:'update',targetId:id}]));});
test('review rejects floating wire money',()=>assert.throws(()=>r.validateReview([{...r.initialReview(draft,[])[0],priceMinor:1.5}])));
for(const [prefix,mime] of [[Buffer.from([255,216,255]),'image/jpeg'],[Buffer.from([137,80,78,71,13,10,26,10]),'image/png'],[Buffer.from('%PDF-1.7'),'application/pdf'],[Buffer.from('RIFF1234WEBP'),'image/webp']])test('sniff '+mime,()=>assert.equal(c.fileKind(Buffer.concat([prefix,Buffer.alloc(12)])),mime));
test('invalid HTML rejected regardless of filename',()=>assert.throws(()=>c.fileKind(Buffer.from('<html>not image</html>'))));
test('file limit enforced before model call',()=>assert.throws(()=>c.fileKind(new Uint8Array(c.MAX_FILE+1))));
test('prompt protects source as untrusted, not execution authority',()=>{for(const s of ['untrusted DATA','never invent','paid extras','null','human'])assert.ok(c.SYSTEM_PROMPT.includes(s));});
const originalFetch=globalThis.fetch;
async function stub(value,fn){globalThis.fetch=value;try{await fn();}finally{globalThis.fetch=originalFetch;}}
const ok=()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(draft)}}],usage:{prompt_tokens:20,completion_tokens:60}}));
test('provider uses bounded schema/no tools and image data not remote URL',async()=>{await stub(async(url,init)=>{assert.equal(url,'https://ai-gateway.vercel.sh/v1/chat/completions');const b=JSON.parse(init.body);assert.equal(b.tools,undefined);assert.equal(b.response_format.type,'json_schema');assert.equal(b.response_format.json_schema.strict,true);assert.equal(b.stream,false);assert.equal(b.messages[1].content[1].image_url.url,'data:image/png;base64,abc');return ok();},async()=>assert.equal((await p.extractMenu('abc','image/png','synthetic-token')).draft.items[0].priceMinor,'15000'));});
test('PDF goes as original typed file, not rasterized OCR',async()=>{await stub(async(_,init)=>{assert.equal(JSON.parse(init.body).messages[1].content[1].file.file_data,'data:application/pdf;base64,pdf');return ok();},async()=>assert.equal((await p.extractMenu('pdf','application/pdf','synthetic-token')).inputTokens,'20'));});
for(const [status,code] of [[401,'AI_ACCESS_REQUIRED'],[403,'AI_ACCESS_REQUIRED'],[402,'AI_CREDIT_REQUIRED'],[429,'AI_RATE_LIMIT'],[500,'AI_UNAVAILABLE']])test('provider safe failure '+status,async()=>{let calls=0;await stub(async()=>{calls++;return new Response('',{status});},async()=>await assert.rejects(p.extractMenu('a','image/png','synthetic-token'),new RegExp(code)));assert.equal(calls,1);});
test('network ambiguity does not auto-retry',async()=>{let n=0;await stub(async()=>{n++;throw Error('secret detail');},async()=>await assert.rejects(p.extractMenu('a','image/png','secret'),/AI_RESULT_UNKNOWN/));assert.equal(n,1);});
test('truncation is not accepted as complete extraction',async()=>{await stub(async()=>new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'{}'}}]})),async()=>await assert.rejects(p.extractMenu('a','image/png','t'),/AI_OUTPUT_INCOMPLETE/));});
test('refusal is not interpreted as an empty menu',async()=>{await stub(async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{refusal:'no'}}]})),async()=>await assert.rejects(p.extractMenu('a','image/png','t'),/AI_REFUSAL/));});
test('oversized response fails safely',async()=>{await stub(async()=>new Response('x'.repeat(350001)),async()=>await assert.rejects(p.extractMenu('a','image/png','t'),/AI_OUTPUT_INCOMPLETE/));});

for(const balance of ['0','0.000000','00.00'])test('zero gateway credit blocks inference before claim '+balance,async()=>{await stub(async(url,init)=>{assert.ok(url.endsWith('/credits'));assert.equal(init.method,undefined);return new Response(JSON.stringify({balance}));},async()=>await assert.rejects(p.checkGatewayAccess('synthetic'),/AI_CREDIT_REQUIRED/));});
for(const balance of ['0.01','5'])test('existing positive credit preflight '+balance,async()=>{await stub(async()=>new Response(JSON.stringify({balance})),async()=>await p.checkGatewayAccess('synthetic'));});
test('preflight does not turn credentials alone into available AI',async()=>{await stub(async()=>new Response('',{status:403}),async()=>await assert.rejects(p.checkGatewayAccess('synthetic'),/AI_ACCESS_REQUIRED/));});
