import {test} from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import fs from 'node:fs';
const path='test-results/winback.mjs';fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync(path,ts.transpileModule(fs.readFileSync('src/crm/winback.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);const{eligible,runWinbackOnce}=await import('../'+path);
const now=Date.parse('2026-09-17T12:00:00Z'),day=86400000;const c={nowMs:now,lastPaidCompletedMs:now-22*day,lastSentMs:null,inactivityDays:21,cooldownDays:30,phoneVerified:true,localConsent:true,iysGranted:true,iysCheckedMs:now-1000,alreadyQueued:false};
test('21-day eligible verified customer',()=>assert.equal(eligible(c),true));
for(const [name,patch] of Object.entries({recent:{lastPaidCompletedMs:now-20*day},optout:{localConsent:false},unverified:{phoneVerified:false},iysrevoked:{iysGranted:false},iysstale:{iysCheckedMs:now-2*day},future:{iysCheckedMs:now+1},duplicate:{alreadyQueued:true},cooldown:{lastSentMs:now-2*day},neverordered:{lastPaidCompletedMs:null}}))test('reject '+name,()=>assert.equal(eligible({...c,...patch}),false));
function ports(){const calls=[];return{calls,enabled:true,claim:async()=>{calls.push('claim');return{id:'x',leaseToken:'lease'}},refreshPermission:async()=>{calls.push('iys')},prepare:async()=>{calls.push('prepare');return{id:'x',phone:'+905550000000',providerRef:'sandbox',senderRef:'BRAND',idempotencyKey:'same',template:'text'}},render:async()=> 'Açık izinli test metni',provider:()=>({send:async()=>{calls.push('send');return{providerRef:'provider-id'}}}),finish:async(_l,s)=>{calls.push(s);return true;}};}
test('disabled does not touch queue or provider',async()=>{const p=ports();p.enabled=false;assert.equal((await runWinbackOnce(p)).state,'disabled');assert.deepEqual(p.calls,[]);});
test('IYS refresh and final DB gate precede send',async()=>{const p=ports();await runWinbackOnce(p);assert.deepEqual(p.calls,['claim','iys','prepare','send','accepted']);});
test('revoked customer not sent',async()=>{const p=ports();p.prepare=async()=>null;assert.equal((await runWinbackOnce(p)).state,'suppressed');assert.ok(!p.calls.includes('send'));});
test('timeout becomes unknown not blind retry',async()=>{const p=ports();let n=0;p.provider=()=>({send:async()=>{n++;throw Error('timeout')}});assert.equal((await runWinbackOnce(p)).state,'unknown');assert.equal(n,1);assert.ok(p.calls.includes('unknown'));});
test('commit failure not a success',async()=>{const p=ports();p.finish=async()=>false;await assert.rejects(runWinbackOnce(p),/SMS_RESULT_NOT_COMMITTED/);});
