// Pure routing/transport tests; all credentials/responses synthetic. No real model calls.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const dir='test-results/free-ai-unit';fs.mkdirSync(dir,{recursive:true});
for(const file of ['core','menu-contracts','open-source','studio-contracts','studio-operations','free-policy','free-router']){
 const source=fs.readFileSync('supabase/functions/menugo-llm/'+file+'.ts','utf8').replaceAll(".ts'",".mjs'");
 fs.writeFileSync(dir+'/'+file+'.mjs',ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
}
const p=await import('../'+dir+'/free-policy.mjs'),r=await import('../'+dir+'/free-router.mjs');
const route=(provider,extra={})=>({provider,model:p.FREE_MODELS[provider][0],key:'SYNTHETIC_NEVER_REAL_KEY_12345',priority:10,version:'1',accountId:provider==='cloudflare_free'?'a'.repeat(32):null,attestedUntil:'2099-01-01T00:00:00Z',publicContentAllowed:true,privateContentAllowed:true,...extra});
const probe={provider:'free_router',model:'free-router-v1',key:'',kind:'test',context:{},request:{}};
const chat=()=>new Response(JSON.stringify({model:'test/free-model',choices:[{finish_reason:'stop',message:{content:JSON.stringify({status:'MENUGO_OK'})}}]}));
const imageProbe=()=>new Response(JSON.stringify({success:true,result:{image:'iVBORw=='}}));
for(const [kind,ctx,provider,expected] of [
 ['assistant',{},'gemini_free',false],['assistant',{},'groq_free',true],['assistant',{},'cloudflare_free',true],
 ['menu-extract',{mime:'image/png'},'groq_free',false],['menu-extract',{mime:'image/png'},'gemini_free',true],['menu-extract',{mime:'image/png'},'cloudflare_free',false],
 ['menu-extract',{mime:'application/pdf'},'openrouter_free',false],['menu-extract',{mime:'application/pdf'},'gemini_free',true],
 ['studio',{studioKind:'invoice',input:{attachment:{mime:'image/png'}}},'gemini_free',false],
 ['studio',{studioKind:'invoice',input:{attachment:{mime:'image/png'}}},'openrouter_free',true],['studio',{studioKind:'invoice',input:{attachment:{mime:'image/png'}}},'cloudflare_free',false],
 ['studio',{studioKind:'photo-enhance'},'cloudflare_free',true],['studio',{studioKind:'photo-enhance'},'openrouter_free',false],
 ['studio',{studioKind:'product-copy'},'gemini_free',true],['studio',{studioKind:'product-copy'},'cloudflare_free',true]
])test('capability/privacy '+kind+' '+ctx.studioKind+' '+provider,()=>assert.equal(p.routeEligible(route(provider),kind,ctx,{}),expected));
test('no consent means no public document forwarding',()=>assert.equal(p.routeEligible(route('openrouter_free',{publicContentAllowed:false}),'menu-extract',{mime:'image/png'},{}),false));
test('no consent means no private invoice forwarding',()=>assert.equal(p.routeEligible(route('openrouter_free',{privateContentAllowed:false}),'studio',{studioKind:'invoice',input:{}},{}),false));
test('Cloudflare private assistant requires private-data opt in',()=>assert.equal(p.routeEligible(route('cloudflare_free',{privateContentAllowed:false}),'assistant',{},{}),false));
for(const value of ['2020-01-01','invalid',''])test('expired or invalid free attestation '+value,()=>assert.equal(p.routeEligible(route('groq_free',{attestedUntil:value}),'test',{},{}),false));
for(const model of ['openai/gpt-5','openrouter/auto','deepseek-chat','gemini-3.8-flash'])test('not reviewed model blocked '+model,()=>assert.equal(p.routeEligible(route('groq_free',{model}),'test',{},{}),false));
test('priority deterministic, max 3 and one credential per provider',()=>{const a=p.sortedRoutes([route('gemini_free',{priority:20}),route('groq_free'),route('groq_free'),route('openrouter_free',{priority:30}),route('cloudflare_free',{priority:40})],'test',{},{});assert.deepEqual(a.map(x=>x.provider),['groq_free','gemini_free','openrouter_free']);});
test('no routes produces no network requests',async()=>{let n=0;await assert.rejects(r.generateFree({...probe,routes:[]},{before:async()=>true,after:async()=>{}},async()=>{n++;return chat();}),/LLM_NO_ELIGIBLE_FREE_ROUTE/);assert.equal(n,0);});
test('429 failover is ordered, ledger before network',async()=>{const order=[];const out=await r.generateFree({...probe,routes:[route('groq_free'),route('openrouter_free',{priority:20})]},{before:async x=>{order.push('before:'+x.provider);return true;},after:async(x,s)=>order.push(s+':'+x.provider)},async url=>{order.push('http');return String(url).includes('api.groq.com')?new Response('{}',{status:429}):chat();});assert.equal(out.result.verified,true);assert.deepEqual(order,['before:groq_free','http','rejected:groq_free','before:openrouter_free','http','success:openrouter_free']);assert.equal(out.model,'test/free-model');});
test('quota denial suppresses call even with key',async()=>{let n=0;await assert.rejects(r.generateFree({...probe,routes:[route('groq_free')]},{before:async()=>false,after:async()=>{throw Error('should not');}},async()=>{n++;return chat();}),/LLM_FREE_QUOTA_WAIT/);assert.equal(n,0);});
for(const mode of ['network','500','invalid','refusal'])test('no fallback after uncertain or refused '+mode,async()=>{let n=0;const states=[];await assert.rejects(r.generateFree({...probe,routes:[route('groq_free'),route('openrouter_free')]},{before:async()=>true,after:async(_,s)=>states.push(s)},async()=>{n++;if(mode==='network')throw Error('private key never logged');if(mode==='500')return new Response('{}',{status:500});if(mode==='invalid')return new Response('{}');return new Response(JSON.stringify({choices:[{message:{refusal:'no'}}]}));}));assert.equal(n,1);assert.deepEqual(states,['unknown']);});
test('Cloudflare photo uses multipart and a reference, not chat/image substitution',async()=>{let called=false;const result=await r.cloudflareImage({...probe,kind:'studio',context:{input:{style:'white',modelAttachment:{mime:'image/png',data:'iVBORw=='}}}},route('cloudflare_free'),async(url,init)=>{called=true;assert.match(url,/api.cloudflare.com\/client\/v4\/accounts\/a{32}\/ai\/run\/@cf\/black-forest-labs\/flux-2-klein-4b$/);assert.equal(init.redirect,'error');assert.equal(init.body.get('width'),'1024');assert.ok(init.body.get('input_image_0') instanceof Blob);return imageProbe();});assert.equal(called,true);assert.equal(result.result.draft.draftOnly,true);assert.equal(result.result.draft.mime,'image/png');});
test('Cloudflare connection probe still verifies configured FLUX endpoint',async()=>{let urlSeen='';const states=[];const out=await r.generateFree({...probe,routes:[route('cloudflare_free')]},{before:async()=>true,after:async(x,s)=>states.push([x.provider,s])},async url=>{urlSeen=String(url);return imageProbe();});assert.match(urlSeen,/\/ai\/run\/@cf\/black-forest-labs\/flux-2-klein-4b$/);assert.equal(out.result.verified,true);assert.deepEqual(states,[['cloudflare_free','success']]);});
test('Cloudflare direct text adapter uses reviewed Gemma model',async()=>{let called=false;const out=await r.cloudflareText(probe,route('cloudflare_free'),async(url,init)=>{called=true;assert.match(url,/api.cloudflare.com\/client\/v4\/accounts\/a{32}\/ai\/v1\/chat\/completions$/);const body=JSON.parse(init.body);assert.equal(body.model,p.CLOUDFLARE_TEXT_MODEL);assert.equal(body.options.rejectIfBusy,true);assert.equal(body.response_format.type,'json_schema');return chat();});assert.equal(called,true);assert.equal(out.result.verified,true);assert.equal(out.model,p.CLOUDFLARE_TEXT_MODEL);});
test('Cloudflare text paid-plan-required fails closed as credit required',async()=>{await assert.rejects(r.cloudflareText(probe,route('cloudflare_free'),async()=>new Response(JSON.stringify({errors:[{code:5035}]}),{status:403})),e=>e?.code==='LLM_CREDIT_REQUIRED');});
test('Cloudflare arbitrary endpoint/account injection rejected without request',async()=>{let n=0;await assert.rejects(r.cloudflareImage(probe,route('cloudflare_free',{accountId:'../../evil'}),async()=>{n++;return chat();}),/LLM_ACCOUNT_REQUIRED/);assert.equal(n,0);});
test('production Edge cannot call legacy paid or self hosted dispatch',()=>{const source=fs.readFileSync('supabase/functions/menugo-llm/index.ts','utf8');assert.ok(source.includes("d.provider!=='free_router'"));assert.ok(source.includes('generateFree'));assert.ok(!source.includes('generate(d)'));});
test('SQL keeps grants closed and quotas transactional',()=>{const sql=fs.readFileSync('supabase/migrations/20260919233000_ops_free_ai_control.sql','utf8');for(const text of ['ENABLE ROW LEVEL SECURITY','pg_advisory_xact_lock','UNIQUE(run_id,provider)','LLM_PAID_PROVIDER_BLOCKED','LLM_FREE_PLAN_RECONFIRM',"NEW.request-'modelAttachment'-'attachment'"])assert.ok(sql.includes(text),text);assert.ok(!/UPDATE public\.|INSERT INTO public\./i.test(sql));});
