'use client';
import {useEffect,useRef,useState} from 'react';
import {Card} from './Shell';
import {PdfMenuImport} from './PdfMenuImport';
import {api,money} from './transport';
import {MAX_FILE,importMessage,minorToTl,tlToMinor} from '@/lib/ai-menu/contracts';
import type {ReviewRow,Product} from '@/lib/ai-menu/review';
type Listing={jobs:{id:string;name:string;status:string;revision:string;createdAt:string}[];categories:{key:string;title:string}[];catalogue:Product[];aiConfigured:boolean;aiUnavailableReason?:string|null;usedToday:number;dailyLimit:number;model:string;provider?:string};
type Job={id:string;file_name:string;mime:string;status:string;revision:string;review_rows:ReviewRow[];catalogue_snapshot:Product[];extracted:{warnings:string[]}|null;error_code:string|null;sourceAvailable:boolean;apply_receipt:{changed:number}|null};
const statuses:Record<string,string>={queued:'Analiz kuyruğunda',processing:'Belge inceleniyor',review:'Kontrolünüzü bekliyor',failed:'Analiz tamamlanamadı',unknown:'Analiz sonucu belirsiz',applied:'Menüye uygulandı',reverted:'Geri alındı',discarded:'Vazgeçildi'};
export function AiMenuStudio(){
 const[list,setList]=useState<Listing|null>(null),[job,setJob]=useState<Job|null>(null),[rows,setRows]=useState<ReviewRow[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmed,setConfirmed]=useState(false),[dirty,setDirty]=useState(false);
 const epoch=useRef(0),uploadKey=useRef(''),activeId=useRef<string|null>(null);
 async function loadList(){try{setList(await api('/api/ai-menu/list'));}catch(e){setError(importMessage(e));}}
 async function open(id:string,force=false){if(!force&&dirty&&!window.confirm('Kaydedilmemiş taslak değişikliklerinden vazgeçilsin mi?'))return;activeId.current=id;const n=++epoch.current;setError('');try{const j=await api<Job>('/api/ai-menu/snapshot?id='+id);if(n!==epoch.current)return;setJob(j);setRows(j.review_rows);setConfirmed(false);setDirty(false);}catch(e){if(n===epoch.current)setError(importMessage(e));}}
 useEffect(()=>{void loadList();return()=>{epoch.current++;};},[]);
 useEffect(()=>{if(!job||!['queued','processing'].includes(job.status))return;const id=job.id;const t=setInterval(()=>{if(document.visibilityState!=='visible'||activeId.current!==id)return;void api<Job>('/api/ai-menu/snapshot?id='+id).then(j=>{if(activeId.current!==id)return;setJob(j);if(j.status==='review'){setRows(j.review_rows);setDirty(false);void loadList();}}).catch(()=>{});},3000);return()=>clearInterval(t);},[job?.id,job?.status]);
 useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 function choose(f:File|null){if(!f)return;setError('');if(f.size>MAX_FILE){setError(importMessage(new Error('FILE_SIZE_LIMIT')));return;}setFile(f);uploadKey.current=crypto.randomUUID();}
 async function upload(){if(!file||busy)return;setBusy(true);setError('');setNotice('');try{
  const raw=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]!);r.onerror=reject;r.readAsDataURL(file);});
  const r=await api<{id:string;duplicate:boolean}>('/api/ai-menu/upload',{operationId:uploadKey.current,fileName:file.name,data:raw});setNotice(r.duplicate?'Bu belge daha önce yüklendi. Aynı taslak açıldı; ürünler çoğaltılmadı.':'Belgeniz kaydedildi. AI yalnızca kontrol edilebilir bir taslak hazırlıyor.');setFile(null);await loadList();await open(r.id,true);
 }catch(e){setError(importMessage(e));}finally{setBusy(false);}}
 function change(i:number,patch:Partial<ReviewRow>){setRows(xs=>xs.map((x,n)=>n===i?{...x,...patch,reviewed:false}:x));setConfirmed(false);setDirty(true);}
 function target(i:number,value:string){const p=list?.catalogue.find(x=>x.id===value);change(i,p?{action:'update',targetId:p.id,expectedUpdatedAt:p.updatedAt,categoryKey:p.categoryKey}:{action:value==='new'?'create':'skip',targetId:null,expectedUpdatedAt:null});}
 async function save(){if(!job)return;setBusy(true);setError('');try{await api('/api/ai-menu/save',{id:job.id,revision:job.revision,rows});await open(job.id,true);setNotice('Taslak kaydedildi. Canlı menü değişmedi.');}catch(e){setError(importMessage(e));}finally{setBusy(false);}}
 async function apply(){if(!job||!confirmed)return;setBusy(true);setError('');try{const r=await api('/api/ai-menu/apply',{id:job.id,revision:job.revision,rows:rows.map(r=>({...r,reviewed:r.action!=='skip'})),confirmed:true});await open(job.id,true);await loadList();setNotice(`${r.changed} ürün değişikliği menüye uygulandı. Eksik fiyatlı yeni ürünler satışa kapalıdır.`);}catch(e){setError(importMessage(e));}finally{setBusy(false);}}
 async function process(){if(!job)return;if(job.status!=='queued'&&!window.confirm('Önceki analiz yanıtı alınamadı. Yeniden deneme ayrı AI kullanımı oluşturabilir. Devam edilsin mi?'))return;setBusy(true);try{await api('/api/ai-menu/process',{id:job.id,retry:true});setJob({...job,status:'processing'});setError('');}catch(e){setError(importMessage(e));}finally{setBusy(false);}}
 async function undo(){if(!job||!window.confirm('Bu aktarımın değişiklikleri geri alınacak. Yeni eklenmiş ürünler silinmez, satışa kapatılır. Sonradan değişen ürün varsa işlem durdurulur. Devam edilsin mi?'))return;setBusy(true);try{await api('/api/ai-menu/undo',{id:job.id});await open(job.id,true);await loadList();setNotice('Aktarım geri alındı; sipariş geçmişi korundu.');}catch(e){setError(importMessage(e));}finally{setBusy(false);}}
 const selected=rows.filter(r=>r.action!=='skip').length;
 return <section className="ai-studio" aria-label="AI Menü Stüdyosu">
 <p className="notice">AI altyapısı MenüGO şirket yönetimi tarafından sağlanır. Yalnızca uygun ücretsiz hizmetler kullanılır. Fotoğrafı yükleyebilir veya PDF sayfalarını önce cihazınızda hazırlayabilirsiniz.</p><Card className="ai-intro"><div><p className="eyebrow">FOTOĞRAFTAN DİJİTAL MENÜYE</p><h2>Menünüzü çekin.<br/>Birlikte kontrol edelim.</h2><p>Ürünleri, fiyatları ve porsiyonları bir taslakta toplayın. Mevcut menünüzle karşılaştırın; yalnızca seçtiğiniz değişiklikleri uygulayın.</p></div><div className="ai-steps"><span><b>01</b> Belgeyi yükle</span><span><b>02</b> Eşleştir ve kontrol et</span><span><b>03</b> Seçilenleri uygula</span></div></Card>
 {error&&<div className="alert" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <div className="ai-top-grid"><Card><div className="section-heading"><h2>Yeni menü aktarımı</h2><span className="tag">Fotoğraf / PDF</span></div><p>JPG, PNG veya WebP. Fotoğraf başına 2 MB. PDF için aşağıdaki sayfa hazırlama alanını kullanın.</p><div className="ai-upload-buttons"><label className="btn"><span aria-hidden>◉</span> Menü fotoğrafını çek<input aria-label="Menü fotoğrafını çek" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>choose(e.target.files?.[0]??null)}/></label><label className="btn">Dosya seç<input aria-label="Menü dosyası seç" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0]??null)}/></label></div>{file&&<p className="ai-file-name">{file.name}</p>}
 <button className="btn primary" disabled={busy||!file||!list?.aiConfigured||list.usedToday>=list.dailyLimit} onClick={()=>void upload()}>{busy?'Kaydediliyor…':'AI ile menü taslağı çıkar'}</button>
 <p className="helper">Bu işlem belgeyi seçili LLM sağlayıcısına iletir. Yalnız size ait menü belgelerini yükleyin; kişisel veri eklemeyin. Kaynak 30 gün erişilebilir; ardından günlük temizlikte silinir. Model yanılabilir; fiyatları mutlaka kontrol edin.</p>
 {list&&!list.aiConfigured&&<p className="alert">{importMessage(new Error(list.aiUnavailableReason||'AI_NOT_CONFIGURED'))} Mevcut menünüz ve siparişleriniz etkilenmez; kayıtlı taslakları düzenlemeye devam edebilirsiniz. Sağlayıcı bağlantılarını yalnız MenüGO şirket yönetimi düzenler.</p>}
 {list&&<p className="helper">Bugünkü AI denemeleri: <b>{list.usedToday} / {list.dailyLimit}</b>. Ücretli modele geçilmez ve kredi satın alınmaz.</p>}</Card>
 <Card><div className="section-heading"><h2>Aktarım geçmişi</h2><button className="text-button" onClick={()=>void loadList()}>Yenile</button></div>{!list?<p>İşletme yetkisi doğrulanıyor…</p>:!list.jobs.length?<div className="ai-empty"><span aria-hidden>▤</span><h3>İlk belgenizi yükleyin</h3><p>Kaynağı, taslağı ve uygulama sonucunu burada takip edeceksiniz.</p></div>:<div className="ai-history">{list.jobs.map(j=><button key={j.id} className={job?.id===j.id?'active':''} onClick={()=>void open(j.id)}><strong>{j.name}</strong><small>{statuses[j.status]} · {new Date(j.createdAt).toLocaleDateString('tr-TR')}</small></button>)}</div>}</Card></div>
 <PdfMenuImport aiReady={list?.aiConfigured===true} remaining={Math.max(0,(list?.dailyLimit??0)-(list?.usedToday??0))} onUploaded={id=>{void loadList();void open(id);}}/>
 {job&&<Card><div className="section-heading"><div><p className="eyebrow">BELGE / TASLAK</p><h2>{job.file_name}</h2></div><span className="tag">{statuses[job.status]}</span></div>
 <div className="ai-document-layout"><aside className="ai-source"><h3>Kaynak belge</h3>{job.sourceAvailable?job.mime==='application/pdf'?<a className="btn" href={'/api/ai-menu/source?id='+job.id}>Kaynak PDF’yi aç / indir</a>:<a href={'/api/ai-menu/source?id='+job.id} target="_blank" rel="noopener noreferrer"><img src={'/api/ai-menu/source?id='+job.id} alt="Yüklenen menünün özgün fotoğrafı"/></a>:<p>Kaynak saklanmıyor.</p>}<p className="helper">AI’nın aktardığı kaynak satırı ve sayfa numarası her ürünün altında bulunur. Fotoğrafa dokunarak büyütebilirsiniz.</p>{job.sourceAvailable&&<button className="text-button" disabled={busy||dirty} onClick={async()=>{if(!window.confirm('Kaynak dosya kalıcı olarak silinsin mi? Taslak ve işlem geçmişi korunur.'))return;try{await api('/api/ai-menu/delete-source',{id:job.id});await open(job.id,true);}catch(e){setError(importMessage(e));}}}>Kaynak dosyayı sil</button>}</aside>
 <div className="ai-review">{job.error_code&&<p className="alert">{importMessage(new Error(job.error_code))}</p>}
 {['queued','processing','unknown','failed'].includes(job.status)&&<div className="ai-empty"><span aria-hidden>✦</span><h3>{job.status==='processing'?'Belgeniz analiz ediliyor':'Analiz adımı'}</h3><p>Mevcut menü ve fiyatlar değiştirilmez. Bu ekranı kapatsanız da kaydedilmiş belge ve iş durumu korunur. Kesinti halinde otomatik ücretli tekrar yapılmaz.</p>{job.status!=='processing'&&<button className="btn primary" disabled={busy||!list?.aiConfigured} onClick={()=>void process()}>{job.status==='queued'?'Analizi başlat':'Analizi yeniden dene'}</button>}</div>}
 {job.status==='review'&&<><div className="notice"><b>{rows.length} ürün taslağı</b> · AI’nın görmediği eski ürünler silinmez. Eşleşme önerileri otomatik uygulanmaz.</div>{job.extracted?.warnings.map((w,i)=><p className="helper" key={i}>{w}</p>)}
 <div className="ai-review-toolbar"><button className="btn" onClick={()=>{setRows(xs=>xs.map(r=>r.targetId?{...r,action:'update',reviewed:false}:r));setDirty(true);setConfirmed(false);}}>Eşleşenleri seç</button><button className="text-button" onClick={()=>{setRows(xs=>xs.map(r=>({...r,action:'skip'})));setDirty(true);setConfirmed(false);}}>Seçimi temizle</button><span>{selected} değişiklik seçildi</span></div>
 {rows.map((r,i)=>{const old=list?.catalogue.find(p=>p.id===r.targetId);return <article className={'ai-review-row '+(r.action==='skip'?'ai-skipped':'')} key={i}><div className="section-heading"><b>{i+1}. {r.name}</b><span className="tag">{r.targetId?'Eşleşme önerisi':'Yeni / eşleştirilmemiş'}</span></div><label>Uygulanacak işlem<select aria-label={`İşlem ${i+1}`} value={r.action==='skip'?'skip':r.action==='create'?'new':r.targetId??'skip'} onChange={e=>target(i,e.target.value)}><option value="skip">Atla — menüyü değiştirme</option><option value="new">Yeni ürün olarak ekle</option>{list?.catalogue.map(p=><option value={p.id} key={p.id}>Güncelle: {p.name}</option>)}</select></label>
 {old&&<div className="ai-comparison"><span>Mevcut: <b>{old.name}</b></span><span>{money(old.priceMinor)} → <b>{money(r.priceMinor)}</b></span></div>}
 <div className="ai-fields"><label>Ürün adı<input aria-label={`Ürün adı ${i+1}`} maxLength={250} value={r.name} onChange={e=>change(i,{name:e.target.value})}/></label><label>Kategori<select aria-label={`Kategori ${i+1}`} value={r.categoryKey} onChange={e=>change(i,{categoryKey:e.target.value})}><option value="">Kategori seçin</option>{list?.categories.map(c=><option key={c.key} value={c.key}>{c.title}</option>)}</select></label><label>Fiyat (TL)<PriceInput key={`${job.id}-${i}`} value={r.priceMinor} set={v=>change(i,{priceMinor:v})}/></label><label>Porsiyon / birim<input maxLength={120} value={r.serving} onChange={e=>change(i,{serving:e.target.value})} placeholder="Örn. adet, porsiyon, kg"/></label></div>
 <details><summary>Açıklama ve seçenekleri düzenle</summary><label>Kaynak açıklaması<textarea value={r.description} maxLength={1000} onChange={e=>change(i,{description:e.target.value})}/></label><label>Aynı fiyatlı seçenekler — her satıra bir seçenek<textarea value={r.options.join('\n')} onChange={e=>change(i,{options:e.target.value.split('\n').filter(Boolean).slice(0,20)})}/></label></details>
 <p className="ai-source-quote">Sayfa {r.sourcePage} · “{r.sourceText}”</p>{r.warnings.map((w,k)=><p className="ai-warning" key={k}>{w}</p>)}{r.priceMinor===null&&<p className="ai-warning">Fiyat okunamadı. Yeni ürün satışa kapalı eklenir; mevcut ürün güncellenecekse fiyatı tamamlayın.</p>}</article>;})}
 {!rows.length&&<p>Belgede okunabilir ürün bulunamadı. Daha net bir fotoğrafla yeni aktarım başlatın.</p>}
 <div className="ai-apply"><label className="ai-ack"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Seçtiğim ürünlerin adını, porsiyonunu, fiyatını ve aynı fiyatlı seçeneklerini kontrol ettim. Bu değişiklikler canlı menüye uygulanabilir.</label><div className="ai-upload-buttons"><button className="btn" disabled={busy||!dirty} onClick={()=>void save()}>Taslağı kaydet</button><button className="btn primary" disabled={busy||!confirmed||selected===0||rows.some(r=>r.action!=='skip'&&(!r.categoryKey||!r.name.trim()||r.action==='update'&&r.priceMinor===null))} onClick={()=>void apply()}>{busy?'İşleniyor…':`${selected} değişikliği menüye uygula`}</button></div></div></>}
 {job.status==='applied'&&<div className="ai-empty"><span aria-hidden>✓</span><h3>{job.apply_receipt?.changed??0} ürün değişikliği uygulandı</h3><p>Tekrar açmak veya aynı belgeyi tekrar yüklemek yeni ürün oluşturmaz. Sonradan değişen ürünleri ezmeden geri alma yapılır.</p><a className="btn primary" href="/bahcesehir" target="_blank" rel="noopener noreferrer">Canlı menüyü aç</a><button className="btn" disabled={busy} onClick={()=>void undo()}>Bu aktarımı geri al</button></div>}
 {job.status==='reverted'&&<p className="notice">Geri alma tamamlandı. Eski ürün alanları geri getirildi; yeni ürünler silinmeden satışa kapatıldı.</p>}
 </div></div></Card>}
 </section>;
}
function PriceInput({value,set}:{value:string|null;set:(n:string|null)=>void}){const[t,setT]=useState(minorToTl(value)),[bad,setBad]=useState(false);return <><input inputMode="decimal" value={t} aria-invalid={bad} onChange={e=>{const v=e.target.value;setT(v);try{set(tlToMinor(v));setBad(false);}catch{setBad(true);set(null);}}}/>{bad&&<small role="alert">150 veya 150,50 şeklinde girin.</small>}</>;}
