'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card} from './Shell';
import styles from './AssistantCommands.module.css';
import {availabilityCommand,undoCommand,pendingKey,parsePending,type AssistantProduct,type PendingAssistantCommand} from '@/src/assistant/commands';
type History={id:string;action:'set-product-availability'|'undo-product-availability';productId:string;productName:string;before:{available:boolean;updatedAt:string};after:{available:boolean;updatedAt:string};reason:string;createdAt:string;reversesCommandId:string|null};
type Snapshot={scopeKey:string;products:AssistantProduct[];history:History[]};
const commandMessages:Record<string,string>={ASSISTANT_COMMAND_UNKNOWN:'İşlem sunucuya ulaşmış olabilir. Yeni komut oluşturmayın; aynı işlemin sonucunu kontrol edin.',INVALID_ASSISTANT_COMMAND:'Komut bilgilerini ve gerekçeyi kontrol edin.',IDEMPOTENCY_CONFLICT:'Aynı işlem kimliği farklı bir istekle kullanılamaz.',ALREADY_IN_STATE:'Ürün zaten seçtiğiniz durumda.',COMMAND_ALREADY_UNDONE:'Bu değişiklik daha önce geri alınmış.',COMMAND_NOT_FOUND:'Geri alınacak komut bulunamadı.',PRODUCT_CHANGED:'Ürün başka bir oturumda değişti. Yenileyip yeniden deneyin.',PLATFORM_SERVICE_PAUSED:'Bu hizmet şirket yönetimi tarafından geçici olarak durduruldu.',MANAGER_REQUIRED:'Yönetici yetkisi gerekiyor.'};
const explainCommand=(e:unknown)=>e instanceof Error?(commandMessages[e.message]??'İşlem tamamlanamadı. Yeniden deneyin.'):'İşlem tamamlanamadı.';
async function call<T>(url:string,data?:unknown):Promise<T>{try{const r=await fetch(url,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});const v=await r.json();if(!r.ok)throw new Error(v.error?.code??'REQUEST_FAILED');return v;}catch(e){if(e instanceof Error&&/^[A-Z0-9_]+$/.test(e.message))throw e;if(data!==undefined)throw new Error('ASSISTANT_COMMAND_UNKNOWN');throw e;}}
export function AssistantCommands(){
 const[state,setState]=useState<Snapshot|null>(null),[productId,setProductId]=useState(''),[desired,setDesired]=useState<'available'|'unavailable'>('available'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[pending,setPending]=useState<PendingAssistantCommand|null>(null),[undoTarget,setUndoTarget]=useState<string|null>(null);
 const product=state?.products.find(p=>p.id===productId)||null;const reversed=useMemo(()=>new Set((state?.history||[]).map(h=>h.reversesCommandId).filter(Boolean) as string[]),[state]);
 async function load(){try{const s=await call<Snapshot>('/api/assistant-commands/status');setState(s);if(!productId&&s.products[0])setProductId(s.products[0].id);const saved=parsePending(sessionStorage.getItem(pendingKey(s.scopeKey)));setPending(saved);}catch(e){setError(explainCommand(e));}}
 useEffect(()=>{void load();},[]);
 function savePending(p:PendingAssistantCommand|null){setPending(p);if(!state)return;const key=pendingKey(state.scopeKey);if(p)sessionStorage.setItem(key,JSON.stringify(p));else sessionStorage.removeItem(key);}
 async function execute(p:PendingAssistantCommand){if(busy)return;setBusy(true);setError('');setNote('');savePending(p);try{const result=await call<any>('/api/assistant-commands/'+(p.kind==='apply'?'apply':'undo'),p.request);savePending(null);setConfirmed(false);setReason('');setUndoTarget(null);setNote(result.duplicate?'Aynı işlemin kayıtlı sonucu doğrulandı.':'İşlem kaydedildi. Ürün fiyatı değiştirilmedi.');await load();}catch(e){const code=e instanceof Error?e.message:'';setError(explainCommand(e));if(code!=='ASSISTANT_COMMAND_UNKNOWN')savePending(null);if(['PRODUCT_CHANGED','ALREADY_IN_STATE','COMMAND_ALREADY_UNDONE','COMMAND_NOT_FOUND','PLATFORM_SERVICE_PAUSED'].includes(code))await load();}finally{setBusy(false);}}
 function apply(){if(!state||!product||!confirmed)return;try{void execute({kind:'apply',request:availabilityCommand(crypto.randomUUID(),product,desired==='available',reason)});}catch(e){setError(explainCommand(e));}}
 function undo(id:string){try{void execute({kind:'undo',request:undoCommand(crypto.randomUUID(),id,'Yönetici tarafından geri alma onayı')});}catch(e){setError(explainCommand(e));}}
 const pendingProduct=pending?.kind==='apply'?state?.products.find(p=>p.id===pending.request.productId):null;
 return <Card className={`assistant-commands ${styles.root}`}><div className="section-heading"><div><p className="eyebrow">İZİNLİ İŞLETME KOMUTLARI</p><h2>Öneriyi siz uygularsınız</h2></div><span className="tag muted">İnsan onaylı</span></div>
 <p>AI veya sistem önerisi hiçbir ürünü kendiliğinden değiştiremez. Buradan yalnız ürünün satışa açık/kapalı durumunu, güncel kayıt kontrolü ve açık onayla değiştirebilirsiniz. Fiyat, içerik, sipariş ve ödeme etkilenmez.</p>
 {error&&<p className="alert" role="alert">{error}</p>}{note&&<p className="notice" role="status">{note}</p>}
 {pending?<div className="notice"><strong>Önceki komutun sonucu doğrulanıyor.</strong><p>{pending.kind==='apply'?(pendingProduct?.name||'Ürün')+' için aynı satış durumu komutu yeniden kontrol edilecek.':'Aynı geri alma komutu yeniden kontrol edilecek.'} Yeni işlem kimliği oluşturulmayacak.</p><button className="btn" disabled={busy} onClick={()=>void execute(pending)}>{busy?'Kontrol ediliyor…':'Aynı işlemin sonucunu kontrol et'}</button></div>:<div className="llm-form">
 <label>Ürün<select value={productId} disabled={busy} onChange={e=>{setProductId(e.target.value);setConfirmed(false);}}><option value="">Ürün seçin</option>{state?.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.available?'Satışta':'Kapalı'}</option>)}</select></label>
 <label>Yeni durum<select value={desired} disabled={busy} onChange={e=>{setDesired(e.target.value as 'available'|'unavailable');setConfirmed(false);}}><option value="available">Satışa aç</option><option value="unavailable">Satışa kapat</option></select></label>
 <label>Gerekçe<input maxLength={200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Örn. ürün bugün tükendi"/></label>
 <label className="llm-check"><input type="checkbox" checked={confirmed} disabled={busy||!product||product.available===(desired==='available')} onChange={e=>setConfirmed(e.target.checked)}/><span>{product?`${product.name} ürününü ${desired==='available'?'satışa açmayı':'satışa kapatmayı'} onaylıyorum.`:'Önce ürün seçin.'}</span></label>
 <button className="btn primary" disabled={busy||!product||!confirmed||reason.trim().length<5||product.available===(desired==='available')} onClick={apply}>{busy?'Kaydediliyor…':'Onaylı durumu uygula'}</button>
 </div>}
 {!!state?.history.length&&<details><summary>Son onaylı komutlar ({state.history.length})</summary><div className={`${styles.history} assistant-command-history`}>{state.history.slice(0,12).map(h=><div className={`${styles.source} llm-source`} key={h.id}><strong>{h.productName}</strong><p>{h.action==='set-product-availability'?(h.after.available?'Satışa açıldı':'Satışa kapatıldı'):'Önceki değişiklik geri alındı'} · {new Date(h.createdAt).toLocaleString('tr-TR')}</p><small>{h.reason}</small>{h.action==='set-product-availability'&&!reversed.has(h.id)&&<div className={`${styles.actions} llm-actions`}>{undoTarget===h.id?<><button className="btn" disabled={busy} onClick={()=>void undo(h.id)}>Geri almayı onayla</button><button className="text-button" disabled={busy} onClick={()=>setUndoTarget(null)}>Vazgeç</button></>:<button className="text-button" disabled={busy||!!pending} onClick={()=>setUndoTarget(h.id)}>Bu değişikliği geri al</button>}</div>}</div>)}</div></details>}
 <p className="helper">Komutlar serbest SQL çalıştırmaz; yalnız izinli alanı değiştirir. Ürün başka bir oturumda değişmişse işlem reddedilir. Şirket AI anahtarı kapalıysa yeni asistan komutu durur, mevcut komutun güvenli geri alması açık kalır.</p>
 </Card>;
}
