'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from './transport';
import {readCampaign,FORMATS,type CampaignSnapshot,type CampaignFormat} from '@/src/campaigns/contracts';
import {renderCampaign,campaignBlob} from '@/src/campaigns/render';
const ERRORS:Record<string,string>={CAMPAIGN_SOURCE_CHANGED:'Ürün veya fiyat değişti. Yeni önizlemeyi inceleyip yeniden hazırlayın.',PRODUCT_NOT_ADVERTISABLE:'Ürün satışa kapalı veya fiyatı onaysız. Görsel hazırlanamaz.',CAMPAIGN_REVIEW_REQUIRED:'Bu kampanya taslağı incelenmemiş, kaldırılmış veya süresi dolmuş.',PLATFORM_SERVICE_PAUSED:'Sosyal yayın isteği şirket tarafından şu anda kapalı.',PUBLICATION_NOT_FOUND:'Yayın isteği bulunamadı.',PUBLICATION_NOT_CANCELLABLE:'Bu yayın isteği artık iptal edilebilir durumda değil.',PUBLICATION_ALREADY_CANCELLED:'Yayın isteği daha önce iptal edilmiş.',IDEMPOTENCY_CONFLICT:'Aynı işlem kimliği farklı içerikle kullanılmış. Güncel durumu yükleyin.',MANAGER_REQUIRED:'İşletme sahibi veya yönetici yetkisi gerekiyor.',UNAUTHENTICATED:'İşletme hesabınızla giriş yapın.',TEXT_DOES_NOT_FIT:'Ürün metni şablona sığmıyor. Kısaltmadan dışa aktarılmadı.'};
const explain=(e:unknown)=>ERRORS[e instanceof Error?e.message:'']||'İşlem tamamlanamadı. Hiçbir sosyal paylaşım veya katalog değişikliği yapılmadı.';
type Product={id:string;name:string;priceMinor:string|null;available:boolean};
type Draft={id:string;productId:string;title:string};
type PublicationItem={id:string;productId:string;network:string;format:string;state:string;sourceVersion:string;createdAt:string;updatedAt:string};
type PublicationState={enabled:boolean;dispatchConfigured:boolean;items:PublicationItem[]};
type PendingPublication={operationId:string;productId:string;jobId:string|null;expectedVersion:string;format:CampaignFormat;network:'instagram'};
const pendingKey='menugo-social-publication-v1';
export function CampaignStudio(){
 const [catalogue,setCatalogue]=useState<Product[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[product,setProduct]=useState(''),[job,setJob]=useState('');
 const [snapshot,setSnapshot]=useState<CampaignSnapshot|null>(null),[format,setFormat]=useState<CampaignFormat>('post'),[error,setError]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false),[ready,setReady]=useState(false),[confirmed,setConfirmed]=useState(false),[caption,setCaption]=useState(''),[refresh,setRefresh]=useState(0);
 const [publication,setPublication]=useState<PublicationState|null>(null),[publishing,setPublishing]=useState(false),[pendingPublication,setPendingPublication]=useState<PendingPublication|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),generation=useRef(0),renderVersion=useRef(0),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;let active=true;try{const raw=sessionStorage.getItem(pendingKey);if(raw){const p=JSON.parse(raw) as PendingPublication;if(p&&typeof p.operationId==='string'&&typeof p.productId==='string'&&typeof p.expectedVersion==='string')setPendingPublication(p);else sessionStorage.removeItem(pendingKey);}}catch{setError('Bekleyen yayın isteği kaydı okunamadı. Yeni istek oluşturmadan önce durumu yenileyin.');}
 void api('/api/campaigns/catalogue').then(d=>{if(active){setCatalogue(d.products);setDrafts(d.drafts);setProduct(d.products.find((p:Product)=>p.available&&p.priceMinor!==null)?.id||'');setLoading(false);}}).catch(e=>{if(active){setError(explain(e));setLoading(false);}});return()=>{active=false;mounted.current=false;generation.current++;renderVersion.current++;};},[]);
 useEffect(()=>{const g=++generation.current;setReady(false);setSnapshot(null);setConfirmed(false);setCaption('');setPublication(null);if(!product)return;setLoading(true);setError('');const q=new URLSearchParams({productId:product,...(job?{jobId:job}:{})});
 void Promise.all([api('/api/campaigns/preview?'+q),api('/api/campaigns/publication-status?productId='+encodeURIComponent(product))]).then(([preview,pub])=>{if(g===generation.current){setSnapshot(readCampaign(preview));setPublication(pub as PublicationState);}}).catch(e=>{if(g===generation.current)setError(explain(e));}).finally(()=>{if(g===generation.current)setLoading(false);});},[product,job,refresh]);
 useEffect(()=>{const r=++renderVersion.current;setReady(false);setConfirmed(false);if(!snapshot)return;const offscreen=document.createElement('canvas');void renderCampaign(offscreen,snapshot,format).then(()=>{if(r!==renderVersion.current||!canvas.current)return;canvas.current.width=offscreen.width;canvas.current.height=offscreen.height;canvas.current.getContext('2d')!.drawImage(offscreen,0,0);setReady(true);}).catch(e=>{if(r===renderVersion.current)setError(explain(e));});return()=>{renderVersion.current++;};},[snapshot,format]);
 async function download(){if(!snapshot||!ready||!confirmed||exporting)return;const g=generation.current,r=renderVersion.current,captured=snapshot,capturedFormat=format;setExporting(true);setError('');setStatus('Güncel fiyat ve uygunluk kontrol ediliyor…');
  try{const payload={productId:captured.productId,jobId:job||null,expectedVersion:captured.version,format:capturedFormat};const checked=await api('/api/campaigns/export',payload);const exact=readCampaign(checked.snapshot);if(exact.version!==captured.version)throw Error('CAMPAIGN_SOURCE_CHANGED');
   const target=document.createElement('canvas');await renderCampaign(target,exact,capturedFormat);const blob=await campaignBlob(target);
   await api('/api/campaigns/export',payload);if(!mounted.current||g!==generation.current||r!==renderVersion.current)return;
   const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`menugo-${captured.productId}-${capturedFormat}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setCaption(checked.caption);setStatus('PNG hazır. Sosyal hesabınıza otomatik gönderilmedi.');
  }catch(e){if(mounted.current&&g===generation.current){setError(explain(e));setStatus('');setConfirmed(false);}}
  finally{if(mounted.current)setExporting(false);}
 }
 async function refreshPublication(){if(!product)return;try{setPublication(await api('/api/campaigns/publication-status?productId='+encodeURIComponent(product)));}catch(e){setError(explain(e));}}
 async function requestPublication(replay?:PendingPublication){if(publishing)return;const payload=replay??(snapshot&&ready&&confirmed?{operationId:crypto.randomUUID(),productId:snapshot.productId,jobId:job||null,expectedVersion:snapshot.version,format,network:'instagram' as const}:null);if(!payload)return;
  setPublishing(true);setError('');setStatus('Yayın isteği doğrulanıyor…');try{sessionStorage.setItem(pendingKey,JSON.stringify(payload));setPendingPublication(payload);}catch{setPublishing(false);setError('Güvenli tekrar kaydı oluşturulamadı. Yayın isteği gönderilmedi.');return;}
  try{const result=await api('/api/campaigns/publication-request',payload);sessionStorage.removeItem(pendingKey);setPendingPublication(null);setStatus(result.dispatchConfigured?'Yayın isteği sıraya alındı.':'Yayın isteği kaydedildi. Şirket sosyal hesap bağlantısı hazır olmadığı için dış hesaba hiçbir gönderi yapılmadı.');await refreshPublication();}
  catch(e){const code=e instanceof Error?e.message:'';if(['CAMPAIGN_SOURCE_CHANGED','PRODUCT_NOT_ADVERTISABLE','CAMPAIGN_REVIEW_REQUIRED','PLATFORM_SERVICE_PAUSED','IDEMPOTENCY_CONFLICT'].includes(code)){sessionStorage.removeItem(pendingKey);setPendingPublication(null);setConfirmed(false);}setError(explain(e));setStatus('');}
  finally{setPublishing(false);}
 }
 async function cancelPublication(id:string){if(publishing)return;setPublishing(true);setError('');try{await api('/api/campaigns/publication-cancel',{operationId:crypto.randomUUID(),publicationId:id});setStatus('Yayın isteği iptal edildi. Dış hesaba gönderim yapılmadı.');await refreshPublication();}catch(e){setError(explain(e));}finally{setPublishing(false);}}
 const queued=publication?.items.find(i=>i.state==='awaiting_platform_connection');
 return <main className="campaign-page"><header><Link className="btn" href="/isletme">← İşletme paneli</Link><Link className="btn" href="/isletme/studyo">İçerik stüdyosu</Link></header><p className="eyebrow">ÜRÜNDEN PAYLAŞIMA</p><h1>Markanızla, menünüzden.</h1><p>Onaylı ürün ve fiyatla gönderi veya hikâye hazırlayın. Orijinal logolar korunur; fotoğraf ve malzeme uydurulmaz.</p>
 {error&&<p role="alert" className="notice">{error}</p>}{status&&<p role="status" className="notice">{status}</p>}
 {pendingPublication&&<section className="card"><h2>Sonucu belirsiz yayın isteği</h2><p>Aynı işlem kimliği ve aynı ürün kanıtı korunuyor. Yeni istek oluşturmak yerine aynı isteği kontrol ederek yeniden deneyin.</p><button className="btn" disabled={publishing} onClick={()=>void requestPublication(pendingPublication)}>Aynı isteği kontrol et / yeniden dene</button></section>}
 <div className="campaign-grid"><section className="card"><h2>Paylaşımınızı hazırlayın</h2><label htmlFor="campaign-product">Ürün</label><select id="campaign-product" value={product} disabled={exporting||publishing||!catalogue.length} onChange={e=>{setProduct(e.target.value);setJob('');setStatus('');}}><option value="">Ürün seçin</option>{catalogue.map(p=><option key={p.id} value={p.id} disabled={!p.available||p.priceMinor===null}>{p.name}{!p.available||p.priceMinor===null?' — yayına uygun değil':''}</option>)}</select>
 <label htmlFor="campaign-caption-source">Açıklama kaynağı</label><select id="campaign-caption-source" value={job} disabled={exporting||publishing} onChange={e=>setJob(e.target.value)}><option value="">Mevcut katalog bilgisi</option>{drafts.filter(d=>d.productId===product).map(d=><option key={d.id} value={d.id}>İncelenmiş taslak: {d.title}</option>)}</select>
 <label htmlFor="campaign-format">Boyut</label><select id="campaign-format" value={format} disabled={exporting||publishing} onChange={e=>setFormat(e.target.value as CampaignFormat)}><option value="post">Instagram gönderisi · 1080 × 1350</option><option value="story">Instagram hikâyesi · 1080 × 1920</option></select>
 <p className="helper">Bu, fotoğrafsız marka şablonudur; AI fotoğraf üretimi değildir. İndirilen görsel ürünün menü bağlantısına giden QR içerir.</p>
 <label className="campaign-confirm"><input type="checkbox" checked={confirmed} disabled={!ready||loading||exporting||publishing} onChange={e=>setConfirmed(e.target.checked)}/> Ürün, fiyat, seçenek ve açıklama bilgilerini inceledim.</label>
 <button className="btn primary full" disabled={!ready||loading||!confirmed||exporting||publishing} onClick={()=>void download()}>{exporting?'Doğrulanıyor…':'PNG görselini indir'}</button><button className="btn full" disabled={exporting||publishing||!product} onClick={()=>setRefresh(x=>x+1)}>Güncel bilgilerle yenile</button>
 <p className="helper">İndirmeden önce güncel fiyat yeniden kontrol edilir. İndirilen dosya fiyat değiştiğinde kendiliğinden güncellenmez; paylaşmadan önce yeniden oluşturun.</p>
 <hr/><h2>Yetkili sosyal yayın</h2><p className="helper">İşletme yalnız incelenmiş kampanya için yayın isteği verir. Sosyal sağlayıcı, hesap bağlantısı ve teknik gönderim MenüGO şirket yönetimindedir.</p>
 {publication&&!publication.enabled&&<p className="helper">Şirket sosyal yayın isteğini henüz açmadı. Bu durum görsel indirmenizi engellemez.</p>}
 {publication?.enabled&&<button className="btn full" disabled={!ready||!confirmed||publishing||!!pendingPublication} onClick={()=>void requestPublication()}>{publishing?'Kontrol ediliyor…':'Instagram yayın isteği oluştur'}</button>}
 {publication?.enabled&&!publication.dispatchConfigured&&<p className="helper">Şirket sosyal hesap bağlantısı yapılandırılmamış. İstek kaydedilebilir; dış hesaba otomatik gönderim yapılmaz.</p>}
 {queued&&<div className="notice"><strong>Bekleyen yayın isteği</strong><p>{new Date(queued.createdAt).toLocaleString('tr-TR')} · {queued.format==='story'?'Hikâye':'Gönderi'} · dış sağlayıcıya gönderilmedi.</p><button className="btn" disabled={publishing} onClick={()=>void cancelPublication(queued.id)}>İsteği iptal et</button></div>}
 {snapshot&&<details open><summary>Gönderi açıklaması</summary><p className="campaign-caption">{snapshot.caption}</p></details>}
 {caption&&<><label htmlFor="campaign-ready-caption">Paylaşıma hazır metin</label><textarea id="campaign-ready-caption" readOnly rows={8} value={caption}/><button className="btn" onClick={()=>void navigator.clipboard.writeText(caption).then(()=>setStatus('Açıklama kopyalandı.')).catch(()=>setError('Metni seçip kopyalayabilirsiniz.'))}>Açıklamayı kopyala</button></>}
 </section><section className="card campaign-preview" aria-label="Görsel önizlemesi"><h2>{loading?'Yükleniyor…':'Önizleme'}</h2><canvas ref={canvas} aria-label={snapshot?`${snapshot.name} — paylaşım görseli`:'Paylaşım görseli'} style={{aspectRatio:`${FORMATS[format].width}/${FORMATS[format].height}`,visibility:ready?'visible':'hidden'}}/><p className="helper">Orijinal Sarıyer Börekçisi ve MenüGO logoları · Beyaz alt bölüm</p></section></div></main>;
}
