'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from './transport';
import {readCampaign,FORMATS,type CampaignSnapshot,type CampaignFormat} from '@/src/campaigns/contracts';
import {renderCampaign,campaignBlob} from '@/src/campaigns/render';
const ERRORS:Record<string,string>={CAMPAIGN_SOURCE_CHANGED:'Ürün veya fiyat değişti. Yeni önizlemeyi inceleyip yeniden indirin.',PRODUCT_NOT_ADVERTISABLE:'Ürün satışa kapalı veya fiyatı onaysız. Görsel indirilemez.',CAMPAIGN_REVIEW_REQUIRED:'Bu kampanya taslağı incelenmemiş, kaldırılmış veya süresi dolmuş.',MANAGER_REQUIRED:'İşletme sahibi veya yönetici yetkisi gerekiyor.',UNAUTHENTICATED:'İşletme hesabınızla giriş yapın.',TEXT_DOES_NOT_FIT:'Ürün metni şablona sığmıyor. Kısaltmadan dışa aktarılmadı.'};
const explain=(e:unknown)=>ERRORS[e instanceof Error?e.message:'']||'İşlem tamamlanamadı. Hiçbir sosyal paylaşım veya katalog değişikliği yapılmadı.';
type Product={id:string;name:string;priceMinor:string|null;available:boolean};
type Draft={id:string;productId:string;title:string};
export function CampaignStudio(){
 const [catalogue,setCatalogue]=useState<Product[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[product,setProduct]=useState(''),[job,setJob]=useState('');
 const [snapshot,setSnapshot]=useState<CampaignSnapshot|null>(null),[format,setFormat]=useState<CampaignFormat>('post'),[error,setError]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false),[ready,setReady]=useState(false),[confirmed,setConfirmed]=useState(false),[caption,setCaption]=useState(''),[refresh,setRefresh]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null),generation=useRef(0),renderVersion=useRef(0),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;let active=true;void api('/api/campaigns/catalogue').then(d=>{if(active){setCatalogue(d.products);setDrafts(d.drafts);setProduct(d.products.find((p:Product)=>p.available&&p.priceMinor!==null)?.id||'');setLoading(false);}}).catch(e=>{if(active){setError(explain(e));setLoading(false);}});return()=>{active=false;mounted.current=false;generation.current++;renderVersion.current++;};},[]);
 useEffect(()=>{const g=++generation.current;setReady(false);setSnapshot(null);setConfirmed(false);setCaption('');if(!product)return;setLoading(true);setError('');const q=new URLSearchParams({productId:product,...(job?{jobId:job}:{})});void api('/api/campaigns/preview?'+q).then(d=>{if(g===generation.current)setSnapshot(readCampaign(d));}).catch(e=>{if(g===generation.current)setError(explain(e));}).finally(()=>{if(g===generation.current)setLoading(false);});},[product,job,refresh]);
 useEffect(()=>{const r=++renderVersion.current;setReady(false);setConfirmed(false);if(!snapshot)return;const offscreen=document.createElement('canvas');void renderCampaign(offscreen,snapshot,format).then(()=>{if(r!==renderVersion.current||!canvas.current)return;canvas.current.width=offscreen.width;canvas.current.height=offscreen.height;canvas.current.getContext('2d')!.drawImage(offscreen,0,0);setReady(true);}).catch(e=>{if(r===renderVersion.current)setError(explain(e));});return()=>{renderVersion.current++;};},[snapshot,format]);
 async function download(){if(!snapshot||!ready||!confirmed||exporting)return;const g=generation.current,r=renderVersion.current,captured=snapshot,capturedFormat=format;setExporting(true);setError('');setStatus('Güncel fiyat ve uygunluk kontrol ediliyor…');
  try{const payload={productId:captured.productId,jobId:job||null,expectedVersion:captured.version,format:capturedFormat};const checked=await api('/api/campaigns/export',payload);const exact=readCampaign(checked.snapshot);if(exact.version!==captured.version)throw Error('CAMPAIGN_SOURCE_CHANGED');
   const target=document.createElement('canvas');await renderCampaign(target,exact,capturedFormat);const blob=await campaignBlob(target);
   // Check again after rendering. Download is never a stale async response side effect.
   await api('/api/campaigns/export',payload);if(!mounted.current||g!==generation.current||r!==renderVersion.current)return;
   const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`menugo-${captured.productId}-${capturedFormat}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setCaption(checked.caption);setStatus('PNG hazır. Sosyal hesabınıza otomatik gönderilmedi.');
  }catch(e){if(mounted.current&&g===generation.current){setError(explain(e));setStatus('');setConfirmed(false);}}
  finally{if(mounted.current)setExporting(false);}
 }
 return <main className="campaign-page"><header><Link className="btn" href="/isletme">← İşletme paneli</Link><Link className="btn" href="/isletme/studyo">İçerik stüdyosu</Link></header><p className="eyebrow">ÜRÜNDEN PAYLAŞIMA</p><h1>Markanızla, menünüzden.</h1><p>Onaylı ürün ve fiyatla gönderi veya hikâye hazırlayın. Orijinal logolar korunur; fotoğraf ve malzeme uydurulmaz.</p>
 {error&&<p role="alert" className="notice">{error}</p>}{status&&<p role="status" className="notice">{status}</p>}
 <div className="campaign-grid"><section className="card"><h2>Paylaşımınızı hazırlayın</h2><label htmlFor="campaign-product">Ürün</label><select id="campaign-product" value={product} disabled={exporting||!catalogue.length} onChange={e=>{setProduct(e.target.value);setJob('');setStatus('');}}><option value="">Ürün seçin</option>{catalogue.map(p=><option key={p.id} value={p.id} disabled={!p.available||p.priceMinor===null}>{p.name}{!p.available||p.priceMinor===null?' — yayına uygun değil':''}</option>)}</select>
 <label htmlFor="campaign-caption-source">Açıklama kaynağı</label><select id="campaign-caption-source" value={job} disabled={exporting} onChange={e=>setJob(e.target.value)}><option value="">Mevcut katalog bilgisi</option>{drafts.filter(d=>d.productId===product).map(d=><option key={d.id} value={d.id}>İncelenmiş taslak: {d.title}</option>)}</select>
 <label htmlFor="campaign-format">Boyut</label><select id="campaign-format" value={format} disabled={exporting} onChange={e=>setFormat(e.target.value as CampaignFormat)}><option value="post">Instagram gönderisi · 1080 × 1350</option><option value="story">Instagram hikâyesi · 1080 × 1920</option></select>
 <p className="helper">Bu, fotoğrafsız marka şablonudur; AI fotoğraf üretimi değildir. İndirilen görsel ürünün menü bağlantısına giden QR içerir.</p>
 <label className="campaign-confirm"><input type="checkbox" checked={confirmed} disabled={!ready||loading||exporting} onChange={e=>setConfirmed(e.target.checked)}/> Ürün, fiyat, seçenek ve açıklama bilgilerini inceledim.</label>
 <button className="btn primary full" disabled={!ready||loading||!confirmed||exporting} onClick={()=>void download()}>{exporting?'Doğrulanıyor…':'PNG görselini indir'}</button><button className="btn full" disabled={exporting||!product} onClick={()=>setRefresh(x=>x+1)}>Güncel bilgilerle yenile</button>
 <p className="helper">İndirmeden önce güncel fiyat yeniden kontrol edilir. İndirilen dosya fiyat değiştiğinde kendiliğinden güncellenmez; paylaşmadan önce yeniden oluşturun.</p>
 {snapshot&&<details open><summary>Gönderi açıklaması</summary><p className="campaign-caption">{snapshot.caption}</p></details>}
 {caption&&<><label htmlFor="campaign-ready-caption">Paylaşıma hazır metin</label><textarea id="campaign-ready-caption" readOnly rows={8} value={caption}/><button className="btn" onClick={()=>void navigator.clipboard.writeText(caption).then(()=>setStatus('Açıklama kopyalandı.')).catch(()=>setError('Metni seçip kopyalayabilirsiniz.'))}>Açıklamayı kopyala</button></>}
 </section><section className="card campaign-preview" aria-label="Görsel önizlemesi"><h2>{loading?'Yükleniyor…':'Önizleme'}</h2><canvas ref={canvas} aria-label={snapshot?`${snapshot.name} — paylaşım görseli`:'Paylaşım görseli'} style={{aspectRatio:`${FORMATS[format].width}/${FORMATS[format].height}`,visibility:ready?'visible':'hidden'}}/><p className="helper">Orijinal Sarıyer Börekçisi ve MenüGO logoları · Beyaz alt bölüm</p></section></div></main>;
}
