'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {getBrowserClient} from '@/lib/supabase/browser';
import {Brand,Card,Empty} from './Shell';
import {api,explain,money,label} from './transport';
import {splitEqual,tipFor} from '@/src/money/split';
import catalog from '@/data/catalog.json';
import {ServiceInsights,ServiceControls,TableOrderingPolicy} from './ServiceInsights';
import {BusyMode,FeedbackInbox,DailyServiceReport} from './ServiceExperience';
import {KitchenBoard} from './KitchenBoard';
import {Handover} from './Handover';
import {TableAccessRequests,PermanentTableQR} from './TableAccess';
import {ProductInformation} from './ProductInformation';
import {MerchantAdmin} from './MerchantAdmin';
import {PriceEditor,TableInvitation,PilotSettings,Counter} from './Pilot';
type Tab='reports'|'feedback'|'profile'|'staff'|'requests'|'qr'|'menu'|'overview'|'tables'|'kitchen'|'orders'|'checkout'|'courier'|'loyalty'|'crm'|'upsell'|'settings';
const tabs:[Tab,string,string][]=[['overview','Genel bakış','◫'],['reports','Günlük rapor','▥'],['feedback','Müşteri görüşleri','☆'],['menu','Menü & Fiyatlar','▤'],['tables','Masalar & Sepet','▦'],['kitchen','Mutfak ekranı','♨'],['orders','Siparişler','≡'],['checkout','Ödemeler','◈'],['courier','Kurye & Paket','↗'],['loyalty','Sadakat','◇'],['crm','Müşteriler & CRM','◎'],['upsell','Çapraz satış','✦'],['settings','Ayarlar','⚙'],['profile','İşletme profili','⌂'],['staff','Personel & Yetkiler','♙'],['requests','Masa çağrıları','♧'],['qr','Menü QR kodu','▣']];
const demoState=()=>({role:'owner',tables:[{id:'demo14',name:'Masa 14',status:'open',checkId:'demo-check',revision:'42'},{id:'demo7',name:'Masa 7',status:'checkout',checkId:'demo-check2',revision:'19'},{id:'demo3',name:'Masa 3',status:'empty'}],orders:[{id:'demo-order-1',checkId:'demo-check',table:'Masa 14',status:'submitted',createdAt:new Date().toISOString(),lines:[{name:'Klasik Sandviç',quantity:2,amountMinor:'32000'},{name:'Çay',quantity:2,amountMinor:'5000'}]},{id:'demo-order-2',checkId:'demo-check2',table:'Masa 7',status:'preparing',createdAt:new Date().toISOString(),lines:[{name:'Kova Waffle',quantity:1,amountMinor:'25000'}]}],deliveries:[],customers:[],loyalty:[],campaigns:[{id:'demo-campaign',name:'21 Gün Geri Kazanım',mode:'dry_run',days:21,cooldownDays:30,template:'{brand}: Sizi özledik. Size özel fırsatı menümüzde keşfedin. {link} İleti tercihi: {optout}'}],outbox:[],rules:[],features:{payments_enabled:false,loyalty_enabled:false,sms_enabled:false,daas_enabled:false},catalogue:{items:(catalog as any[]).map(x=>({id:x[0],sourceId:x[0],name:x[1],priceMinor:x[4]==null?null:(BigInt(x[4])*100n).toString(),canOrder:false}))},lastCrmRun:null});
export function Console({demo=false,view='merchant'}:{demo?:boolean;view?:'merchant'|'waiter'|'kitchen'|'cashier'}){
 const[tab,setTab]=useState<Tab>(view==='waiter'?'tables':view==='kitchen'?'kitchen':view==='cashier'?'checkout':'overview');const[data,setData]=useState<any>(demo?demoState():null);const[error,setError]=useState('');const[loading,setLoading]=useState(!demo);const[busy,setBusy]=useState(false);const[join,setJoin]=useState('');const[joinName,setJoinName]=useState('Masa');const[joinExpiry,setJoinExpiry]=useState(0);const[requestFilter,setRequestFilter]=useState<string|null>(null);const[requestCounts,setRequestCounts]=useState<Record<string,number>>({});const[plan,setPlan]=useState<any>(null);const[count,setCount]=useState(3);const[tip,setTip]=useState(0);const[demoBase,setDemoBase]=useState('10000');
 async function reload(){if(demo)return;setError('');try{setData(await api('/api/ops/console'));}catch(e){setData(null);setError(explain(e));}finally{setLoading(false);}}
 useEffect(()=>{void reload();if(!demo){const t=setInterval(()=>{if(document.visibilityState==='visible')void reload();},15000);return()=>clearInterval(t);}},[demo]);
 async function action(name:string,payload:Record<string,unknown>){setBusy(true);setError('');try{if(demo){if(name==='order-status')setData((d:any)=>({...d,orders:d.orders.map((o:any)=>o.id===payload.orderId?{...o,status:payload.status}:o)}));else if(name==='create-table')setData((d:any)=>({...d,tables:[...d.tables,{id:crypto.randomUUID(),name:payload.name,status:'empty'}]}));else if(name==='save-campaign')setData((d:any)=>({...d,campaigns:d.campaigns.map((c:any)=>c.id===payload.id?{...c,days:payload.days,template:payload.template}:c)}));else if(name==='save-rule')setData((d:any)=>({...d,rules:[...d.rules,{id:crypto.randomUUID(),target:d.catalogue.items.find((p:any)=>p.sourceId===payload.target)?.name,recommendation:d.catalogue.items.find((p:any)=>p.sourceId===payload.recommended)?.name,active:true}]}));return;}
 await api(name==='reject-order'?'/api/merchant/reject-order':'/api/ops/'+name,payload);await reload();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 async function openTable(t:any){setJoinName(t.name);setBusy(true);setError('');try{if(demo){setJoin('/deneyim?table=14');setJoinExpiry(Date.now()+600000);return;}const v=await api('/api/ops/start-table',{tableId:t.id});setJoin((location.hostname.endsWith('menugo.app')?'https://sariyerborekcisi.menugo.app':location.origin)+'/siparis?check='+v.checkId+'&token='+v.token);setJoinExpiry(Date.now()+Math.max(0,Math.min(600,Number(v.expiresInSeconds??600)))*1000);await reload();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 async function openCheckout(t:any){if(demo){setPlan(null);setTab('checkout');return;}try{setPlan(await api('/api/ops/checkout?check='+t.checkId));setTab('checkout');}catch(e){setError(explain(e));}}
 const visibleTabs=(demo||view==='merchant'&&['owner','manager'].includes(data?.role))?tabs:tabs.filter(t=>(view==='kitchen'?['kitchen','orders']:view==='cashier'?['checkout','orders','requests']:['tables','orders','requests','qr']).includes(t[0]));
 const title=tabs.find(t=>t[0]===tab)?.[1];const orders=data?.orders??[];const tables=data?.tables??[];const manager=['owner','manager'].includes(data?.role);const activeOrders=orders.filter((o:any)=>!['completed','cancelled'].includes(o.status));
 return <div className="workspace"><aside className="sidebar"><Brand/><div className="workspace-name"><span className="shop-avatar">SB</span><div><strong>Sarıyer Börekçisi</strong><small>Bahçeşehir şubesi</small></div></div><p className="side-label">İŞLETME MERKEZİ</p><nav>{visibleTabs.map(([id,text,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span aria-hidden>{icon}</span>{text}{id==='kitchen'&&activeOrders.length>0&&<b>{activeOrders.length}</b>}</button>)}</nav><div className="sidebar-bottom"><Link href="/bahcesehir">Müşteri menüsü ↗</Link><Link href={demo?'/giris':'/deneyim'}>{demo?'Gerçek işletme girişi':'Paneli örnek verilerle incele'}</Link><Link href="/yardim#personel">Kullanım rehberi</Link><small>Yeni Nesil Dijital Menü</small></div></aside><div className="workspace-body"><header className="workspace-top"><span>İşletme / <b>{title}</b></span><div><span className={'tag '+(demo?'amber':'green')}>{demo?'Örnek veri':'Yetkili işletme alanı'}</span>{!demo&&<button className="text-button" onClick={async()=>{await getBrowserClient().auth.signOut();location.assign('/giris');}}>Çıkış</button>}<span className="avatar">GO</span></div></header>
 <main className="workspace-main">{demo&&<div className="demo-banner"><strong>ETKİLEŞİMLİ DEMO</strong><span>Buradaki veriler ve işlemler örnektir. Gerçek sipariş, ödeme, puan veya SMS oluşmaz.</span><Link href="/giris">İşletmeme giriş yap →</Link></div>}<div className="page-heading"><div><p className="eyebrow">MENÜGO / BAHÇEŞEHİR</p><h1>{title}</h1><p>{tab==='overview'?'Günün operasyonu, tek bir bakışta.':tab==='crm'?'Doğru müşteriye, doğru zamanda; yalnızca izinli iletişim.':'İşletmenizin tüm hareketleri, aynı merkezde.'}</p></div><div className="heading-actions"><button className="btn" onClick={()=>void reload()} disabled={loading||demo}>↻ Yenile</button><Link className="btn primary" href="/bahcesehir">Menüyü aç ↗</Link></div></div>
 {error&&<div className="alert" role="alert">{error} <Link href="/giris">Giriş ekranı</Link> <button className="text-button" onClick={async()=>{try{await api('/api/session',{});await reload();}catch(e){setError(explain(e));}}}>Yönetici hesabını eşleştir</button></div>}
 {loading?<Card><p>İşletme verileri yükleniyor…</p></Card>:!data?<Card><Empty title="İşletme hesabınızla giriş yapın" description="Masa, sipariş, müşteri ve finans verileri yalnızca şube yetkisi doğrulandıktan sonra gösterilir."/><div className="center"><Link className="btn primary" href="/giris">Giriş yap</Link><Link className="btn" href="/deneyim">Paneli incele</Link></div></Card>:<>
 {!demo&&manager&&tab==='overview'&&<Handover go={setTab}/>}
 {!demo&&data.role!=='kitchen'&&['overview','tables','requests'].includes(tab)&&<TableAccessRequests tableId={requestFilter} showEmpty={tab==='tables'} onCounts={setRequestCounts} onClear={()=>setRequestFilter(null)}/>}
 {!demo&&['overview','kitchen','orders','requests','tables'].includes(tab)&&<ServiceInsights role={data.role}/>}
 {(['profile','staff','requests','qr'] as string[]).includes(tab)&&!demo&&<MerchantAdmin section={tab as 'profile'|'staff'|'requests'|'qr'}/>}
 {tab==='menu'&&<PriceEditor products={data.products??data.catalogue.items.map((p:any)=>({...p,available:true,approved:false,optionCount:0}))} reload={reload} demo={demo}/>}
 {tab==='menu'&&!demo&&manager&&<ProductInformation/>}
 {tab==='reports'&&!demo&&manager&&<DailyServiceReport/>}
 {tab==='feedback'&&!demo&&manager&&<FeedbackInbox/>}
 {['reports','feedback'].includes(tab)&&demo&&<Card><p>Bu bölüm gerçek işletme kayıtlarını kullanır. Demoda tahsilat veya müşteri yorumu oluşturulmaz.</p></Card>}
 {tab==='settings'&&!demo&&manager&&<><BusyMode/><TableOrderingPolicy/><ServiceControls/></>}
 {tab==='overview'&&<><div className="stats"><Metric title="Açık masa" value={String(tables.filter((t:any)=>t.status!=='empty').length)} note="Açık adisyonlar" icon="▦"/><Metric title="Mutfakta" value={String(activeOrders.length)} note="Aktif siparişler" icon="♨"/><Metric title="Paket servis" value={String(data.deliveries.length)} note="Teslimat işleri" icon="↗"/><Metric title="Onaylı ürün" value={String(data.catalogue.items.filter((p:any)=>p.canOrder).length)} note="Çevrim içi siparişe uygun" icon="✓"/></div><div className="columns"><Card><div className="section-heading"><h2>Canlı operasyon</h2><button className="text-button" onClick={()=>setTab('kitchen')}>Mutfağa git →</button></div>{activeOrders.length?<div className="list">{activeOrders.slice(0,5).map((o:any)=><div className="list-row" key={o.id}><span className="row-icon">♨</span><div><strong>{o.table}</strong><small>{o.lines.map((l:any)=>l.name).join(' · ')}</small></div><span className="tag amber">{label(o.status)}</span></div>)}</div>:<Empty title="Henüz sipariş yok" description="Siparişe açılmış masalardan gelen ürünler burada görünür."/>}</Card><Card className="blue-card"><span className="eyebrow">İŞLETMENİN BÜYÜME DÖNGÜSÜ</span><h2>Bir sonraki ziyareti<br/>bugünden planlayın.</h2><p>Çapraz satış, kişiye ait puan hesabı ve 21 günlük geri kazanım akışı.</p><button className="btn" onClick={()=>setTab('crm')}>CRM akışını incele →</button><div className="growth-flow"><span>Sipariş</span><i>→</i><span>Sadakat</span><i>→</i><span>Tekrar ziyaret</span></div></Card></div><Card><div className="section-heading"><h2>Bağlantı durumu</h2><button className="text-button" onClick={()=>setTab('settings')}>Ayarlar →</button></div><div className="integration-grid">{[['Supabase','Veritabanı & oturum',!demo],['Ödeme','Sağlayıcı bağlantısı',data.features?.payments_enabled],['Kurye','DaaS bağlantısı',data.features?.daas_enabled],['SMS / İYS','İzinli iletişim',data.features?.sms_enabled]].map(([name,desc,ok])=><div key={String(name)}><strong>{name}</strong><p>{desc}</p><span className={'tag '+(ok?'green':'gray')}>{ok?'Bağlı':'Etkin değil'}</span></div>)}</div></Card></>}
 {tab==='tables'&&<><Card><div className="section-heading"><h2>Masa planı</h2><span className="tag">{tables.length} masa</span></div><form className="inline-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('create-table',{code:f.get('code'),name:f.get('name')});}}><label>Masa kodu<input name="code" placeholder="masa-14" pattern="[a-z0-9_-]{1,32}" required/></label><label>Masa adı<input name="name" placeholder="Masa 14" maxLength={100} required/></label><button className="btn primary" disabled={busy}>Masa ekle</button></form></Card><div className="table-grid">{tables.map((t:any)=><Card key={t.id} className="table-card"><div className="table-symbol">▦</div><h2>{t.name}</h2><span className={'tag '+(t.status==='empty'?'gray':t.status==='checkout'?'amber':'green')}>{label(t.status)}</span><div className="table-actions"><button disabled={busy||t.status==='checkout'} className="btn primary" onClick={()=>void openTable(t)}>{t.checkId?'Ziyaret QR’sini oluştur':'Adisyonu aç'}</button>{t.checkId&&<><button className="btn" onClick={()=>setTab('orders')}>Siparişleri gör</button>{(demo||data.features?.payments_enabled)&&<button className="text-button" onClick={()=>void openCheckout(t)}>Adisyonu böl →</button>}</>}</div>{!demo&&<><PermanentTableQR table={t}/></>} {!demo&&t.checkId&&<button className="text-button" disabled={busy} onClick={async()=>{if(!confirm(t.name+' için boş adisyon kapatılsın mı? Gönderilmemiş seçim, aktif sipariş veya borç varsa kapanmaz. İptal kayıtları silinmez.'))return;setBusy(true);try{await api('/api/merchant/close-empty',{checkId:t.checkId});await reload();}catch(e){setError(explain(e));}finally{setBusy(false);}}}>Boş adisyonu kapat</button>}</Card>)}</div>{!tables.length&&<Card><Empty title="İlk masanızı ekleyin" description="Önce gerçek masa numarasını ekleyin. Masa kartından QR göster ile kalıcı QR’yi ekrana getirin veya yazdırın; müşteri QR’yi okuttuğunda adisyon açılır; gelen siparişi kabul edin."/></Card>}{join&&<TableInvitation key={join} url={join} tableName={joinName} expiresAt={joinExpiry}/>} </>}
 {tab==='kitchen'&&<KitchenBoard orders={orders} role={data.role} busy={busy} action={action}/>}
 {tab==='orders'&&<Card><h2>Sipariş geçmişi</h2>{orders.length?<div className="responsive-table"><table><thead><tr><th>Masa / Kanal</th><th>Ürünler</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{orders.map((o:any)=><tr key={o.id}><td><b>{o.table}</b><small>#{o.id.slice(-8)}</small></td><td>{o.lines.map((l:any)=>`${l.quantity} × ${l.name}`).join(', ')}</td><td><span className="tag">{label(o.status)}</span></td><td>{o.status==='submitted'&&['owner','manager','waiter','kitchen'].includes(data.role)&&<><button className="btn primary" disabled={busy} onClick={()=>void action('order-status',{orderId:o.id,status:'accepted'})}>Kabul et</button><RejectOrder busy={busy} reject={note=>action('reject-order',{orderId:o.id,note})}/></>}{o.status==='served'&&['owner','manager','waiter'].includes(data.role)&&<button className="btn" onClick={()=>void action('order-status',{orderId:o.id,status:'completed'})}>Tamamla</button>}</td></tr>)}</tbody></table></div>:<Empty title="Sipariş kaydı yok" description="Son yedi gündeki siparişler burada listelenir."/>}</Card>}
 {tab==='checkout'&&<Counter tables={tables} receipts={data.receipts??[]} reload={reload} demo={demo}/>}
 {tab==='checkout'&&(demo||data.features?.payments_enabled)&&<><Card><h2>Hesabı böl</h2><p>Kişi payları, siparişe dönüşen birim borçlarından hesaplanır. Bahşiş ayrıca gösterilir.</p>{!demo&&!plan?<><label>Açık adisyon<select defaultValue="" onChange={e=>{const t=tables.find((t:any)=>t.checkId===e.target.value);if(t)void openCheckout(t);}}><option value="" disabled>Adisyon seçin</option>{tables.filter((t:any)=>t.checkId).map((t:any)=><option key={t.id} value={t.checkId}>{t.name}</option>)}</select></label>{!tables.some((t:any)=>t.checkId)&&<Empty title="Ödenecek adisyon yok" description="Masa siparişleri gönderildiğinde ödeme payları hazırlanabilir."/>}</>:demo?<><div className="notice">Hesaplama demosu · Gerçek ödeme oluşturmaz.</div><div className="inline-form"><label>Toplam (kuruş)<input value={demoBase} onChange={e=>/^[0-9]{0,8}$/.test(e.target.value)&&setDemoBase(e.target.value)}/></label><label>Kişi sayısı<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>Bahşiş<select value={tip} onChange={e=>setTip(Number(e.target.value))}>{[0,500,1000,1500].map(n=><option key={n} value={n}>%{n/100}</option>)}</select></label></div><div className="share-grid">{splitEqual(BigInt(demoBase||0),count).map((n,i)=><div className="share-card" key={i}><span>Kişi {i+1}</span><h3>{money(n)}</h3><p>Bahşiş {money(tipFor(n,tip))}</p><strong>Toplam {money(n+tipFor(n,tip))}</strong></div>)}</div></>:<CheckoutPlan plan={plan} busy={busy} onSplit={async mode=>{try{setBusy(true);const assignments=Object.fromEntries((plan.charges??[]).map((c:any)=>[c.id,(document.getElementById('assign-'+c.id) as HTMLSelectElement)?.value]));const p=await api('/api/ops/split',{checkId:plan.checkId,operationId:crypto.randomUUID(),expectedRevision:plan.revision,mode,payers:plan.members.map((m:any)=>m.id),assignments:mode==='items'?assignments:{}});setPlan(p);}catch(e){setError(explain(e));}finally{setBusy(false);}}}/>}</Card><Card><h2>Ödeme bağlantısı</h2><p>PayTR / diğer PSP bağlantısı etkinleştirilmedi. Bu ekrandan kart bilgisi toplanmaz ve tahsilat yapılmaz.</p><span className="tag amber">Sağlayıcı hesabı ve callback doğrulaması bekleniyor</span></Card></>}
 {tab==='courier'&&<><div className="stats two"><Metric title="Teslimat işi" value={String(data.deliveries.length)} note="Kendi kurye veya DaaS" icon="↗"/><Metric title="Belirsiz sonuç" value={String(data.deliveries.filter((d:any)=>d.dispatchState==='unknown').length)} note="Yeniden çağırmadan önce mutabakat" icon="◷"/></div><Card><div className="section-heading"><h2>Teslimatlar</h2><span className="tag gray">DaaS bağlantısı bekleniyor</span></div>{data.deliveries.length?data.deliveries.map((d:any)=><div key={d.id} className="list-row"><div><strong>#{d.orderId.slice(-8)}</strong><small>{label(d.routing)}</small></div><span className="tag">{label(d.status)}</span><span>{label(d.dispatchState)}</span></div>):<Empty title="Henüz teslimat yok" description="Hazırlanmaya başlayan, teslimat izni doğrulanmış paket siparişleri Outbox üzerinden buraya gelir."/>}</Card></>}
 {tab==='loyalty'&&<><div className="columns"><Card className="blue-card"><p className="eyebrow">ADİL KAZANIM</p><h2>Her müşteri<br/>kendi payından kazanır.</h2><p>100 puan = 1 TL. Bahşiş ve teslimat bedeli puanlandırılmaz.</p><span className="tag">Ödeme kanıtı bağlantısı bekleniyor</span></Card><Card><h2>Puan defteri</h2><div className="journey"><span>Kazanım</span><span>Rezervasyon</span><span>Harcama / İade</span></div><p>Kullanılabilir ve rezerve puanlar ayrı izlenir. Geçmiş hareketler silinmez.</p></Card></div><Card><h2>Müşteri cüzdanları</h2>{data.loyalty.length?data.loyalty.map((l:any)=><div className="list-row" key={l.id}><strong>{l.phone}</strong><span>{l.available} kullanılabilir</span><span>{l.held} rezerve</span></div>):<Empty title="Puan hesabı yok" description="Doğrulanmış ödemelere ait puan hareketleri tamamlandıktan sonra müşteri cüzdanları burada görünür."/>}</Card></>}
 {tab==='crm'&&<><div className="stats"><Metric title="Müşteri" value={String(data.customers.length)} note="Şubeye kayıtlı hesaplar" icon="◎"/><Metric title="SMS izinli" value={String(data.customers.filter((c:any)=>c.consent==='granted').length)} note="İYS ayrıca doğrulanır" icon="✓"/><Metric title="Aday kuyruğu" value={String(data.outbox.length)} note="Deneme / canlı ayrı" icon="≡"/><Metric title="Gönderilen SMS" value={String(data.outbox.filter((q:any)=>['accepted','delivered'].includes(q.state)).length)} note="Sağlayıcı onaylı" icon="↗"/></div><div className="columns"><Card><h2>21 Gün Geri Kazanım</h2><p>Son tamamlanmış ve ödenmiş sipariş → bekleme süresi → güncel izin → tekil gönderim.</p>{data.campaigns.map((c:any)=><form key={c.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('save-campaign',{id:c.id,days:Number(f.get('days')),template:String(f.get('template'))});}}><div className="section-heading"><h3>{c.name}</h3><span className="tag amber">{label(c.mode)}</span></div><label>Siparişsiz geçen gün<input name="days" type="number" min={7} max={365} defaultValue={c.days}/></label><label>SMS taslağı<textarea name="template" defaultValue={c.template} maxLength={1000} rows={4}/></label><p className="helper">Marka, bağlantı ve ileti tercihi alanları gönderim öncesi doldurulur. Kayıt işlemi SMS göndermez.</p><button className="btn primary" disabled={busy}>Taslağı kaydet</button></form>)}</Card><Card><h2>Gönderim güvenlik kapıları</h2><div className="gate-list">{['Doğrulanmış telefon','Ayrı SMS pazarlama izni','İşletmeye ait güncel İYS onayı','Yeni sipariş / ret kontrolü','Gönderim saatleri ve sıklık sınırı','Kalıcı işlem kimliği ve Outbox'].map(t=><div key={t}><span>✓</span>{t}</div>)}</div><div className="notice">Gönderim kapalı. Cron yalnızca uygun adayları değerlendirir; izin veya sağlayıcı bilgisi eksik müşteriye mesaj göndermez.</div>{data.lastCrmRun&&<p className="helper">Son değerlendirme: {new Date(data.lastCrmRun.finished_at??data.lastCrmRun.started_at).toLocaleString('tr-TR')}</p>}</Card></div><Card><h2>Müşteriler</h2>{data.customers.length?data.customers.map((c:any)=><div className="list-row" key={c.id}><strong>{c.phone}</strong><span className="tag">{label(c.consent)}</span><small>{c.lastOrder?new Date(c.lastOrder).toLocaleDateString('tr-TR'):'Tamamlanmış sipariş yok'}</small></div>):<Empty title="Henüz müşteri kaydı yok" description="Müşteri bilgileri ve izinler güvenli kayıt akışıyla toplandığında burada listelenir."/>}</Card><Card><h2>Gönderim kuyruğu</h2>{data.outbox.length?data.outbox.map((q:any)=><div className="list-row" key={q.id}><span>#{q.id.slice(-8)}</span><span className="tag">{label(q.state)}</span><small>{q.reason||'Değerlendirildi'}</small></div>):<Empty title="Kuyruk boş" description="İzinli ve uygun müşteriler için tekrar etmeyen kayıtlar oluşturulur."/>}</Card></>}
 {tab==='upsell'&&<Card><h2>Tamamlayıcı ürün kuralları</h2><p>LLM yok. Onaylı fiyat, stok uygunluğu ve işletmenin tanımladığı skorlarla en fazla iki öneri.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action('save-rule',Object.fromEntries(f.entries()));}}><div className="inline-form"><label>Sepetteki ürün<select name="target" required>{data.catalogue.items.map((p:any)=><option key={p.id} value={p.sourceId}>{p.name}</option>)}</select></label><label>Önerilecek ürün<select name="recommended" required defaultValue="TIR-018">{data.catalogue.items.map((p:any)=><option key={p.id} value={p.sourceId}>{p.name}</option>)}</select></label></div><div className="inline-form">{[['confidenceBps','Birlikte alım güveni'],['marginBps','Marj skoru'],['weightBps','Kural ağırlığı']].map(([n,t])=><label key={n}>{t} (0–10000)<input name={n} type="number" min={0} max={10000} defaultValue={n==='weightBps'?10000:5000} required/></label>)}</div><button disabled={busy} className="btn primary">Kuralı kaydet</button></form><div className="list">{data.rules.map((r:any)=><div className="list-row" key={r.id}><strong>{r.target}</strong><span>→</span><strong>{r.recommendation}</strong><span className="tag green">{r.active?'Etkin':'Pasif'}</span></div>)}</div></Card>}
 {tab==='settings'&&manager&&<PilotSettings settings={data.orderingSettings} reload={reload} demo={demo}/>}
 {tab==='settings'&&<><Card><h2>İşletme ve modüller</h2><p>Meşhur Sarıyer Börekçisi Sandviç · Bahçeşehir</p><div className="gate-list">{[['Sipariş',data.catalogue.orderingEnabled],['Ödeme',data.features?.payments_enabled],['Sadakat kullanımı',data.features?.loyalty_enabled],['DaaS',data.features?.daas_enabled],['SMS gönderimi',data.features?.sms_enabled]].map(([n,on])=><div key={String(n)}><strong>{n}</strong><span className={'tag '+(on?'green':'gray')}>{on?'Açık':'Kapalı'}</span></div>)}</div><p className="helper">Gerçek fiyat onayı, işletme yetkilendirmesi ve sağlayıcı kabul testleri tamamlanmadan modüller canlı satışa açılmaz.</p></Card><Card><h2>Güvenli pilot</h2><p>Müşteri menüsü korunur. Finansal işlemler kuruş tabanlıdır. Kurye ve SMS işleri veritabanı kuyruğunda izlenir. Doğrulanmış gönderim/ödeme sonucu olmadan başarılı işlem gösterilmez.</p></Card></>}
 </>}</main></div></div>;
}
function Metric({title,value,note,icon}:{title:string;value:string;note:string;icon:string}){return <Card className="metric"><div><span>{title}</span><b className="metric-icon">{icon}</b></div><strong>{value}</strong><small>{note}</small></Card>;}
function CheckoutPlan({plan,busy,onSplit}:{plan:any;busy:boolean;onSplit:(m:'equal'|'items')=>Promise<void>}){const[mode,setMode]=useState<'equal'|'items'>('equal');return <div><div className="total-band"><span>Adisyon</span><strong>{money(plan.totalMinor)}</strong></div>{!plan.shares.length?<><div className="segmented"><button className={mode==='equal'?'active':''} onClick={()=>setMode('equal')}>Eşit böl</button><button className={mode==='items'?'active':''} onClick={()=>setMode('items')}>Ürün bazlı</button></div><p>{plan.members.length} masa katılımcısı</p>{mode==='items'&&plan.charges.map((c:any)=><label key={c.id} className="allocation-row">{c.name} · {money(c.amountMinor)}<select id={'assign-'+c.id}>{plan.members.map((m:any,i:number)=><option key={m.id} value={m.id}>{m.isMe?'Ben':`Kişi ${i+1}`}</option>)}</select></label>)}<button disabled={busy||!plan.members.length||!plan.charges.length} className="btn primary" onClick={()=>void onSplit(mode)}>Bölüşümü kesinleştir</button></>:<div className="share-grid">{plan.shares.map((s:any,i:number)=><div className="share-card" key={s.id}><span>{s.isMine?'Benim payım':`Kişi ${i+1}`}</span><h3>{money(s.baseMinor)}</h3><small>{label(s.paymentStatus)}</small></div>)}</div>}</div>;}

function RejectOrder({busy,reject}:{busy:boolean;reject:(note:string)=>Promise<void>}){
 const[open,setOpen]=useState(false),[note,setNote]=useState('');
 return open?<form className="order-reject-form" onSubmit={e=>{e.preventDefault();if(note.trim())void reject(note.trim()).then(()=>setOpen(false));}}><label>Reddetme gerekçesi<input autoFocus required maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="Örn. ürün tükendi"/></label><button className="btn" type="button" onClick={()=>setOpen(false)}>Vazgeç</button><button className="btn" disabled={busy||!note.trim()}>Reddet ve kaydet</button></form>:<button className="btn full" type="button" disabled={busy} onClick={()=>setOpen(true)}>Siparişi reddet</button>;
}
