'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
import {useSharedCart} from '@/hooks/useSharedCart';import type {Scope} from '@/src/cart-protocol';
import {catTitle} from '@/lib/public-format';import {CustomerOrders} from './CustomerOrders';
import {PageHeader,Card,Empty} from './Shell';import {api,explain,money,label} from './transport';
export function Customer(){const[scope,setScope]=useState<Scope|null>(null);const[cat,setCat]=useState<any>(null);const[check,setCheck]=useState('');const[message,setMessage]=useState('');const[needLogin,setNeedLogin]=useState(false);
 useEffect(()=>{let alive=true;void(async()=>{try{if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});const u=new URL(location.href);const id=u.searchParams.get('check')??'';const token=u.searchParams.get('token');setCheck(id);if(token&&/^[0-9a-f]{64}$/.test(token)){sessionStorage.setItem('menugo:join:'+id,token);u.searchParams.delete('token');history.replaceState(null,'',u.pathname+u.search);}const catalogue=await api('/api/catalogue');if(alive)setCat(catalogue);if(!id)return;const session=await api('/api/session');const pending=sessionStorage.getItem('menugo:join:'+id);if(pending){await api('/api/ops/join',{checkId:id,token:pending});sessionStorage.removeItem('menugo:join:'+id);}if(alive)setScope({...session,checkId:id,userId:session.userId});}catch(e){if(alive){setMessage(explain(e));setNeedLogin(e instanceof Error&&e.message==='UNAUTHENTICATED');}}})();return()=>{alive=false;};},[]);
 return <><header className="table-brand"><Link href="/bahcesehir"><img src="/media/sariyer-brand-transparent-r8.webp" alt="Meşhur Sarıyer Börekçisi Sandviç" width="600" height="200"/></Link><Link href="/hesabim">Hesabım ↗</Link></header><main className="customer"><div className="customer-heading"><img src="/media/sariyer-brand-transparent-r8.webp" alt="Meşhur Sarıyer Börekçisi Sandviç"/><div><p className="eyebrow">BAHÇEŞEHİR</p><h1>Masam & Sipariş</h1><p>Birlikte seçin, hesabınızı kolayca paylaşın.</p></div></div>{message&&<div className="notice" role="status">{message}{needLogin&&<Link className="btn primary" href={'/giris?next='+encodeURIComponent('/siparis?check='+check)}>Oturum aç</Link>}</div>}{scope&&cat?<Live scope={scope} catalogue={cat}/>:<><Card><Empty title={check?'Masa katılımı':'Masanızın QR kodunu okutun'} description={check?'Ortak sepete erişmek için hesabınız ve masa katılımınız doğrulanır.':'Siparişe açık masanızın katılım bağlantısını personelimizden alabilirsiniz.'}/><div className="center"><Link className="btn primary" href="/bahcesehir">Menüyü incele</Link><Link className="btn" href="/giris">Hesabıma giriş yap</Link></div></Card>{cat&&<div className="customer-product-grid">{cat.items.slice(0,12).map((p:any)=><Card key={p.id}><p className="eyebrow">{catTitle(p.category)}</p><h3>{p.name}</h3><p>{p.description}</p><strong>{money(p.priceMinor)}</strong></Card>)}</div>}</>}</main></>;
}
function Live({scope,catalogue}:{scope:Scope;catalogue:any}){const live=useSharedCart(scope);const[choices,setChoices]=useState<Record<string,string>>({});const[tab,setTab]=useState<'menu'|'cart'|'bill'|'wallet'>('menu');const[category,setCategory]=useState('all');const[search,setSearch]=useState('');const[recs,setRecs]=useState<any[]>([]);const[bill,setBill]=useState<any>(null);const[wallet,setWallet]=useState<any>(null);const[tip,setTip]=useState(0);const[quote,setQuote]=useState<any>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[points,setPoints]=useState('');const[orderPending,setOrderPending]=useState<{operationId:string;revision:string}|null>(null);
 useEffect(()=>{try{const raw=sessionStorage.getItem('menugo:order:'+scope.checkId);if(raw)setOrderPending(JSON.parse(raw));}catch{}},[scope.checkId]);
 useEffect(()=>{let alive=true;if(live.cart)void api('/api/ops/recommendations?check='+scope.checkId).then(v=>{if(alive)setRecs(v);}).catch(()=>{if(alive)setRecs([]);});return()=>{alive=false;};},[live.cart?.revision,scope.checkId]);
 useEffect(()=>{let alive=true;if(tab==='bill')void api('/api/ops/checkout?check='+scope.checkId).then(v=>{if(alive)setBill(v);}).catch(e=>setMessage(explain(e)));if(tab==='wallet')void api('/api/ops/wallet').then(v=>{if(alive)setWallet(v);}).catch(e=>setMessage(explain(e)));return()=>{alive=false;};},[tab,live.cart?.revision,scope.checkId]);
 useEffect(()=>{let alive=true;setQuote(null);const s=bill?.shares?.find((s:any)=>s.isMine);if(s)void api('/api/ops/payment-quote?check='+scope.checkId+'&share='+s.id+'&tip='+tip).then(v=>{if(alive)setQuote(v);}).catch(e=>setMessage(explain(e)));return()=>{alive=false;};},[bill,tip,scope.checkId]);
 async function change(id:string,delta:number,option?:string){setMessage('');const result=await live.mutateCart(id,delta,option);if(result.kind==='conflict')setMessage('Masa güncellendi. Güncel sepeti kontrol edip tekrar deneyin.');else if(result.kind==='unknown')setMessage('İşlemin sonucu doğrulanıyor. Yeni ürün eklemeden önce aynı işlemi kontrol edin.');else if(result.kind==='rejected')setMessage('Bu değişiklik şu anda uygulanamıyor.');}
 async function send(){if(!live.cart)return;setBusy(true);setMessage('');const cmd=orderPending??{operationId:crypto.randomUUID(),revision:live.cart.revision.toString()};try{sessionStorage.setItem('menugo:order:'+scope.checkId,JSON.stringify(cmd));setOrderPending(cmd);const r=await fetch('/api/checks/'+scope.checkId+'/order',{method:'POST',credentials:'same-origin',headers:{'Idempotency-Key':cmd.operationId,'If-Match':'"'+cmd.revision+'"'},signal:AbortSignal.timeout(15000)});const value=await r.json();if(!r.ok){if(r.status===409&&['REVISION_CONFLICT','CART_EMPTY','PRICE_CHANGED','PRODUCT_NOT_ORDERABLE','ORDERING_DISABLED','CHECK_NOT_OPEN'].includes(value.error?.code)){sessionStorage.removeItem('menugo:order:'+scope.checkId);setOrderPending(null);}throw new Error(value.error?.code??'UNKNOWN');}sessionStorage.removeItem('menugo:order:'+scope.checkId);setOrderPending(null);await live.refresh();setMessage('Siparişiniz kaydedildi.');setTab('bill');}catch(e){setMessage(explain(e));await live.refresh();}finally{setBusy(false);}}
 const cats=[...new Set(catalogue.items.map((p:any)=>p.category))] as string[];
 return <><div className="live-status"><span className={'dot '+(live.connection==='subscribed'?'connected':'')}/><span>{!live.online?'Bağlantı kesildi':live.stale?'Masa güncelleniyor…':live.connection==='subscribed'?'Masanızla senkronize':'Masa bağlantısı'}</span><button className="text-button" onClick={()=>void live.refresh()}>↻ Yenile</button></div>{live.accessDenied&&<div className="alert">Masa erişimi sona erdi. Personelimizden yeni katılım bağlantısı isteyin.</div>}{message&&<div role="status" className="notice">{message}</div>}{live.pending&&<div className="notice">Son işlemin sonucu henüz doğrulanmadı.<button className="btn" disabled={live.mutation==='sending'||!live.online} onClick={()=>void live.retryPending()}>Aynı işlemi kontrol et</button></div>}
 <CustomerOrders checkId={scope.checkId} refreshKey={String(live.cart?.revision??'')}/><nav className="customer-tabs">{([['menu','Menü'],['cart','Ortak sepet'],['bill','Hesabım'],['wallet','Puanlarım']] as const).filter(([id])=>id!=='wallet').map(([id,title])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{title}</button>)}</nav>
 {tab==='menu'&&<><div className="search-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ürün ara…" aria-label="Ürün ara"/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Kategori"><option value="all">Tüm menü</option>{cats.map(c=><option key={c} value={c}>{catTitle(c)}</option>)}</select></div><div className="customer-product-grid">{catalogue.items.filter((p:any)=>(category==='all'||p.category===category)&&p.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).map((p:any)=><Card key={p.id}><p className="eyebrow">{catTitle(p.category)}</p><h3>{p.name}</h3>{p.description&&<p>{p.description}</p>}<>{p.options?.length>0&&<label>Seçeneğiniz<select aria-label={p.name+' seçeneği'} value={choices[p.id]??''} onChange={e=>setChoices(v=>({...v,[p.id]:e.target.value}))}><option value="">Lütfen seçin</option>{p.options.map((o:string)=><option key={o}>{o}</option>)}</select></label>}</><div className="section-heading"><strong>{money(p.priceMinor)}</strong><button className="btn primary" disabled={!live.canMutate||!p.canOrder||(p.options?.length>0&&!choices[p.id])||!!orderPending} onClick={()=>void change(p.id,1,choices[p.id]||undefined)}>{p.canOrder?'＋ Ekle':'Siparişe kapalı'}</button></div></Card>)}</div></>}
 {tab==='cart'&&<Card><h2>Ortak sepet</h2><p>Bu masanın güncel seçimi. Gönderildiğinde listedeki tüm ürünler mutfak sırasına alınır.</p>{!live.cart?.lines.length?<Empty title="Sepetiniz boş" description="Menüden ürün seçerek başlayın."/>:live.cart.lines.map(l=><div className="cart-row" key={l.cartLineId}><div><h3>{l.productName}</h3><span>{money(l.lineTotalMinor)}</span></div><div className="quantity"><button aria-label={l.productName+' azalt'} disabled={!live.canMutate||!!orderPending} onClick={()=>void change(l.productId,-1,l.option)}>−</button><b>{l.quantity}</b><button aria-label={l.productName+' artır'} disabled={!live.canMutate||!!orderPending} onClick={()=>void change(l.productId,1,l.option)}>＋</button></div></div>)}<div className="total-band"><span>Sepet toplamı</span><strong>{money(live.cart?.totalMinor)}</strong></div>{recs.length>0&&<div className="upsell"><h3>Yanına ne iyi gider?</h3>{recs.map(r=><button className="upsell-item" key={r.productId} disabled={!live.canMutate||!!orderPending} onClick={()=>void change(r.productId,1)}><span>{r.productName}</span><strong>{money(r.priceMinor)} ＋</strong></button>)}</div>}<button className="btn primary full" disabled={busy||!live.online||live.stale||(!orderPending&&(!live.cart?.canMutate||!live.cart?.lines.length))} onClick={()=>void send()}>{busy?'Gönderiliyor…':orderPending?'Önceki siparişi doğrula':'Ortak sepeti siparişe gönder'}</button></Card>}
 {tab==='bill'&&<><Card><h2>Hesabım</h2>{!bill?<p>Adisyon yükleniyor…</p>:<><div className="total-band"><span>Masa adisyonu</span><strong>{money(bill.totalMinor)}</strong></div>{bill.charges.map((c:any)=><div className="list-row" key={c.id}><span>{c.name}</span><strong>{money(c.amountMinor)}</strong></div>)}{!bill.charges.length&&<Empty title="Henüz sipariş yok" description="Gönderdiğiniz siparişin ürünleri ve kişi payları burada görünür."/>}{bill.shares.length?<div className="share-grid">{bill.shares.map((s:any,i:number)=><div className="share-card" key={s.id}><span>{s.isMine?'Benim payım':`Kişi ${i+1}`}</span><h3>{money(s.baseMinor)}</h3><small>{label(s.paymentStatus)}</small></div>)}</div>:bill.charges.length>0?<p className="notice">Hesabı eşit veya ürün bazlı bölmek için personelimizden yardım alabilirsiniz.</p>:null}</>}</Card>{bill?.shares.some((s:any)=>s.isMine)&&<Card><h2>Gönüllü bahşiş</h2><div className="segmented">{[0,500,1000,1500].map(n=><button key={n} className={tip===n?'active':''} onClick={()=>setTip(n)}>{n===0?'Bahşiş yok':'%'+n/100}</button>)}</div>{quote&&<><div className="list-row"><span>Benim payım</span><strong>{money(quote.baseMinor)}</strong></div><div className="list-row"><span>Bahşiş</span><strong>{money(quote.tipMinor)}</strong></div><div className="total-band"><span>Toplam</span><strong>{money(quote.amountMinor)}</strong></div></>}<button disabled className="btn primary full">Çevrim içi ödeme henüz açık değil</button><p className="helper">Ödemeniz için personelimizle görüşebilirsiniz. Bu ekran kart bilgisi toplamaz.</p></Card>}</>}
 {tab==='wallet'&&<Card><p className="eyebrow">MENÜGO SADAKAT</p><h2>Puanlarım</h2><div className="wallet-number">{wallet?.available??'—'} <span>puan</span></div><p>100 puan = 1 TL · Yalnızca kendi ödediğiniz net gıda tutarından kazanılır.</p>{wallet?.enabled?<><label>Kullanmak istediğiniz puan<input inputMode="numeric" value={points} onChange={e=>/^[0-9]*$/.test(e.target.value)&&setPoints(e.target.value)}/></label><button className="btn" disabled onClick={()=>{}}>Ödeme bağlantısı bekleniyor</button></>:<div className="notice">Bu şubede puan kullanımı henüz açık değil.</div>}{wallet?.history.map((h:any,i:number)=><div className="list-row" key={i}><span>{h.kind}</span><strong>{h.points} puan</strong></div>)}</Card>}
 <div className="cart-dock"><div><small>Ortak sepet</small><strong>{live.cart?money(live.cart.totalMinor):'Bağlanıyor…'}</strong></div><button className="btn primary" onClick={()=>setTab('cart')}>Sepeti aç →</button></div></>;
}
