'use client';
import MenuGoLogo from '@/components/MenuGoLogo';
import {GuestWelcomeExperience,MenuSelectionVisual} from './GuestWelcomeExperience';
import {useEffect,useState,useRef} from 'react';import Link from 'next/link';
import {TableScanner} from './TableScanner';
import {ServiceAvailability,VisitFeedback} from './ServiceExperience';
import {ProductInformationView} from './ProductInformation';
import {VoiceOrderDraft} from './VoiceOrderDraft';
import {useGuestCart} from '@/hooks/useGuestCart';import type {Scope} from '@/src/cart-protocol';
import {api,explain,money,label} from './transport';import {CATEGORIES,catTitle} from '@/lib/public-format';
// Serialize bootstrap across React StrictMode mounts. Never persists a write token in JS.
let bootstrap:{id:string,promise:Promise<any>}|null=null;
function openVisit(id:string,token:string|null){if(bootstrap?.id===id)return bootstrap.promise;
 const promise=(async()=>{try{return await api('/api/guest/'+id+'/cart');}catch(e){if(!token)throw e;return api('/api/guest/'+id+'/join',{token});}})();bootstrap={id,promise};void promise.finally(()=>{if(bootstrap?.promise===promise)bootstrap=null;}).catch(()=>{});return promise;}
export function GuestTable(){const[session,setSession]=useState<any>(null),[catalogue,setCatalogue]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);const joinMemory=useRef<string|null>(null);
 useEffect(()=>{let alive=true;setError('');setLoading(true);void(async()=>{try{
 const u=new URL(location.href);const id=u.searchParams.get('check');const token=u.searchParams.get('token');
 if(token&&id&&/^[0-9a-f]{64}$/.test(token)){joinMemory.current=token;try{sessionStorage.setItem('menugo:join:'+id,token);}catch{}u.searchParams.delete('token');history.replaceState(null,'',u.pathname+u.search);}
 const [cat,info]=await Promise.all([api('/api/catalogue'),api('/api/merchant/product-information').catch(()=>[])]);cat.information=info;if(alive)setCatalogue(cat);
 if(!id){const visits=await api('/api/guest/visits');const active=visits.find((v:any)=>['open','checkout'].includes(v.status));if(active){location.replace('/siparis?check='+active.checkId);return;}return;}
 if(!/^[0-9a-f-]{36}$/.test(id))throw Error('INVALID_TABLE_INVITATION');
 let joinToken=joinMemory.current;try{joinToken=joinToken??sessionStorage.getItem('menugo:join:'+id);}catch{}const data=await openVisit(id,joinToken);joinMemory.current=null;try{sessionStorage.removeItem('menugo:join:'+id);}catch{}
 if(alive)setSession(data);
 }catch(e){if(alive)setError(explain(e));}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[retry]);
 return <div className="guest-site"><header className="guest-header"><Link href="/bahcesehir"><img src="/media/sariyer-brand-transparent-r8.webp" width="600" height="200" alt="Meşhur Sarıyer Börekçisi Sandviç"/></Link><Link href="/hesabim">Siparişlerim</Link></header>
 {session&&catalogue?<Dining scope={{businessId:session.businessId,branchId:session.branchId,checkId:session.checkId,userId:session.viewerUserId}} catalogue={catalogue}/>:<GuestWelcomeExperience><span className="guest-kicker">BAHÇEŞEHİR · ÜYELİKSİZ MENÜ</span><h1>{loading?'Masanız hazırlanıyor…':'Hoş geldiniz.'}</h1><p>{loading?'Masa bağlantınız güvenle doğrulanıyor.':'Masanızın QR kodunu kameranızla tarayın; ürünlerinizi seçip siparişinizi gönderin. Üyelik gerekmez.'}</p>{error&&<p role="alert" className="notice">{error}</p>}{error&&<button className="btn" onClick={()=>setRetry(v=>v+1)}>Yeniden dene</button>}{!loading&&<TableScanner/>}<div className="guest-welcome-actions"><Link className="btn" href="/bahcesehir">Menüyü incele</Link><a className="btn" href="tel:+905394830031">İşletmeyi ara</a></div><p className="helper">QR’yi göremiyorsanız garsonunuzdan “QR göster” ekranını açmasını isteyin. Kısa süreli ziyaret QR’siyle de katılabilirsiniz.</p></GuestWelcomeExperience>}
 <footer className="guest-footer"><a href="https://www.menugo.app/"><MenuGoLogo width="560" height="147" alt="menügo — Yeni Nesil Dijital Menü"/></a><Link href="/yardim">Yardım</Link><Link href="/giris?role=waiter">Personel girişi</Link></footer></div>;
}
function Dining({scope,catalogue}:{scope:Scope;catalogue:any}){
 const live=useGuestCart(scope);const[tab,setTab]=useState<'menu'|'cart'|'orders'|'bill'>('menu'),[category,setCategory]=useState(catalogue.items.some((x:any)=>x.category==='sandvic')?'sandvic':'all'),[search,setSearch]=useState(''),[choices,setChoices]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[orders,setOrders]=useState<any[]>([]),[reason,setReason]=useState(''),[cancelOrder,setCancelOrder]=useState<string|null>(null),[pendingOrder,setPendingOrder]=useState<{operationId:string;expectedRevision:string}|null>(null),[recommendations,setRecommendations]=useState<any[]>([]);
 useEffect(()=>{if(live.accessDenied){setOrders([]);setRecommendations([]);}},[live.accessDenied]);
 const submitting=useRef(false);const cart=live.cart;const key='menugo:guest-order:'+scope.checkId+':'+scope.userId;
 useEffect(()=>{try{const v=JSON.parse(sessionStorage.getItem(key)||'null');if(typeof v?.operationId==='string'&&/^[0-9a-f-]{36}$/i.test(v.operationId)&&typeof v?.expectedRevision==='string'&&/^(0|[1-9][0-9]{0,18})$/.test(v.expectedRevision))setPendingOrder({operationId:v.operationId,expectedRevision:v.expectedRevision});}catch{}},[key]);
 useEffect(()=>{if(live.accessDenied)return;let alive=true;const load=()=>api('/api/guest/'+scope.checkId+'/orders').then(v=>{if(alive)setOrders(v);}).catch(()=>{});void load();const timer=setInterval(()=>{if(navigator.onLine&&document.visibilityState==='visible')void load();},10000);return()=>{alive=false;clearInterval(timer);};},[scope.checkId,scope.userId,cart?.revision,live.accessDenied]);
 async function change(id:string,delta:number,option?:string){setNotice('');const result=await live.mutateCart(id,delta,option);if(result.kind==='conflict')setNotice('Masa güncellendi. Seçiminizi kontrol edip tekrar deneyin.');if(result.kind==='unknown')setNotice('Son işleminiz doğrulanıyor. Lütfen aynı işlemi kontrol edin.');if(result.kind==='rejected')setNotice('Ürün eklenemedi. Bağlantınızı ve ürün seçeneğini kontrol edin.');}
 async function applyVoiceLine(line:{productId:string;quantity:number;option:string|null}){setNotice('');const result=await live.mutateCart(line.productId,line.quantity,line.option??undefined);if(result.kind==='committed'){setNotice('Sesli taslaktaki ürün seçimlerinize eklendi. Sipariş henüz gönderilmedi.');return;}if(result.kind==='conflict'){setNotice('Masa güncellendi. Taslağı kontrol edip tekrar deneyin.');throw Error(result.code);}if(result.kind==='unknown'){setNotice('Son eklemenin sonucu henüz kesinleşmedi. Aynı işlemi tekrar göndermeyin.');throw Error('OPERATION_RESULT_UNKNOWN');}setNotice('Ürün eklenemedi. Bağlantınızı ve ürün seçeneğini kontrol edin.');throw Error(result.code);}
 async function send(){if(!cart||submitting.current)return;submitting.current=true;setBusy(true);const cmd=pendingOrder??{operationId:crypto.randomUUID(),expectedRevision:cart.revision.toString()};try{sessionStorage.setItem(key,JSON.stringify(cmd));setPendingOrder(cmd);await api('/api/guest/'+scope.checkId+'/order',cmd);sessionStorage.removeItem(key);setPendingOrder(null);setTab('orders');setNotice('Siparişiniz gönderildi. İşletme kabul ettiğinde durumunuz güncellenecek.');await live.refresh();}catch(e){if(e instanceof Error&&['REVISION_CONFLICT','PRICE_CHANGED','CART_EMPTY','PRODUCT_NOT_ORDERABLE','CHECK_NOT_OPEN','ORDERING_DISABLED','KITCHEN_CAPACITY_REACHED','ORDERING_PAUSED','ORDER_AWAITING_ACCEPTANCE','ORDER_LIMIT_EXCEEDED'].includes(e.message)){sessionStorage.removeItem(key);setPendingOrder(null);}setNotice(explain(e));await live.refresh();}finally{submitting.current=false;setBusy(false);}}
 async function service(kind:string){setBusy(true);try{await api('/api/guest/'+scope.checkId+'/service',{kind});setNotice(kind==='waiter'?'Garson talebiniz kaydedildi.':'Hesap talebiniz kaydedildi. Ödemenizi personelimizle tamamlayabilirsiniz.');}catch(e){setNotice(explain(e));}finally{setBusy(false);}}
 async function cancel(){if(!cancelOrder||!reason.trim())return;setBusy(true);try{await api('/api/guest/'+scope.checkId+'/cancel',{orderId:cancelOrder,reason});setNotice('İptal talebiniz iletildi. İşletme onayı olmadan siparişiniz iptal edilmez.');setCancelOrder(null);setOrders(await api('/api/guest/'+scope.checkId+'/orders'));}catch(e){setNotice(explain(e));}finally{setBusy(false);}}
 useEffect(()=>{let alive=true;if(cart&&!live.stale&&!live.accessDenied)void api('/api/guest/'+scope.checkId+'/recommendations').then(v=>{if(alive)setRecommendations(v);}).catch(()=>{});return()=>{alive=false;};},[cart?.revision,live.stale,scope.checkId,scope.userId,live.accessDenied]);
 const categories=CATEGORIES.filter(c=>catalogue.items.some((p:any)=>p.category===c.id));const mine=cart?.lines.filter(l=>l.isMine)??[];const open=cart&&['open','checkout'].includes(cart.status);
 return <main className="guest-main" data-cart-revision={cart?.revision.toString()??''}><div className="guest-context"><div><span className="guest-kicker">MASADA SİPARİŞ · ÜYELİK GEREKMEZ</span><h1>{cart?.tableName||'Masanız'} <small>{cart?'Misafir '+cart.seat:''}</small></h1></div><span className={'guest-sync '+(live.connection==='subscribed'?'connected':'')}>{!live.online?'Çevrimdışı':live.stale?'Güncelleniyor…':live.connection==='subscribed'?'Canlı bağlantı':'Güncel sepet'}</span></div>
 <ServiceAvailability/>{!live.online&&<div className="notice" role="status">İnternet bağlantısı kesildi. Son bilgiler gösteriliyor; yeni sipariş gönderilmez. Personelimizden yardım alabilirsiniz.</div>}
 {live.accessDenied&&<div className="alert">Masa erişiminiz sona erdi. Personelimizden yeni katılım bağlantısı isteyin.</div>}
 {cart&&!open&&<div className="notice">Bu adisyon kapandı. Yeni ziyaretiniz için masanın güncel QR kodunu okutun.</div>}
 {notice&&<p className="notice" role="status">{notice}</p>}{live.pending&&<div className="notice">Son ekleme/çıkarma işleminin sonucu henüz kesinleşmedi.<button className="btn" disabled={!live.online||live.mutation==='sending'} onClick={()=>void live.retryPending()}>Aynı işlemi kontrol et</button></div>}
 <nav className="guest-tabs" aria-label="Masa menüsü">{([['menu','Menü'],['cart','Benim seçimlerim'],['orders','Siparişlerim'],['bill','Hesap']] as const).map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
 <div className="guest-assist"><button disabled={!open||busy||!live.online} onClick={()=>void service('waiter')}>♧ Garson çağır</button><button disabled={!open||busy||!live.online} onClick={()=>void service('bill')}>▤ Hesap iste</button></div>
 {tab==='menu'&&<><VoiceOrderDraft checkId={scope.checkId} disabled={!open||busy||!live.online||live.stale||!live.canMutate||!!pendingOrder} onApply={applyVoiceLine}/><label className="guest-search"><span>⌕</span><input aria-label="Ürün ara" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Canınız ne çekiyor?"/></label><div className="guest-categories"><button onClick={()=>setCategory('all')} aria-pressed={category==='all'}>Tümü</button>{categories.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} aria-pressed={category===c.id}>{c.symbol} {c.title}</button>)}</div><div className="guest-products">{catalogue.items.filter((p:any)=>(category==='all'||p.category===category)&&p.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).map((p:any)=><article className="guest-product" key={p.id}><MenuSelectionVisual item={p}/><small>{catTitle(p.category)}{p.quantityLabel?' · '+p.quantityLabel:''}</small><h2>{p.name}</h2>{p.description&&<p>{p.description}</p>}{catalogue.information?.some((i:any)=>i.productId===p.id)&&<details className="guest-product-info"><summary>İçerik ve alerjenler</summary><ProductInformationView value={catalogue.information.find((i:any)=>i.productId===p.id)}/></details>}{p.options?.length>0&&<select aria-label={p.name+' seçeneği'} value={choices[p.id]??''} onChange={e=>setChoices(v=>({...v,[p.id]:e.target.value}))}><option value="">Seçeneğinizi belirleyin</option>{p.options.map((o:string)=><option key={o}>{o}</option>)}</select>}<div><strong>{money(p.priceMinor)}</strong><button aria-label={p.name+' ekle'} disabled={!live.canMutate||!p.canOrder||!!pendingOrder||(p.options?.length>0&&!choices[p.id])} onClick={()=>void change(p.id,1,choices[p.id]||undefined)}>{p.canOrder?'＋ Ekle':'Mevcut değil'}</button></div></article>)}</div><p className="helper">Alerjiniz varsa siparişten önce personelimize danışın.</p></>}
 {tab==='cart'&&<section className="guest-card"><h2>Benim seçimlerim</h2><p>Yalnızca sizin seçtikleriniz gönderilir. Masadaki diğer misafirler kendi seçimlerini yönetir.</p>{mine.length?mine.map(l=><div className="guest-line" key={l.cartLineId}><div><strong>{l.productName}</strong><small>{money(l.lineTotalMinor)}</small></div><div className="guest-qty"><button aria-label={l.productName+' azalt'} disabled={!live.canMutate||!!pendingOrder} onClick={()=>void change(l.productId,-1,l.option)}>−</button><b>{l.quantity}</b><button aria-label={l.productName+' artır'} disabled={!live.canMutate||!!pendingOrder} onClick={()=>void change(l.productId,1,l.option)}>＋</button></div></div>):<p className="guest-empty">Henüz bir ürün seçmediniz.</p>}<div className="guest-total"><span>Benim seçimlerim</span><strong>{money(cart?.ownTotalMinor??0n)}</strong></div><button className="guest-primary full" disabled={busy||!live.online||live.stale||(!pendingOrder&&(!live.canMutate||!mine.length))} onClick={()=>void send()}>{busy?'Gönderiliyor…':pendingOrder?'Önceki siparişi doğrula':'Seçimlerimi siparişe gönder'}</button>{recommendations.length>0&&<div className="guest-upsell"><h3>Yanına güzel gider</h3>{recommendations.map(p=><div key={p.productId}><span>{p.productName} · {money(p.priceMinor)}</span><button disabled={!live.canMutate||!!pendingOrder} onClick={()=>void change(p.productId,1)}>＋ Ekle</button></div>)}</div>}</section>}
 {tab==='orders'&&<section className="guest-card"><h2>Siparişlerim</h2><p>Gönderildi → kabul edildi → hazırlanıyor → hazır → servis edildi.</p>{orders.length?orders.filter(o=>o.isMine!==false).map(o=><article className="guest-order" key={o.id}><header><strong>#{o.id.slice(-6)} · {o.isMine?'Benim siparişim':o.seat?'Misafir '+o.seat:'Personel siparişi'}</strong><span className="tag">{o.rejected?'İşletme tarafından kabul edilmedi':o.status==='submitted'?'İşletme kabulü bekleniyor':label(o.status)}</span></header>{o.lines?.map((l:any,i:number)=><div className="guest-line" key={i}><span>{l.quantity} × {l.name}</span><strong>{money(l.amountMinor)}</strong></div>)}{o.cancelState&&<p className="helper">İptal talebi: {o.cancelState==='pending'?'İşletme onayı bekliyor':o.cancelState==='approved'?'Onaylandı':'Kabul edilmedi'}</p>}{o.isMine&&['submitted','accepted','preparing'].includes(o.status)&&o.cancelState!=='pending'&&<button className="text-button" onClick={()=>{setCancelOrder(o.id);setReason('');}}>İptal talebi oluştur</button>}</article>):<p className="guest-empty">Henüz gönderilmiş sipariş yok.</p>}{!live.accessDenied&&orders.some(o=>['served','completed'].includes(o.status))&&<VisitFeedback checkId={scope.checkId} guestId={scope.userId} disabled={!live.online}/>} {cancelOrder&&<form className="guest-cancel" onSubmit={e=>{e.preventDefault();void cancel();}}><label>İptal gerekçeniz<textarea maxLength={300} required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn" type="button" onClick={()=>setCancelOrder(null)}>Vazgeç</button><button className="btn primary" disabled={busy}>Talebi gönder</button></form>}</section>}
 {tab==='bill'&&<section className="guest-card"><h2>Hesap</h2><div className="guest-total"><span>Benim gönderdiğim siparişler</span><strong>{money(cart?.ownBillMinor??0n)}</strong></div><p>Burada yalnızca bu telefondan verdiğiniz siparişler görünür. Masanızın ortak hesabı ve ödemeniz için personelimiz yardımcı olacaktır.</p><button className="guest-primary full" disabled={!open||busy||!live.online} onClick={()=>void service('bill')}>Hesabı iste · kasada öde</button><div className="guest-account-invite"><h3>Bir sonraki ziyaret için</h3><p>Hesap açmak isteğe bağlıdır. Bu masada sipariş vermek için üyelik gerekmez.</p><Link href="/hesabim">Ziyaretlerimi görüntüle →</Link></div></section>}
 <nav className="guest-dock"><div><small>Benim seçimlerim</small><strong>{cart?money(cart.ownTotalMinor):'…'}</strong></div><button className="guest-primary" onClick={()=>setTab('cart')}>Seçimlerimi gör →</button></nav></main>;
}
