'use client';
import {useEffect,useRef,useState} from 'react';
import {Card} from './Shell';
import {llmApi as api} from '@/lib/llm/browser';
import {llmMessage,llmModels,type LlmStatus} from '@/lib/llm/messages';
type Status=LlmStatus&{products:{id:string;name:string}[]};
type Pending={operationId:string;task:string;question:string;productId:string|null;day:string};
type Answer={answer:string;warnings:string[];sources:{id:string;title:string;data:Record<string,unknown>}[];capturedAt:string;draftOnly:true};
const tasks=[['menu','Menüyü değerlendir','Açıklaması ve porsiyonu eksik ürünleri, kategori tutarlılığını değerlendir.'],['description','Ürün açıklaması','Bu ürün için yalnızca kayıtlı içerikten kısa, iştah açıcı bir açıklama taslağı yaz.'],['translation','İngilizce çeviri','Ürün adını, mevcut açıklamayı, porsiyonu ve seçenekleri İngilizceye çevir.'],['campaign','Paylaşım metni','Bu ürün için Instagram gönderi açıklaması yaz. İndirim veya içerik uydurma.'],['daily','Günü özetle','Seçilen günün sipariş ve kasa raporunu özetle; tahsilat ile sipariş tutarını ayır.']];
export function LlmAssistant(){
 const[status,setStatus]=useState<Status|null>(null),[provider,setProvider]=useState<'self_hosted'|'openrouter_free'>('openrouter_free'),[model,setModel]=useState('qwen3.5:4b'),[key,setKey]=useState(''),[limit,setLimit]=useState(30),[enabled,setEnabled]=useState(true),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 const[task,setTask]=useState('menu'),[question,setQuestion]=useState(tasks[0][2]),[product,setProduct]=useState(''),[day,setDay]=useState(''),[answer,setAnswer]=useState<Answer|null>(null),[answerModel,setAnswerModel]=useState(''),[pending,setPending]=useState<Pending|null>(null);
 const mounted=useRef(true),testOp=useRef<string|null>(null);
 async function load(){try{const s=await api<Status>('/api/llm/status');if(!mounted.current)return;setStatus(s);const p=s.provider==='self_hosted'?'self_hosted':'openrouter_free';setProvider(p);setModel((s.provider===p&&s.model)?s.model:llmModels[p][0][0]);setLimit(s.dailyLimit);setEnabled(s.configured?s.enabled:true);}catch(e){if(mounted.current)setError(llmMessage(e));}}
 useEffect(()=>{mounted.current=true;setDay(new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'}));void load();return()=>{mounted.current=false;};},[]);
 async function save(){if(!status||busy)return;setBusy(true);setError('');setNote('');try{await api('/api/llm/settings',{version:status.version,provider,model,...(key?{apiKey:key}:{}),dailyLimit:limit,enabled,consent});setNote('LLM bağlantısı kaydedildi. Küçük bir test isteğiyle model erişimini doğrulayın.');await load();}catch(e){setError(llmMessage(e));}finally{setKey('');setConsent(false);setBusy(false);}}
 async function probe(){if(busy)return;setBusy(true);setError('');setNote('');testOp.current??=crypto.randomUUID();try{const r=await api<any>('/api/llm/test',{operationId:testOp.current});if(r.result?.verified){setNote('Gerçek model yanıtı alındı. LLM bağlantısı doğrulandı.');testOp.current=null;}await load();}catch(e){setError(llmMessage(e));if(!(e instanceof Error)||!['LLM_RESULT_UNKNOWN','LLM_SAVE_UNKNOWN','LLM_IN_PROGRESS'].includes(e.message))testOp.current=null;}finally{setBusy(false);}}
 async function disconnect(){if(!status||!window.confirm('Bu işletmenin LLM anahtarı silinsin mi? Mevcut menü ve siparişler korunur. Başlamış sağlayıcı çağrısı geri alınamaz.'))return;setBusy(true);setError('');try{await api('/api/llm/disconnect',{version:status.version});setNote('Sağlayıcı bağlantısı ve saklanan anahtar kaldırıldı.');setAnswer(null);setPending(null);await load();}catch(e){setError(llmMessage(e));}finally{setBusy(false);}}
 async function send(existing?:Pending){if(busy)return;const p=existing||{operationId:crypto.randomUUID(),task,question,productId:product||null,day};setPending(p);setBusy(true);setError('');setNote('');setAnswer(null);try{const r=await api<any>('/api/llm/ask',p);if(mounted.current){setAnswer(r.result);setAnswerModel(r.model);setPending(null);await load();}}catch(e){if(mounted.current){setError(llmMessage(e));if(e instanceof Error&&!['LLM_RESULT_UNKNOWN','LLM_SAVE_UNKNOWN','LLM_IN_PROGRESS','LLM_CONNECTION_UNAVAILABLE'].includes(e.message))setPending(null);}}finally{if(mounted.current)setBusy(false);}}
 const ready=!!status&&['self_hosted','openrouter_free'].includes(status.provider||'')&&!!status.enabled&&!!status.verified;
 return <section className="llm-studio" aria-label="LLM Asistanı">
 <Card className="llm-hero"><div><p className="eyebrow">MENÜGO · İŞLETME ASİSTANI</p><h2>Menünüzü bilen<br/>bir çalışma arkadaşı.</h2><p>Menüyü değerlendirin, ürün metni hazırlayın, çevirin ve günlük raporu yorumlayın. Son karar ve yayın kontrolü sizde.</p></div><div className="llm-status"><span className={'tag '+(ready?'':'muted')}>{ready?'Bağlantı doğrulandı':status?.configured?'Bağlantı testi gerekli':'LLM bağlantısı bekleniyor'}</span><strong>{status?.provider==='openrouter_free'?'OpenRouter · Ücretsiz router':status?.provider==='self_hosted'?status.model:'Ücretsiz/açık model bağlantısı'}</strong><small>Menüye, siparişe ve ödemeye otomatik yazma yok.</small></div></Card>
 {error&&<p className="alert" role="alert">{error}</p>}{note&&<p className="notice" role="status">{note}</p>}
 <div className="llm-grid"><Card>
 <h2>Ücretsiz / açık model bağlantısı</h2><p>Sunucu kurmadan OpenRouter’ın yalnız ücretsiz modellere yönlenen <strong>openrouter/free</strong> rotasını kullanabilir veya kendi Ollama/vLLM sunucunuzu seçebilirsiniz. Ücretli modele otomatik geçiş yok.</p><p className="notice">OpenRouter seçeneğinde istek başına sıfır veri saklama (ZDR), veri toplamayı reddetme ve gerekli parametre desteği zorunlu tutulur. Uygun ücretsiz uç nokta yoksa işlem başarısız olur; ücretli modele düşmez.</p>
 {!status?<p>Yetki doğrulanıyor…</p>:<><dl className="llm-meta"><div><dt>Bağlantı</dt><dd>{status.configured?'Anahtar güvenli kasada kayıtlı':'Henüz anahtar yok'}</dd></div><div><dt>Bugünkü denemeler</dt><dd>{status.usedToday} / {status.dailyLimit}</dd></div></dl>
 {status.canManage?<details open={!status.configured||!['self_hosted','openrouter_free'].includes(status.provider||'')}><summary>Bağlantıyı yönet</summary><div className="llm-form">
 <label>LLM sağlayıcısı<select value={provider} disabled={busy} onChange={e=>{const p=e.target.value as 'self_hosted'|'openrouter_free';setProvider(p);setModel(llmModels[p][0][0]);setKey('');}}><option value="openrouter_free">Sunucusuz · OpenRouter ücretsiz router</option><option value="self_hosted">Kendi sunucum · Açık modeller</option></select></label>
 <label>Model<select value={model} disabled={busy} onChange={e=>setModel(e.target.value)}>{llmModels[provider].map(m=><option key={m[0]} value={m[0]}>{m[1]}</option>)}</select></label>
 <label>API anahtarı<input type="password" autoComplete="new-password" spellCheck={false} maxLength={512} value={key} onChange={e=>setKey(e.target.value)} placeholder={status.configured?'Değiştirmeyecekseniz boş bırakın':provider==='openrouter_free'?'OpenRouter API anahtarı':'Kendi model sunucunuzun erişim anahtarı'}/></label>
 <p className="helper">Anahtar Supabase Vault’ta şifreli saklanır; kayıtlı anahtar geri gösterilmez. Anahtarı sohbet kutusuna veya destek mesajına yazmayın.</p>
 <label>Günlük deneme üst sınırı<input type="number" min={1} max={100} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label>
 <label className="llm-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>LLM kullanımına izin ver</label>
 <label className="llm-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Seçtiğim menü belgeleri, ürün bilgileri ve günlük özetin seçtiğim sağlayıcıya gönderileceğini onaylıyorum. OpenRouter kullanımında veri model sağlayıcısına iletilir; MenüGO isteği ZDR ve veri toplamama koşullarıyla sınırlar.</label>
 <button className="btn primary" disabled={busy||!consent||((!status.configured||status.provider!==provider)&&!key)||limit<1||limit>100} onClick={()=>void save()}>Bağlantıyı kaydet</button>
 {status.configured&&<button className="text-button" disabled={busy} onClick={()=>void disconnect()}>Anahtarı sil ve bağlantıyı kaldır</button>}
 </div></details>:<p className="helper">Sağlayıcı ayarlarını işletme sahibi yönetir.</p>}
 <div className="llm-actions"><button className="btn" disabled={busy||!status.configured||!status.enabled||!['self_hosted','openrouter_free'].includes(status.provider||'')} onClick={()=>void probe()}>Bağlantıyı test et</button><button className="text-button" disabled={busy} onClick={()=>void load()}>Durumu yenile</button></div>
 <p className="helper">Test, seçili ücretsiz/açık model bağlantısına tek küçük istek gönderir. Başarılı model yanıtı gelmeden üretim açılmaz. Günlük sınır kullanımı kontrol eder; ücretli modele geçiş, kredi alımı veya otomatik satın alma yapılmaz.</p>
 </>}
 </Card><Card>
 <h2>Nasıl yardımcı olayım?</h2><div className="llm-task-grid">{tasks.map(t=><button key={t[0]} className={'llm-task '+(task===t[0]?'active':'')} disabled={busy||!!pending} onClick={()=>{setTask(t[0]);setQuestion(t[2]);setAnswer(null);}}>{t[1]}</button>)}</div>
 <div className="llm-form">{['description','translation','campaign'].includes(task)&&<label>İlgili ürün<select value={product} disabled={busy||!!pending} onChange={e=>setProduct(e.target.value)}><option value="">Ürün seçin</option>{status?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 {task==='daily'&&<label>Rapor günü<input type="date" value={day} disabled={busy||!!pending} onChange={e=>setDay(e.target.value)}/></label>}
 <label>İsteğiniz<textarea maxLength={1500} rows={5} value={question} disabled={busy||!!pending} onChange={e=>setQuestion(e.target.value)} placeholder="Menünüz veya günlük raporunuz hakkında sorun…"/></label>
 <p className="helper">Müşteri telefonu, adresi veya kişisel veri yazmayın. Model yalnız kayıtlı menü ve seçili günlük raporla çalışır; CRM kişileri gönderilmez.</p>
 {!pending?<button className="btn primary" disabled={busy||!ready||!question.trim()||(['description','translation','campaign'].includes(task)&&!product)} onClick={()=>void send()}>Taslak yanıt oluştur</button>:<div className="llm-actions"><button className="btn" disabled={busy} onClick={()=>void send(pending)}>{busy?'Model yanıtı bekleniyor…':'Aynı işlemin sonucunu kontrol et'}</button><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm('Önceki çağrı sonuçlanmış olabilir. Yeni deneme ayrı kullanım oluşturabilir. Yeni istek hazırlansın mı?'))setPending(null);}}>Yeni istek hazırla</button></div>}
 </div>
 {answer&&<article className="llm-answer" aria-label="LLM yanıtı"><div className="section-heading"><strong>AI taslağı · {answerModel}</strong><button className="text-button" onClick={()=>void navigator.clipboard.writeText(answer.answer).then(()=>setNote('Taslak metin kopyalandı. Menüye uygulanmadı.')).catch(()=>setError('Metni seçerek kopyalayın.'))}>Metni kopyala</button></div><p className="llm-answer-text">{answer.answer}</p>{answer.warnings.map((w,i)=><p className="notice" key={i}>{w}</p>)}<p className="helper">AI yanılabilir. Bu yanıt hiçbir ürün, fiyat, sipariş veya kampanyayı değiştirmedi.</p><details><summary>Kullanılan kayıtlar ({answer.sources.length})</summary>{answer.sources.map(s=><div className="llm-source" key={s.id}><strong>{s.title}</strong><pre>{JSON.stringify(s.data,null,2)}</pre></div>)}</details></article>}
 {!answer&&!busy&&<div className="llm-empty"><span aria-hidden>✦</span><h3>Önce kaynak, sonra yorum.</h3><p>Yanıtın altında hangi ürünlerin veya raporun kullanıldığını görebilirsiniz. Fiyat hesabı, ödeme ve sadakat kuralları LLM’ye bırakılmaz.</p></div>}
 </Card></div></section>;
}
