'use client';
import MenuGoLogo from '@/components/MenuGoLogo';
import {useEffect,useState,type FormEvent} from 'react';import Link from 'next/link';import {getBrowserClient} from '@/lib/supabase/browser';import {api} from './transport';import {safeDestination,accountDestination} from '@/lib/auth-destination';
const roles=[['customer','Müşteri','Kalıcı hesap · isteğe bağlı','/hesabim'],['merchant','Üye işyeri','İşletme yönetimi','/isletme'],['waiter','Garson','Masalar ve servis','/garson'],['kitchen','Mutfak','Hazırlık ve sipariş sırası','/mutfak'],['cashier','Kasa','Adisyon ve tahsilat kaydı','/kasa']];

export function Login(){const[mode,setMode]=useState<'login'|'signup'>('login');const[role,setRole]=useState('merchant');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[show,setShow]=useState(false);const[next,setNext]=useState<string|null>(null);
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('mode')==='signup')setMode('signup');if(roles.some(r=>r[0]===q.get('role')))setRole(q.get('role')!);setNext(safeDestination(q.get('next')));if(q.has('error'))setMessage('Doğrulama bağlantısı kullanılmış veya süresi dolmuş olabilir. E-postanız doğrulandıysa aşağıdan giriş yapın.');},[]);
 async function destination(){if(next&&['/platform','/platform/ayarlar','/platform/yapay-zeka'].includes(next.split('?')[0])){try{await api(next.split('?')[0]==='/platform/yapay-zeka'?'/api/platform/ai/context':'/api/platform/control/state');return next;}catch{}}const membership=await api('/api/merchant/claim',{});return accountDestination(membership.role??null,role,next);}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const s=getBrowserClient();if(mode==='signup'){const {data,error}=await s.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:location.origin+'/auth/callback'+(next?'?next='+encodeURIComponent(next):'')}});if(error){setMessage('Hesap oluşturulamadı. E-posta adresinizi, parola koşullarını ve bağlantınızı kontrol edin.');return;}if(data.session){try{await api('/api/session',{});}catch{}location.assign(await destination());return;}setMessage('Doğrulama e-postası gönderildi. E-postadaki bağlantıyı açtıktan sonra bu sayfaya dönüp “Giriş yap”ı seçin. Personel yetkiniz işletme yöneticisinin davetiyle tanımlanır.');setMode('login');return;}
 const{error}=await s.auth.signInWithPassword({email:email.trim(),password});if(error){setMessage('Giriş yapılamadı. E-posta doğrulamasını tamamladığınızdan ve parolanızın doğru olduğundan emin olun.');return;}
 try{await api('/api/session',{});}catch{}location.assign(await destination());
 }catch{setMessage('Bağlantı kurulamadı. Lütfen yeniden deneyin.');}finally{setBusy(false);}}
 async function resend(){if(!email.trim()){setMessage('Önce e-posta adresinizi yazın.');return;}setBusy(true);try{const{error}=await getBrowserClient().auth.resend({type:'signup',email:email.trim(),options:{emailRedirectTo:location.origin+'/auth/callback'+(next?'?next='+encodeURIComponent(next):'')}});setMessage(error?'Doğrulama e-postası gönderilemedi. Biraz sonra yeniden deneyin.':'Doğrulama bağlantısı yenilendi. Gelen kutunuzu kontrol edin.');}catch{setMessage('E-posta isteği tamamlanamadı.');}finally{setBusy(false);}}
 return <main className="merchant-login"><section className="merchant-login-intro"><a href="/bahcesehir"><img src="/media/sariyer-brand-transparent-r8.webp" alt="Meşhur Sarıyer Börekçisi Sandviç" width="600" height="200"/></a><div><p className="merchant-eyebrow">BAHÇEŞEHİR · DİJİTAL İŞLETME MERKEZİ</p><h1>Lezzet aynı.<br/><em>Deneyim yepyeni.</em></h1><p>Masanızdan mutfağa, servisten kasaya.<br/>Doğru yetkiyle, aynı işletmede buluşun.</p><Link href="/bahcesehir">← Menüyü keşfet</Link></div><a className="login-powered" href="https://www.menugo.app/"><small>Yeni Nesil Dijital Menü</small><MenuGoLogo tone="dark" alt="MenüGO" width="560" height="147"/></a></section><section className="merchant-login-side"><div className="merchant-login-box"><p className="merchant-eyebrow">GÜVENLİ HESAP ERİŞİMİ</p><h2>{mode==='signup'?'Hesabınızı oluşturun.':'Hoş geldiniz.'}</h2><div className="role-selector" aria-label="Çalışma alanı">{roles.map(([id,title,,path])=><button type="button" key={id} aria-pressed={role===id} className={role===id?'active':''} onClick={()=>setRole(id)}>{title}</button>)}</div><p>{roles.find(r=>r[0]===role)![2]}</p>{role==='customer'&&<div className="notice">Menü ve masa siparişi için hesap gerekmez.<Link className="btn primary" href="/siparis">Üye olmadan devam et</Link></div>}<form onSubmit={submit}><label>E-posta<input name="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-posta adresiniz"/></label><label>Parola<div className="password-field"><input name="password" type={show?'text':'password'} minLength={mode==='signup'?12:undefined} maxLength={128} autoComplete={mode==='signup'?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Parolayı gizle':'Parolayı göster'}>{show?'Gizle':'Göster'}</button></div></label>{mode==='signup'&&<small>En az 12 karakter. Hesap açılması personel yetkisi vermez.</small>}<button className="merchant-action full" disabled={busy}>{busy?'İşlem sürüyor…':mode==='signup'?'Hesap oluştur':'Giriş yap →'}</button></form>{message&&<p className="merchant-notice" role="status">{message}</p>}<button className="text-button" onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('');}}>{mode==='signup'?'Zaten hesabınız var mı? Giriş yap':'İlk kez mi kullanıyorsunuz? Hesap oluştur'}</button><button className="text-button" onClick={()=>void resend()} disabled={busy}>Doğrulama e-postasını yeniden gönder</button><Link className="text-button" href="/parola">Parolamı unuttum</Link><p className="login-help">Personel hesabı için yöneticinizin tanımladığı e-posta adresini kullanın. Rol seçimi yalnızca çalışma ekranını belirler; yetkiler sunucuda kontrol edilir.</p><Link href="/bahcesehir" className="back-link">← Müşteri menüsüne dön</Link></div></section></main>;
}
