'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card,Empty} from './Shell';
import {api,explain,money} from './transport';
type Branch={id:string;name:string;slug:string};type Candidate={branchId:string;branchName:string;sourceId:string;name:string;priceMinor:string};
type Binding={branchId:string;branchName:string;productSourceId:string;productName:string;overridePriceMinor:string|null;overrideVersion:string|null;effectivePriceMinor:string;cataloguePriceMinor:string|null;drift:boolean};
type Master={id:string;key:string;name:string;basePriceMinor:string;version:string;active:boolean;bindings:Binding[]};
type Snapshot={role:'owner'|'manager';currentBranchId:string;branches:Branch[];masters:Master[];unboundProducts:Candidate[]};
const priceInput=(minor:string)=>`${BigInt(minor)/100n},${(BigInt(minor)%100n).toString().padStart(2,'0')}`;
function parsePrice(v:string){const m=v.trim().replace(/\s/g,'').replace('.',',').match(/^(\d{1,7})(?:,(\d{1,2}))?$/);if(!m)throw Error('INVALID_PRICE');return (BigInt(m[1])*100n+BigInt((m[2]??'').padEnd(2,'0')||'0')).toString();}
export function MultiBranchMenu(){const[data,setData]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[candidate,setCandidate]=useState('');
 async function load(){try{setData(await api('/api/merchant/multi-branch-menu'));setMessage('');}catch(e){setMessage(explain(e));}}
 useEffect(()=>{void load();},[]);
 async function command(name:string,payload:Record<string,unknown>){setBusy(true);setMessage('');try{await api('/api/merchant/multi-branch-menu',{operationId:crypto.randomUUID(),command:name,payload});await load();setMessage('Değişiklik kaydedildi.');}catch(e){setMessage(explain(e));}finally{setBusy(false);}}
 const currentCandidates=useMemo(()=>data?.unboundProducts.filter(x=>x.branchId===data.currentBranchId)??[],[data]);
 if(!data)return <Card><p role="status">{message||'Ana menü hazırlanıyor…'}</p></Card>;
 return <div className="studio-stack"><Card><div className="section-heading"><div><p className="eyebrow">ÇOK ŞUBELİ YÖNETİM</p><h1>Ana menü ve yerel fiyatlar</h1></div><span className="tag">{data.role==='owner'?'İşletme sahibi':'Yönetici'}</span></div><p>Ana fiyat, yerel fiyat tanımlanmamış bağlı şubelere uygulanır. Yerel fiyat yalnız seçilen şubeyi değiştirir. Her değişiklik işlem kimliği, satır kilidi ve sürüm kontrolüyle kaydedilir.</p>{message&&<p className="notice" role="status">{message}</p>}<div className="inline-form"><label>Bu şubeden ana ürüne dönüştür<select value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">Ürün seçin</option>{currentCandidates.map(x=><option key={x.sourceId} value={x.sourceId}>{x.name} · {money(x.priceMinor)}</option>)}</select></label><button className="btn primary" disabled={busy||!candidate} onClick={()=>void command('create-master',{productSourceId:candidate})}>Ana ürüne ekle</button></div></Card>
 {data.masters.length===0?<Empty title="Henüz ana ürün yok" description="Mevcut şube ürünlerinden birini ana menüye ekleyerek başlayın."/>:data.masters.map(m=><MasterCard key={m.id} master={m} data={data} busy={busy} command={command}/>)}</div>;
}
function MasterCard({master:m,data,busy,command}:{master:Master;data:Snapshot;busy:boolean;command:(n:string,p:Record<string,unknown>)=>Promise<void>}){const[base,setBase]=useState(priceInput(m.basePriceMinor)),[targetBranch,setTargetBranch]=useState(''),[targetProduct,setTargetProduct]=useState('');const candidates=data.unboundProducts.filter(x=>!targetBranch||x.branchId===targetBranch);return <Card><div className="section-heading"><div><h2>{m.name}</h2><small>Ana fiyat: {money(m.basePriceMinor)} · sürüm {m.version}</small></div>{m.bindings.some(x=>x.drift)&&<span className="tag">Fiyat farkı kontrol edilmeli</span>}</div>
 {data.role==='owner'&&<div className="inline-form"><label>Ana fiyat<input value={base} inputMode="decimal" onChange={e=>setBase(e.target.value)} aria-label={m.name+' ana fiyat'}/></label><button className="btn" disabled={busy} onClick={()=>{try{void command('set-master-price',{masterItemId:m.id,priceMinor:parsePrice(base),expectedVersion:m.version});}catch(e){alert(explain(e));}}}>Ana fiyatı uygula</button></div>}
 <div>{m.bindings.map(b=><BindingRow key={b.branchId} master={m} binding={b} busy={busy} command={command}/>)}</div>
 {data.role==='owner'&&<details><summary>Başka şubedeki ürünü bağla</summary><div className="inline-form"><label>Şube<select value={targetBranch} onChange={e=>{setTargetBranch(e.target.value);setTargetProduct('');}}><option value="">Şube seçin</option>{data.branches.filter(b=>!m.bindings.some(x=>x.branchId===b.id)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Onaylı ürün<select value={targetProduct} disabled={!targetBranch} onChange={e=>setTargetProduct(e.target.value)}><option value="">Ürün seçin</option>{candidates.filter(x=>x.branchId===targetBranch).map(x=><option key={x.sourceId} value={x.sourceId}>{x.name} · {money(x.priceMinor)}</option>)}</select></label><button className="btn" disabled={busy||!targetBranch||!targetProduct} onClick={()=>void command('bind-product',{masterItemId:m.id,targetBranchId:targetBranch,productSourceId:targetProduct})}>Şubeye bağla</button></div></details>}</Card>}
function BindingRow({master,binding:b,busy,command}:{master:Master;binding:Binding;busy:boolean;command:(n:string,p:Record<string,unknown>)=>Promise<void>}){const[value,setValue]=useState(priceInput(b.effectivePriceMinor));return <div className="list-row"><div><strong>{b.branchName}</strong><small>{b.productName} · Katalog {b.cataloguePriceMinor?money(b.cataloguePriceMinor):'onaysız'} · Etkin {money(b.effectivePriceMinor)}{b.overridePriceMinor?' · yerel':''}{b.drift?' · katalog farklı':''}</small></div><div className="inline-form"><label>Yerel fiyat<input value={value} inputMode="decimal" onChange={e=>setValue(e.target.value)} aria-label={b.branchName+' yerel fiyat'}/></label><button className="btn" disabled={busy} onClick={()=>{try{void command('set-local-price',{masterItemId:master.id,targetBranchId:b.branchId,priceMinor:parsePrice(value),expectedOverrideVersion:b.overrideVersion??'-1'});}catch(e){alert(explain(e));}}}>Yerel fiyatı kaydet</button>{b.overridePriceMinor&&<button className="text-button" disabled={busy} onClick={()=>void command('clear-local-price',{masterItemId:master.id,targetBranchId:b.branchId,expectedOverrideVersion:b.overrideVersion})}>Ana fiyata dön</button>}</div></div>}
