'use client';
import {useEffect,useState} from 'react';
import {Card,Empty} from './Shell';
import {api,explain,money} from './transport';

export function PriceEditor({products,reload,demo=false}:{products:any[];reload:()=>Promise<void>;demo?:boolean}) {
 const [search,setSearch]=useState('');const [selected,setSelected]=useState<any>(null);const [price,setPrice]=useState('');const [available,setAvailable]=useState(true);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 function edit(p:any){setSelected(p);setPrice(p.priceMinor===null?'':`${BigInt(p.priceMinor)/100n},${(BigInt(p.priceMinor)%100n).toString().padStart(2,'0')}`);setAvailable(p.available);setNotice('');}
 async function save(){if(!selected)return;setBusy(true);setNotice('');try{if(!/^\d{1,7}([,.]\d{1,2})?$/.test(price.trim()))throw new Error('INVALID_PRICE');const [whole,fraction='']=price.trim().replace(',','.').split('.');const minor=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(minor<=0n||minor>100000000n)throw new Error('INVALID_PRICE');if(demo){setNotice('Demo: fiyat değişikliği canlı menüye gönderilmedi.');return;}await api('/api/ops/save-product',{productId:selected.id,priceMinor:minor.toString(),available,expectedUpdatedAt:selected.updatedAt});await reload();setSelected(null);setNotice('Ürün güncellendi. Yeni fiyat bir sonraki menü isteğinde görünür.');}catch(e){setNotice(explain(e));}finally{setBusy(false);}}
 return <><Card><h2>Menü & fiyat yönetimi</h2><p>Onayladığınız fiyatlar kuruş hassasiyetiyle kaydedilir. Tükenen ürünleri satışa kapatabilirsiniz.</p><input aria-label="Menü yönetiminde ürün ara" placeholder="Ürün ara…" value={search} onChange={e=>setSearch(e.target.value)}/>{notice&&<p className="notice" role="status">{notice}</p>}<div className="menu-editor-list">{products.filter(p=>p.name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))).map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><small>{p.available?'Satışta':'Tükendi'} · {p.approved?'Fiyat onaylı':'Fiyat gerekli'}{p.optionCount>0?' · Seçenekli ürün':''}</small></div><strong>{money(p.priceMinor)}</strong><button className="btn" onClick={()=>edit(p)}>Düzenle</button></div>)}</div></Card>{selected&&<div className="pilot-modal-backdrop" role="presentation"><section className="pilot-modal" role="dialog" aria-modal="true" aria-labelledby="edit-product-title"><h2 id="edit-product-title">{selected.name}</h2><label>Satış fiyatı (TL)<input autoFocus inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="160,00"/></label><label className="check-label"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Satışa uygun</label>{notice&&<p className="notice" role="status">{notice}</p>}<div className="inline-actions"><button className="btn" disabled={busy} onClick={()=>setSelected(null)}>Vazgeç</button><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'Kaydediliyor…':'Fiyatı onayla ve kaydet'}</button></div></section></div>}</>;
}

export function TableInvitation({url}:{url:string}) {
 const [image,setImage]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{let alive=true;void import('qrcode').then(q=>q.toDataURL(url,{width:420,margin:4,errorCorrectionLevel:'M'})).then(v=>{if(alive)setImage(v);}).catch(()=>setMessage('QR oluşturulamadı; bağlantıyı kullanabilirsiniz.'));return()=>{alive=false;};},[url]);
 return <Card><h2>Masa katılımı</h2><p>Bu QR aynı açık adisyona katılır. Katılım bağlantısı 10 dakika geçerlidir; yeniden bağlantı oluşturmak mevcut sepeti silmez.</p><div className="table-qr">{image&&<img src={image} width={260} height={260} alt="Masa katılım QR kodu"/>}<div><a className="btn primary" href={url} target="_blank" rel="noreferrer">Bu masada sipariş aç ↗</a><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Bağlantı kopyalandı.');}catch{setMessage('Bağlantıyı aşağıdaki alandan kopyalayın.');}}}>Bağlantıyı kopyala</button><input aria-label="Masa katılım bağlantısı" readOnly value={url} onFocus={e=>e.target.select()}/><p className="helper">QR’yi yalnızca bu masadaki misafirlerle paylaşın. Uzun süreli baskı için değil, açık adisyon katılımı içindir.</p>{message&&<p role="status">{message}</p>}</div></div></Card>;
}

export function PilotSettings({settings,reload,demo=false}:{settings:any;reload:()=>Promise<void>;demo?:boolean}) {
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function toggle(){setBusy(true);setMessage('');try{if(demo){setMessage('Demo: canlı sipariş ayarları değişmedi.');return;}await api('/api/ops/dine-in',{enabled:!settings?.orderingEnabled});await reload();setMessage('Masada sipariş ayarı güncellendi.');}catch(e){setMessage(explain(e));}finally{setBusy(false);}}
 return <Card><h2>Masada sipariş kontrolü</h2><p>QR katılımı personelin açtığı adisyonla sınırlıdır. Online ödeme, paket servis ve kampanya gönderimleri bu düğmeden açılmaz.</p><div className="section-heading"><span className={'tag '+(settings?.orderingEnabled?'green':'gray')}>{settings?.orderingEnabled?'Masada sipariş açık':'Masada sipariş kapalı'}</span><button className={'btn '+(settings?.orderingEnabled?'':'primary')} disabled={busy} onClick={()=>void toggle()}>{settings?.orderingEnabled?'Yeni siparişleri durdur':'Masada siparişi aç'}</button></div>{message&&<p className="notice" role="status">{message}</p>}</Card>;
}

export function Counter({tables,receipts,reload,demo=false}:{tables:any[];receipts:any[];reload:()=>Promise<void>;demo?:boolean}) {
 const [id,setId]=useState('');const [info,setInfo]=useState<any>(null);const [method,setMethod]=useState('cash');const [reference,setReference]=useState('');const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [pending,setPending]=useState<any>(null);
 useEffect(()=>{let alive=true;setInfo(null);setConfirmed(false);setPending(null);setMessage('');if(!id||demo)return;try{const raw=sessionStorage.getItem('menugo:counter:'+id);if(raw)setPending(JSON.parse(raw));}catch{}void api('/api/ops/counter-info?check='+id).then(v=>{if(alive)setInfo(v);}).catch(e=>{if(alive)setMessage(explain(e));});return()=>{alive=false;};},[id,demo]);
 async function collect(){if(!info&&!pending)return;setBusy(true);setMessage('');const cmd=pending??{checkId:id,operationId:crypto.randomUUID(),expectedRevision:info.revision,amountMinor:info.totalMinor,method,reference:reference.trim()||null};try{sessionStorage.setItem('menugo:counter:'+id,JSON.stringify(cmd));setPending(cmd);const result=await api('/api/ops/counter-close',cmd);sessionStorage.removeItem('menugo:counter:'+id);setPending(null);setMessage('Kasada tahsilat kaydedildi; masa kapatıldı. Kayıt: '+result.receiptId.slice(0,8));setInfo(null);setId('');await reload();}catch(e){const code=e instanceof Error?e.message:'';if(['REVISION_CONFLICT','AMOUNT_CHANGED','SERVICE_NOT_FINISHED','SUBMIT_CART_FIRST','ONLINE_PAYMENT_REQUIRES_RECONCILIATION','CHECK_NOT_OPEN','INVALID_COUNTER_RECEIPT'].includes(code)){sessionStorage.removeItem('menugo:counter:'+id);setPending(null);setConfirmed(false);try{setInfo(await api('/api/ops/counter-info?check='+id));}catch{}}setMessage(explain(e));}finally{setBusy(false);}}
 async function manage(action:string){setBusy(true);try{await api('/api/ops/'+action,{checkId:id});setMessage(action==='cancel-split'?'Bölüşüm iptal edildi. Masa yeniden siparişe açık.':'Boş masa kapatıldı.');setId('');setInfo(null);await reload();}catch(e){setMessage(explain(e));}finally{setBusy(false);}}
 const canClose=info&&info.cartEmpty&&info.serviceComplete&&!info.hasOnlinePayment&&BigInt(info.totalMinor)>0n&&['open','checkout'].includes(info.status);
 return <><Card><h2>Kasa · Adisyon kapat</h2><p>Yalnızca kasada gerçekten alınmış nakit veya harici POS ödemesini kaydedin. Bu işlem karttan çekim yapmaz ve mali fiş/fatura yerine geçmez.</p><label>Masa<select value={id} disabled={busy||!!pending} onChange={e=>setId(e.target.value)}><option value="">Bir açık masa seçin</option>{tables.filter(t=>t.checkId).map(t=><option key={t.id} value={t.checkId}>{t.name}</option>)}</select></label>{demo&&<p className="notice">Bu alanda gerçek kasa kaydı yapılmaz.</p>}{message&&<p className="notice" role="status">{message}</p>}{info&&<><div className="total-band"><span>Adisyon toplamı</span><strong>{money(info.totalMinor)}</strong></div>{info.lines.map((l:any,i:number)=><div className="list-row" key={i}><span>{l.name}</span><strong>{money(l.amountMinor)}</strong></div>)}{!info.cartEmpty&&<p className="notice">Önce ortak sepeti gönderin veya temizleyin.</p>}{!info.serviceComplete&&<p className="notice">Önce mutfakta tüm siparişleri “Servis edildi / Tamamlandı” durumuna getirin.</p>}{info.hasOnlinePayment&&<p className="alert">Online ödeme girişimi var. Mutabakat yapılmadan kasadan tekrar tahsilat kaydı oluşturulamaz.</p>}{canClose&&<><label>Tahsilat yöntemi<select value={method} disabled={!!pending} onChange={e=>setMethod(e.target.value)}><option value="cash">Nakit</option><option value="external_pos">İşletmenin harici POS cihazı</option></select></label>{method==='external_pos'&&<label>POS işlem / fiş referansı<input value={reference} disabled={!!pending} maxLength={100} onChange={e=>setReference(e.target.value)}/></label>}<label className="check-label"><input type="checkbox" checked={confirmed} disabled={!!pending} onChange={e=>setConfirmed(e.target.checked)}/> {money(info.totalMinor)} tutarın tamamının kasada alındığını doğruluyorum.</label></>}{info.status==='checkout'&&!info.hasOnlinePayment&&!pending&&<button disabled={busy} className="btn" onClick={()=>void manage('cancel-split')}>Tahsilata başlanmamış bölüşümü iptal et</button>}{info.cartEmpty&&info.serviceComplete&&info.totalMinor==='0'&&info.status==='open'&&!pending&&<button disabled={busy} className="btn" onClick={()=>void manage('close-empty')}>Boş masayı kapat</button>}</>}{(canClose||pending)&&<button className="btn primary full" disabled={busy||(!pending&&(!confirmed||(method==='external_pos'&&!reference.trim())))} onClick={()=>void collect()}>{busy?'Kaydediliyor…':pending?'Önceki tahsilat kaydını doğrula':'Tahsilatı kaydet ve masayı kapat'}</button>}</Card><Card><h2>Kasada kaydedilen tahsilatlar</h2>{receipts.length?receipts.map(r=><div className="list-row" key={r.id}><div><strong>{r.table}</strong><small>{r.method==='cash'?'Nakit':'Harici POS'} · {r.reference??r.id.slice(0,8)} · {new Date(r.createdAt).toLocaleString('tr-TR')}</small></div><strong>{money(r.amountMinor)}</strong></div>):<Empty title="Henüz kasa kaydı yok" description="Tahsilat kaydedildiğinde adisyon kapanır ve değiştirilemez kayıt burada görünür."/>}</Card></>;
}
