'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import MenuGoLogo from './MenuGoLogo';
import {policyFields,roleNames,type Policy,type Principal,type ControlState,type Member} from '@/src/platform/control';
const nav=[['overview','Genel bakış'],['policies','Modüller & limitler'],['security','Güvenlik & erişim'],['team','Şirket ekibi'],['integrations','Entegrasyonlar'],['queues','İş kuyrukları'],['privacy','Veri & saklama'],['audit','Değişiklik geçmişi'],['runtime','Alan adı & yayın']] as const;
type Tab=typeof nav[number][0];
type Pending={action:string;url:string;body:Record<string,unknown>};
const errors:Record<string,string>={PLATFORM_ADMIN_REQUIRED:'Şirket yetkiniz bulunmuyor.',PLATFORM_PERMISSION_REQUIRED:'Bu işlem şirket rolünüzde bulunmuyor.',PLATFORM_VERSION_CHANGED:'Ayar başka bir oturumda değişti. Güncel değerleri yeniden yükleyin.',LAST_PLATFORM_OWNER:'Son aktif platform sahibi kaldırılamaz.',VERIFIED_ACCOUNT_REQUIRED:'Önce bu e-postayla hesap oluşturulmalı ve e-posta doğrulanmalı.',IDEMPOTENCY_CONFLICT:'İşlem anahtarı farklı bir içerikle kullanılmış. Durumu yeniden yükleyin.',INVALID_PLATFORM_REQUEST:'Alanları ve en az 5 karakterlik gerekçeyi kontrol edin.',INVALID_PLATFORM_POLICY:'Ayar değerleri geçersiz.',UNKNOWN_PLATFORM_SETTING:'Bu ayar desteklenmiyor.',INVALID_PLATFORM_LIMIT:'Günlük limit 1–50 arasında tam sayı olmalı.'};
const date=(v:string|null|undefined)=>v?new Date(v).toLocaleString('tr-TR'):'Henüz yok';
export function PlatformControl({principal}:{principal:Principal}){
 const[tab,setTab]=useState<Tab>('overview'),[selection,setSelection]=useState('global'),[data,setData]=useState<(ControlState&{runtime?:{release:string;hosts:string[]}})|null>(null),[draft,setDraft]=useState<Policy>({}),[reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[admission,setAdmission]=useState('direct');
 const[review,setReview]=useState<Pending|null>(null);const confirmButton=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{if(review)confirmButton.current?.focus();},[review]);
 const[pending,setPending]=useState<Pending|null>(null),[member,setMember]=useState<{email:string;role:string;active:boolean;previous:Record<string,unknown>}>({email:'',role:'auditor',active:true,previous:{}});
 const journalKey='menugo-company-command-v1:'+principal.userId;
 const alive=useRef(true),epoch=useRef(0),readAbort=useRef<AbortController|null>(null),lock=useRef(false);
 const branch=data?.branches.find(b=>b.branchId===selection);
 const suffix=branch?`?businessId=${encodeURIComponent(branch.businessId)}&branchId=${encodeURIComponent(branch.branchId)}`:'';
 async function load(scopeSuffix=suffix){const n=++epoch.current;readAbort.current?.abort();const controller=new AbortController();readAbort.current=controller;setLoading(true);setError('');
 try{const r=await fetch('/api/platform/control/state'+scopeSuffix,{credentials:'same-origin',cache:'no-store',redirect:'error',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])});const v=await r.json();if(!alive.current||n!==epoch.current)return;
 if(!r.ok){if([401,403].includes(r.status)){setData(null);setDraft({});}throw Error(v.error?.code||'REQUEST_FAILED');}setData(v);setDraft({...v.settings});setAdmission(v.admission?.mode??'direct');}
 catch(e){if(alive.current&&n===epoch.current&&!controller.signal.aborted)setError(errors[e instanceof Error?e.message:'']||'Veri alınamadı. Yeniden yükleyin.');}
 finally{if(alive.current&&n===epoch.current)setLoading(false);}}
 useEffect(()=>{alive.current=true;
 let query='';try{const raw=sessionStorage.getItem(journalKey);if(raw){const p=JSON.parse(raw) as Pending;const u=new URL(p.url,location.origin);if(u.origin===location.origin&&/^\/api\/platform\/control\/(policy|admission|member)$/.test(u.pathname)&&typeof p.body?.operationId==='string'){setPending(p);query=u.search;setSelection(u.searchParams.get('branchId')??'global');}else sessionStorage.removeItem(journalKey);}}catch{setError('Tarayıcı işlem kaydı okunamadı. Önce geçmişi kontrol edin.');}
 void load(query);return()=>{alive.current=false;epoch.current++;readAbort.current?.abort();};},[]);
 async function send(p:Pending){if(lock.current)return;try{sessionStorage.setItem(journalKey,JSON.stringify(p));}catch{setError('Güvenli tekrar kaydı oluşturulamadı. İşlem gönderilmedi.');return;}lock.current=true;setBusy(true);setError('');setNotice('');setPending(p);
 try{const r=await fetch(p.url,{method:'POST',credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify(p.body),signal:AbortSignal.timeout(20000)});const value=await r.json();if(!alive.current)return;
 if(!r.ok){if(r.status>=400&&r.status<500){sessionStorage.removeItem(journalKey);setPending(null);if([401,403].includes(r.status)){setData(null);setDraft({});}setError(errors[value.error?.code]||'İşlem reddedildi. Ayarları yeniden kontrol edin.');return;}throw Error('UNKNOWN');}
 sessionStorage.removeItem(journalKey);setPending(null);setReason('');await load();if(alive.current)setNotice('Kaydedildi. Değişiklik geçmişine işlendi.');
 }catch{if(alive.current)setError('Sonuç doğrulanamadı. Yeni işlem oluşturmayın; aynı işlemi kontrol ederek yeniden deneyin.');}
 finally{lock.current=false;if(alive.current)setBusy(false);}}
 const current=data??principal;
 const canPolicy=current.canManageAi||current.canManageOperations;
 const blocked=busy||loading||pending!==null||review!==null||!data;
 function commit(action:string,body:Record<string,unknown>){if(blocked||reason.trim().length<5)return;setReview({action,url:'/api/platform/control/'+action+suffix,body:structuredClone({...body,operationId:crypto.randomUUID(),reason:reason.trim()})});}
 function pick(value:string){if(blocked)return;const b=data?.branches.find(x=>x.branchId===value);setSelection(value);setData(d=>d?{...d,readiness:undefined,queues:undefined,admission:undefined,features:undefined}:d);setNotice('');setReason('');void load(b?`?businessId=${b.businessId}&branchId=${b.branchId}`:'');}
 const scopeSelect=<label className="pc-target">Yönetim kapsamı<select value={selection} disabled={blocked} onChange={e=>pick(e.target.value)}><option value="global">Tüm işletmeler · Global politika</option>{data?.branches.map(b=><option key={b.branchId} value={b.branchId}>{b.name}</option>)}</select></label>;
 const reasonField=<label>Değişiklik gerekçesi<input type="text" value={reason} disabled={blocked} onChange={e=>setReason(e.target.value)} maxLength={300} minLength={5} placeholder="Neden değiştiriyorsunuz? En az 5 karakter."/></label>;
 return <main className="pc-root"><header className="pc-header"><Link href="/platform" aria-label="MenüGO şirket merkezi"><MenuGoLogo alt="MenüGO" width="280" height="74"/></Link><div><span className="pc-badge">ŞİRKET YÖNETİMİ</span><p>{roleNames[current.role]??'Yetkili kullanıcı'}</p></div><Link className="btn" href="/isletme">İşletme paneli</Link></header>
 <div className="pc-layout"><nav className="pc-nav" aria-label="Şirket yönetimi bölümleri">{nav.filter(([key])=>key!=='team'||current.canManageMembers||current.canManageSecurity).map(([key,name])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setReason('');}}>{name}</button>)}{current.canManageAi&&<Link href="/platform/yapay-zeka">AI sağlayıcıları ↗</Link>}</nav>
 <div className="pc-content"><p className="eyebrow">MENÜGO KONTROL MERKEZİ</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1><p className="pc-lead">Altyapı şirketin kontrolünde; günlük işletme yönetimi restoranınızda.</p>{scopeSelect}
 <div className="pc-state"><span>Ücretli AI geçişi: <b>Kapalı</b></span><span>Harcamaya izin: <b>0</b></span><button type="button" disabled={busy||!!pending||!!review} onClick={()=>void load()}>Durumu yenile</button></div>
 {review&&<section className="pc-card pc-review" aria-label="Değişiklik onayı"><h2>Uygulamadan önce kontrol edin</h2><p><strong>{selection==='global'?'Tüm işletmeler · Global politika':branch?.name}</strong></p><p>{String(review.body.reason)}</p><p>Mevcut kayıtlar silinmez. Bu işlem şirket değişiklik geçmişine yazılacak.</p><button type="button" className="btn primary" ref={confirmButton} onClick={()=>{const p=review;setReview(null);void send(p);}}>Değişikliği uygula</button><button type="button" className="btn" onClick={()=>setReview(null)}>Vazgeç</button></section>}
 {error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{pending&&!busy&&<div className="notice"><strong>Kaydetme sonucu belirsiz.</strong><p>Aynı işlem kimliği ve aynı veri korunuyor. Başka kapsamda yeni işlem başlatılmıyor.</p><button className="btn" disabled={busy} onClick={()=>void send(pending)}>Aynı işlemi kontrol et / yeniden dene</button></div>}{loading&&<p role="status">Güncel kayıtlar alınıyor…</p>}
 {!data&&!loading&&<section className="pc-card"><h2>Yetkili veri yüklenemedi</h2><p>Bu ekran restoran sahipliğinden bağımsız şirket yetkisi gerektirir. Genel ayar veya anahtar gösterilmedi.</p><Link className="btn" href="/giris?next=%2Fplatform">Giriş yap</Link></section>}
 {data&&tab==='overview'&&<><section className="pc-banner"><h2>Tek merkez. Açık yetki sınırları.</h2><p>Modüller ve limitler, güvenlik politikası, sağlayıcılar, şirket ekibi ve işlem geçmişi. Müşteri verisi veya API anahtarı bu özete taşınmaz.</p></section><div className="pc-grid">{Object.entries(data.readiness??{branches:data.branches.length}).map(([k,v])=><Metric key={k} label={metricNames[k]??k} value={String(v)}/>)}</div><section className="pc-card"><h2>Şirket mi, işletme mi?</h2><div className="pc-columns"><div><h3>Şirket yönetir</h3><p>AI sağlayıcısı, ücretsiz kullanım politikası, teknik tavanlar, merkezi durdurma, masa güvenlik yöntemi ve şirket yetkileri.</p></div><div><h3>Restoran yönetir</h3><p>Ürünler, fiyatlar, çalışma saatleri, masa adları, personelin şube görevleri, mutfak kapasitesi, yoğunluk molası ve kampanya taslağı.</p></div></div></section></>}
 {data&&tab==='policies'&&<section className="pc-card"><h2>{selection==='global'?'Global hizmet politikası':'Şubeye özel sınırlar'}</h2><p>Şube politikası global bir kapatmayı aşamaz. Limitlerde düşük olan değer geçerlidir. Bu anahtarlar, yapılandırılmamış ödeme veya kurye servisini açmaz.</p><form onSubmit={e=>{e.preventDefault();commit('policy',{version:data.version,settings:draft});}}>
 {policyFields.map(f=><label className="pc-toggle" key={f.key}><input type="checkbox" checked={draft[f.key]??data.globalSettings[f.key]??true} disabled={blocked||!(f.permission==='ai'?current.canManageAi:current.canManageOperations)} onChange={e=>setDraft(d=>({...d,[f.key]:e.target.checked}))}/><span><strong>{f.label}</strong><small>{f.help}</small><em>Etkin: {data.effective[f.key]?'İzinli':'Durdurulmuş'}{selection!=='global'&&draft[f.key]===undefined?' · Globalden devralınıyor':''}</em></span></label>)}
 <label>Günlük AI işi tavanı<input type="number" min={1} max={50} step={1} disabled={blocked||!current.canManageAi} value={draft.dailyAiLimit??data.globalSettings.dailyAiLimit??50} onChange={e=>setDraft(d=>({...d,dailyAiLimit:Number(e.target.value)}))}/></label><p className="pc-small">Şube başına; sağlayıcının kendi kotası ve bağlantı limiti ayrıca geçerli. Etkin tavan: {data.effective.dailyAiLimit}. Ücretli harcama seçeneği yoktur.</p>{reasonField}<button className="btn primary" disabled={blocked||!canPolicy||reason.trim().length<5}>Politikayı kaydet</button>{selection!=='global'&&current.role==='platform_owner'&&<button type="button" className="btn" disabled={blocked||reason.trim().length<5} onClick={()=>commit('policy',{version:data.version,settings:{}})}>Global politikayı devral</button>}</form></section>}
 {data&&tab==='security'&&<><section className="pc-card"><h2>Masa erişim politikası</h2><p>Varsayılan kodsuz giriş korunur. İstisnai personel katılım onayı yalnız şirket güvenlik yetkisiyle değiştirilebilir. Sipariş kabulü her iki yöntemde de sürer.</p>{data.admission?<form onSubmit={e=>{e.preventDefault();commit('admission',{version:data.admission!.version,mode:admission});}}><label>Masa erişimi<select value={admission} disabled={blocked||!current.canManageSecurity} onChange={e=>setAdmission(e.target.value)}><option value="direct">Kodsuz sipariş · Önerilen</option><option value="staff_approved">İstisnai personel katılım onayı</option></select></label>{reasonField}<button className="btn primary" disabled={blocked||!current.canManageSecurity||reason.trim().length<5}>Güvenlik politikasını kaydet</button></form>:<p>Bu ayarı görmek için bir şube seçin.</p>}</section><section className="pc-card"><h2>Değiştirilemeyen korumalar</h2><p>Şube izolasyonu ve RLS, sunucu fiyat doğrulaması, kuruş hassasiyeti, idempotency, özel Realtime kanalları, gönüllü bahşiş ve görev bazlı personel erişimi korunur. Bu panelden kapatılamaz.</p></section><section className="pc-card"><h2>Kimlik, MFA ve e-posta altyapısı</h2><p>Supabase MFA, sızdırılmış parola koruması, SMTP ve izinli dönüş adresleri ayrı sağlayıcı ayarlarıdır. Bu ekranda kaydetmek bu servisleri değiştirmez; sağlayıcı kontrolü henüz otomatik doğrulanmıyor.</p><a className="btn" href="https://supabase.com/dashboard/project/lrfcqpmjgghodymhnvue/auth/url-configuration" target="_blank" rel="noreferrer">Supabase kimlik ayarları ↗</a></section></>}
 {data&&tab==='team'&&<section className="pc-card"><h2>MenüGO şirket ekibi</h2><p>Restoran personel yetkilerinden bağımsızdır. E-posta doğrulanmış mevcut hesap gerekir; davet e-postası veya parola bu ekrandan gönderilmez. Son platform sahibi kaldırılamaz.</p>{data.members.map(m=><div className="pc-row" key={m.userId}><span><strong>{m.email}</strong><small>{roleNames[m.role]} · {m.active?'Aktif':'Kapalı'}</small></span>{current.canManageMembers&&<button className="btn" disabled={blocked} onClick={()=>setMember({email:m.email,role:m.role,active:m.active,previous:{role:m.role,active:m.active}})}>Düzenle</button>}</div>)}
 {current.canManageMembers&&<form onSubmit={e=>{e.preventDefault();commit('member',member);}}><h3>Şirket yetkisi tanımla / güncelle</h3><label>Doğrulanmış hesap e-postası<input type="email" value={member.email} disabled={blocked} onChange={e=>{const m=data.members.find(m=>m.email.toLowerCase()===e.target.value.toLowerCase());setMember({email:e.target.value,role:m?.role??'auditor',active:m?.active??true,previous:m?{role:m.role,active:m.active}:{}});}} required/></label><label>Şirket rolü<select value={member.role} disabled={blocked} onChange={e=>setMember(m=>({...m,role:e.target.value}))}>{Object.entries(roleNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="pc-check"><input type="checkbox" checked={member.active} disabled={blocked} onChange={e=>setMember(m=>({...m,active:e.target.checked}))}/>Yetki aktif</label>{reasonField}<button className="btn primary" disabled={blocked||reason.trim().length<5}>Şirket yetkisini kaydet</button></form>}</section>}
 {data&&tab==='integrations'&&<><section className="pc-card"><h2>AI sağlayıcıları ve anahtar kasası</h2><p>Ücretsiz model listeleri, gizlilik izinleri, öncelik, bağlantı limitleri ve gerçek bağlantı testi yalnız AI yetkililerindedir. Anahtarlar geri okunmaz.</p>{current.canManageAi?<Link className="btn primary" href="/platform/yapay-zeka">AI kontrol merkezine git</Link>:<span className="pc-badge">AI ayar yetkisi yok</span>}</section><div className="pc-grid">{[['payments_enabled','Online ödeme'],['loyalty_enabled','Sadakat harcama'],['daas_enabled','DaaS kurye'],['sms_enabled','Kampanya SMS']].map(([k,n])=><section className="pc-card" key={k}><h3>{n}</h3><b>{data.features?(data.features[k]?'Veritabanı bayrağı açık':'Kapalı'):'Şube seçin'}</b><p>Sağlayıcı sözleşmesi, kimlik bilgileri ve kabul testi ayrı doğrulanır. Bu ekranda etkinleştirme, para çekme veya otomatik tekrar yok.</p></section>)}</div><section className="pc-card"><h2>WhatsApp / POS / sosyal hesaplar</h2><p>WhatsApp sipariş talebi müşteri tarafından gönderilir; Business API botu değildir. POS, yazıcı ve sosyal hesap otomasyon bağlantıları henüz merkezi sağlayıcı adaptörüyle etkinleştirilmez. İşletmenin telefon, çalışma saatleri ve profil bilgileri restoran panelinde kalır.</p></section></>}
 {data&&tab==='queues'&&<><div className="pc-grid">{Object.entries(data.queues??{}).filter(([k])=>k!=='crmLastRun').map(([k,v])=><Metric key={k} label={metricNames[k]??k} value={String(v??0)}/>)}</div><section className="pc-card"><h2>Tekrar güvenliği</h2><p>Sonuç belirsizken ikinci ödeme, kurye veya model çağrısı otomatik başlatılmaz. Başarısız işleri topluca tekrar gönderme düğmesi yoktur. Kuyruk ayrıntıları müşteri telefonu, adresi ve belge içeriklerini bu merkeze taşımaz.</p><p>Son CRM değerlendirmesi: {date(data.queues?.crmLastRun as string)}.</p><p className="pc-small">Şube sayaçları anlık görüntüdür. Harici worker kalp atışı ve SLA ölçümü bu sürümde doğrulanmıyor.</p></section></>}
 {data&&tab==='privacy'&&<><section className="pc-card"><h2>Veri ve izin sınırları</h2><p>Ücretsiz model seçimi özel veriyi her sağlayıcıya gönderme izni vermez. Yayınlanabilir içerik ve özel belge izinleri AI merkezinde ayrı tutulur. Satış, ödeme ve kampanya izni birbirinden bağımsızdır.</p><p>KVKK/ileti onaylarını kullanıcı adına açma, finans defterini silme, ham müşteri dışa aktarma ve kalıcı veri temizliği bu panelde yoktur.</p></section><section className="pc-card"><h2>Saklama, yedekleme ve kurtarma</h2><p>Kaynak belgelerin mevcut süre sonu ve taslak geri alma kuralları korunur. Bu sürüm saklama sürelerini kısaltmaz, veri silmez veya yeni bir yedek planı başlatmaz.</p><p className="pc-badge">Yedek geri yükleme doğrulaması: henüz bağlı değil</p><p>Supabase veritabanı yedeği ile medya dosyalarının yedeği ayrı kontrol edilmelidir. Servis politikası değişiklikleri, silinmeyen geçmişten önce/sonra incelenebilir.</p></section></>}
 {data&&tab==='audit'&&<><section className="pc-card"><h2>Ayar değişiklikleri · son 60 kayıt</h2>{data.changes.length?data.changes.map(c=><details className="pc-change" key={c.id}><summary>{date(c.createdAt)} · {c.action==='member'?'Şirket yetkisi':c.action==='admission'?'Masa güvenliği':'Hizmet politikası'}</summary><p>{c.reason}</p><small>{c.scope} · Yetkili: {c.actorId}</small><div className="pc-columns"><div><h3>Önce</h3><pre>{JSON.stringify(c.before,null,2)}</pre></div><div><h3>Sonra</h3><pre>{JSON.stringify(c.after,null,2)}</pre></div></div></details>):<p>Henüz şirket ayarı değişikliği yok.</p>}</section><section className="pc-card"><h2>Şirket olayları · son 30 kayıt</h2>{data.audit.map((a,i)=><div className="pc-row" key={i}><span>{a.action}</span><small>{date(a.createdAt)}</small></div>)}</section></>}
 {data&&tab==='runtime'&&<><section className="pc-card"><h2>Alan adları ve sürüm</h2><p>Kaynak sürümü: <strong>{data.runtime?.release??'—'}</strong></p>{data.runtime?.hosts.map(h=><p key={h}>{h}</p>)}<p className="pc-small">Bu liste uygulamanın izinli alan adlarıdır; DNS veya sertifika doğrulaması değildir. DNS, ortam anahtarları ve otomatik dağıtım ayarları altyapı sağlayıcısında yönetilir.</p><a className="btn" href="https://vercel.com/info-64116029s-projects/menugo/settings" target="_blank" rel="noreferrer">Vercel proje ayarları ↗</a></section><section className="pc-card"><h2>Marka ve yayın sınırları</h2><p>Kanonik MenüGO logosu ve platform imzası korunur. Restoran logosu ve marka içeriği kendi işletme profilinde yönetilir. AI üretimiyle resmî logo değiştirme ve incelemesiz içerik yayımlama kapalıdır.</p></section></>}
 </div></div></main>;
}
const metricNames:Record<string,string>={branches:'İşletme şubesi',products:'Katalog kaydı',approvedPrices:'Onaylı fiyat',tables:'Aktif masa',staff:'Şube personeli',aiRoutes:'AI bağlantısı',expiredAiAttestations:'Süresi geçmiş ücretsiz hesap beyanı',courierAccounts:'Kurye hesabı',aiToday:'Bugünkü AI işi',aiUnknown:'Belirsiz AI işi',paymentUnknown:'Belirsiz ödeme',courierDead:'İnceleme bekleyen kurye işi',courierPending:'Bekleyen kurye işi',smsUnknown:'Belirsiz SMS'};
function Metric({label,value}:{label:string;value:string}){return <section className="pc-metric"><span>{label}</span><strong>{value}</strong></section>;}
