'use client';
import {useEffect,useState} from 'react';import {api,explain} from './transport';import {Card} from './Shell';
export function ServiceInsights({role}:{role:string}){const[data,setData]=useState<any>(null),[error,setError]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 const load=()=>api('/api/merchant/service-dashboard').then(setData).catch(e=>setError(explain(e)));
 useEffect(()=>{let alive=true;const refresh=()=>api('/api/merchant/service-dashboard').then(v=>{if(alive)setData(v);}).catch(()=>{});void refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},8000);return()=>{alive=false;clearInterval(t);};},[]);
 async function end(v:any){if(!confirm('Misafir '+v.seat+' oturumu sonlandırılsın ve gönderilmemiş seçimleri temizlensin? Gönderilmiş siparişler korunur.'))return;setBusy(true);try{await api('/api/merchant/end-guest',{checkId:v.checkId,guestId:v.id});await load();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 async function decide(id:string,approve:boolean){setBusy(true);setError('');try{await api('/api/merchant/decide-cancellation',{id,approve,note:notes[id]});await load();}catch(e){setError(explain(e));}finally{setBusy(false);}}
 if(!data)return null;return <section className="service-insights"><div className="service-summary" aria-live="polite"><span><b>{data.summary.waitingAcceptance}</b> Kabul bekliyor</span><span><b>{data.summary.preparing}</b> Hazırlanıyor</span><span><b>{data.summary.ready}</b> Servise hazır</span><span><b>{data.guestVisits}</b> Misafir ziyareti</span></div>{data.summary.overdue>0&&<div role="status" className="alert"><strong>{data.summary.overdue} sipariş 3 dakikadan uzun süredir kabul bekliyor.</strong> Mutfak ve servis ekranlarını kontrol edin.</div>}{error&&<p role="alert">{error}</p>}{data.cancellations.length>0&&<Card><h2>Müşteri iptal talepleri</h2><p>Talep, siparişi kendiliğinden iptal etmez. Karar ve gerekçe kaydedilir.</p>{data.cancellations.map((r:any)=><article className="service-request" key={r.id}><strong>{r.table} · #{r.orderId.slice(-6)}</strong><p>{r.reason}</p>{role!=='kitchen'&&<><label>İşletme kararı / gerekçe<input maxLength={300} value={notes[r.id]??''} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))}/></label><button className="btn" disabled={busy||!notes[r.id]?.trim()} onClick={()=>void decide(r.id,false)}>Talebi reddet</button><button className="btn primary" disabled={busy||!notes[r.id]?.trim()} onClick={()=>void decide(r.id,true)}>İptali onayla</button></>}</article>)}</Card>}{role!=='kitchen'&&data.visits?.some((v:any)=>v.active)&&<details className="guest-staff-visits"><summary>Açık masaların misafir oturumları</summary>{data.visits.filter((v:any)=>v.active).map((v:any)=><div key={v.id} className="list-row"><span>{v.table} · Misafir {v.seat}</span><button className="btn" disabled={busy} onClick={()=>void end(v)}>Oturumu sonlandır</button></div>)}</details>}</section>;}
export function ServiceControls(){const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{api('/api/merchant/service-control').then(setData).catch(e=>setError(explain(e)));},[]);if(!data)return error?<p>{error}</p>:null;return <Card><h2>Mutfak kapasitesi ve hazırlık süresi</h2><p>Yoğunluk sınırı dolduğunda yeni sipariş alınmaz; mevcut siparişler silinmez. Boş kapasite alanı sınırsız kabul anlamına gelir.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{setData(await api('/api/merchant/service-control',{version:data.version,capacity:data.capacity??'',minutes:data.minutes??''}));setError('Ayarlar kaydedildi.');}catch(e){setError(explain(e));}finally{setBusy(false);}}}><div className="form-grid"><label>Aynı anda kabul edilebilecek sipariş<input type="number" min="1" max="300" value={data.capacity??''} onChange={e=>setData({...data,capacity:e.target.value})}/></label><label>Tahmini hazırlık süresi (dakika)<input type="number" min="1" max="180" value={data.minutes??''} onChange={e=>setData({...data,minutes:e.target.value})}/></label></div><p className="helper">Süre, personelin planlama hedefidir; doğrulanmış teslimat saati garantisi değildir.</p><button className="btn primary" disabled={busy}>Kapasiteyi kaydet</button>{error&&<p role="status">{error}</p>}</form></Card>;}

export function TableOrderingPolicy(){
 const[mode,setMode]=useState('direct'),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;api('/api/merchant/table-policy').then(v=>{if(alive){setMode(v.mode);setLoaded(true);}}).catch(e=>{if(alive)setMessage(explain(e));});return()=>{alive=false;};},[]);
 return <Card><h2>Müşteri sipariş akışı</h2><p>Önerilen: müşteri QR’den doğrudan sipariş verir. Personel yalnızca gelen siparişi kabul eder.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await api('/api/merchant/table-policy',{mode});setMessage('Sipariş akışı kaydedildi.');}catch(e){setMessage(explain(e));}finally{setBusy(false);}}}><label>Masa erişimi<select value={mode} disabled={!loaded||busy} onChange={e=>setMode(e.target.value)}><option value="direct">Kodsuz sipariş — önerilen</option><option value="staff_approved">İstisnai güvenlik: personel katılım onayı</option></select></label><p className="helper">Sipariş kabulü her iki yöntemde de zorunludur. Kodsuz erişim, başka müşterilerin siparişlerini veya ödeme bilgilerini göstermez.</p><button className="btn primary" disabled={!loaded||busy}>Akışı kaydet</button>{message&&<p role="status">{message}</p>}</form></Card>;
}
