'use client';
import {useEffect,useState} from 'react';
import {api,explain,money} from './transport';
import {Card} from './Shell';
import {csvCell} from '@/lib/menu-discovery';
export function ServiceAvailability(){const[data,setData]=useState<any>(null);useEffect(()=>{let alive=true;const load=()=>api('/api/merchant/availability').then(v=>{if(alive)setData(v);}).catch(()=>{});void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>{alive=false;clearInterval(t);};},[]);
 if(!data||(!data.paused&&!data.estimatedMinutes))return null;
 return <div className={'service-availability '+(data.paused?'is-paused':'')} role="status">{data.paused?<><strong>Yeni masa siparişlerine kısa bir ara verdik.</strong><span>{new Date(data.pausedUntil).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'})} itibarıyla tekrar kontrol edebilirsiniz. Gönderilmiş siparişleriniz devam eder; personelimizden yardım alabilirsiniz.</span></>:<><strong>Tahmini hazırlık: {data.estimatedMinutes} dakika</strong><span>İşletmenin planlama süresidir; sipariş ve yoğunluğa göre değişebilir.</span></>}</div>;
}
export function BusyMode(){const[data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await api('/api/merchant/pause'));}useEffect(()=>{void load().catch(e=>setMessage(explain(e)));},[]);
 async function change(minutes:number){if(!data)return;setBusy(true);setMessage('');try{setData(await api('/api/merchant/pause',{minutes,version:data.version}));setMessage(minutes?'Yeni sipariş kabulü süreli durduruldu. Mevcut siparişler etkilenmedi.':'Süreli duraklatma kaldırıldı.');}catch(e){setMessage(explain(e));await load().catch(()=>{});}finally{setBusy(false);}}
 return <Card><h2>Yoğunluk molası</h2><p>Yalnız yeni masa siparişlerini 15, 30 veya 60 dakika durdurun. Süre dolunca kısıt kendiliğinden biter; genel sipariş ayarınızı değiştirmez.</p>{data?.paused&&<p role="status">Mola bitişi: {new Date(data.pausedUntil).toLocaleTimeString('tr-TR',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit'})}</p>}<div className="experience-actions">{[15,30,60].map(n=><button className="btn" disabled={busy||!data} key={n} onClick={()=>void change(n)}>{n} dakika ara ver</button>)}<button className="btn primary" disabled={busy||!data} onClick={()=>void change(0)}>Sipariş kabulüne dön</button></div>{message&&<p role="status">{message}</p>}</Card>;
}
export function VisitFeedback({checkId,guestId,disabled=false}:{checkId:string;guestId:string;disabled?:boolean}){
 const[data,setData]=useState<any>(null),[rating,setRating]=useState(0),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[command,setCommand]=useState<any>(null);
 const endpoint='/api/guest/'+checkId+'/feedback';const key='menugo:feedback:'+checkId+':'+guestId;
 useEffect(()=>{let alive=true;void api(endpoint).then(v=>{if(alive)setData(v);}).catch(()=>{});try{const c=JSON.parse(sessionStorage.getItem(key)||'null');if(c&&typeof c.operationId==='string'&&/^[0-9a-f-]{36}$/i.test(c.operationId)&&Number.isInteger(c.rating)&&c.rating>=1&&c.rating<=5&&typeof c.comment==='string'&&c.comment.length<=500){setCommand(c);setRating(c.rating);setComment(c.comment);}}catch{}return()=>{alive=false;};},[endpoint,key]);
 if(!data?.eligible&&!data?.submitted)return null;
 if(data?.submitted)return <section className="visit-feedback"><h3>Görüşünüz için teşekkür ederiz.</h3><p>Geri bildiriminiz işletmeye iletildi.</p></section>;
 async function send(){setBusy(true);setNotice('');const c=command??{operationId:crypto.randomUUID(),rating,comment:comment.trim()};try{sessionStorage.setItem(key,JSON.stringify(c));setCommand(c);const v=await api(endpoint,c);setData(v);sessionStorage.removeItem(key);setCommand(null);}catch(e){setNotice(explain(e));try{const v=await api(endpoint);setData(v);if(v.submitted){sessionStorage.removeItem(key);setCommand(null);}}catch{}}finally{setBusy(false);}}
 return <section className="visit-feedback"><h3>Deneyiminiz nasıldı?</h3><p>Yalnız bu ziyaretinize ait görüşünüz işletmeye iletilir. Üyelik gerekmez; yanıtınız herkese açık yayımlanmaz.</p><div className="feedback-stars" role="group" aria-label="Deneyim puanı">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={n+' yıldız'} aria-pressed={rating===n} disabled={busy||disabled||!!command} onClick={()=>setRating(n)}>{n<=rating?'★':'☆'}<small>{n}</small></button>)}</div><label>Görüşünüz (isteğe bağlı)<textarea maxLength={500} rows={3} value={comment} disabled={busy||disabled||!!command} onChange={e=>setComment(e.target.value)} placeholder="Telefon, adres veya ödeme bilgisi yazmayın."/></label><button className="btn primary" disabled={busy||disabled||!rating} onClick={()=>void send()}>{command?'Aynı geri bildirimi doğrula':'Görüşümü gönder'}</button>{notice&&<p role="status">{notice}</p>}</section>;
}
export function FeedbackInbox(){const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=()=>api('/api/merchant/feedback').then(setData);useEffect(()=>{void load().catch(e=>setError(explain(e)));},[]);
 return <Card><div className="section-heading"><h2>Müşteri görüşleri</h2><button className="btn" disabled={busy} onClick={()=>void load().catch(e=>setError(explain(e)))}>Yenile</button></div><p>Son 30 gün · En yeni 200 görüş. Yalnız hizmet verilen ziyaretlerden gelir; Google değerlendirmesi veya pazarlama izni değildir.</p>{!data?<p>{error||'Yükleniyor…'}</p>:!data.rows.length?<p>Henüz ziyaret geri bildirimi yok.</p>:data.rows.map((r:any)=><article className="feedback-entry" key={r.id}><header><strong>{r.rating}/5 · {r.table??'Masa'}</strong><time>{new Date(r.createdAt).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}</time></header><p>{r.comment||'Yorum eklenmedi.'}</p>{r.reviewed?<small>İncelendi</small>:<button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{setData(await api('/api/merchant/feedback',{id:r.id}));}catch(e){setError(explain(e));}finally{setBusy(false);}}}>İncelendi olarak işaretle</button>}</article>)}{error&&<p role="alert">{error}</p>}</Card>;
}
export function DailyServiceReport(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const[day,setDay]=useState(today),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setData(null);setError('');api('/api/merchant/daily-report?day='+day).then(v=>{if(alive)setData(v);}).catch(e=>{if(alive)setError(explain(e));});return()=>{alive=false;};},[day]);
 function download(){if(!data)return;const rows=[['Gün',data.day],['Saat dilimi',data.timezone],['Sipariş sayısı',data.orderCount],['Kabul edilmiş sipariş tutarı (kuruş)',data.acceptedOrderMinor],['Kabul bekleyen tutar (kuruş)',data.waitingOrderMinor],['İptal borç tutarı (kuruş)',data.voidedOrderMinor],['Nakit kaydı (kuruş)',data.cashMinor],['Harici POS kaydı (kuruş)',data.externalPosMinor],['Kasa kaydı toplamı (kuruş)',data.collectedMinor],[],['Ürün','Adet','Sipariş tutarı (kuruş)'],...data.topProducts.map((p:any)=>[p.name,p.quantity,p.netMinor])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map((r:any[])=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='menugo-operasyon-'+data.day+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Card><div className="section-heading"><h2>Günlük işletme özeti</h2><button className="btn" disabled={!data} onClick={download}>CSV indir</button></div><label>Rapor günü<input type="date" max={today} value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><p>İstanbul saati 00.00–24.00. Sipariş değerleri seçilen gün gönderilen siparişlerin güncel durumudur; kasa kayıtları tahsilatın kaydedildiği güne aittir. Birbirinden farklı olabilir.</p>{error&&<p role="alert">{error}</p>}{data?<><div className="experience-metrics">{[['Kabul edilen sipariş',data.acceptedCount+' / '+data.orderCount],['Sipariş tutarı',money(data.acceptedOrderMinor)],['Kabul bekleyen',money(data.waitingOrderMinor)],['Kasa kaydı toplamı',money(data.collectedMinor)],['Nakit',money(data.cashMinor)],['Harici POS',money(data.externalPosMinor)]].map(([n,v])=><div key={n}><span>{n}</span><strong>{v}</strong></div>)}</div><p>{data.cancelledCount} iptal sipariş · {data.receiptCount} kasa kaydı · İptal edilen borç: {money(data.voidedOrderMinor)}</p><h3>En çok sipariş verilen ürünler</h3>{!data.topProducts.length?<p>Bu gün için kabul edilmiş ürün kaydı yok.</p>:data.topProducts.map((p:any)=><div className="list-row" key={p.name}><strong>{p.name}</strong><span>{p.quantity} adet</span><span>{money(p.netMinor)}</span></div>)}<small>Mali belge, kâr hesabı veya banka mutabakatı değildir. İade ve online PSP tahsilatı bu kasa raporuna dahil değildir.</small></>:!error&&<p>Rapor hazırlanıyor…</p>}</Card>;
}
