'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Card,Empty} from './Shell';
import {costRecipe,decimalToScaled,type Ingredient} from '@/src/studio/operations';
import {readCostLedgerCommand,type CostLedgerCommand,type PurchasePostCommand,type RecipeSaveCommand} from '@/src/studio/cost-ledger';

type Purchase={id:string;jobId:string;invoiceNumber:string|null;invoiceDate:string|null;currency:'TRY';totalMinor:string;postedAt:string;lines:{lineNo:number;name:string;quantityText:string;unitText:string;netMinor:string;taxMinor:string;grossMinor:string;page:number;sourceText:string}[]};
type Recipe={id:string;productId:string;productName:string;name:string;version:string;portions:number;overheadMinor:string;totalMinor:string;currency:'TRY';costBasis:'human-verified-input';createdAt:string;ingredients:{lineNo:number;name:string;unit:'g'|'ml'|'piece';packQuantity:string;packCostMinor:string;recipeQuantity:string;edibleYieldBps:number}[]};
type Product={id:string;name:string};
type Ledger={scopeKey:string;purchases:Purchase[];recipes:Recipe[];catalogue:Product[]};
type RecipeLine={id:string;name:string;unit:'g'|'ml'|'piece';packQuantity:string;packCost:string;used:string;yield:string};
class RequestError extends Error{constructor(public code:string,public status:number){super(code);}}
const ERRORS:Record<string,string>={INVALID_COST_INPUT:'Maliyet kaydı doğrulanamadı. Alanları yeniden kontrol edin.',IDEMPOTENCY_CONFLICT:'Bekleyen işlem ile mevcut form uyuşmuyor. Yeni kayıt oluşturulmadı.',APPROVED_INVOICE_REQUIRED:'Yalnız kaynakla karşılaştırılıp onaylanmış fatura taslağı satın alma kaydına alınabilir.',STUDIO_REVISION_CHANGED:'Fatura taslağı onaydan sonra değişmiş. Güncel taslağı yeniden inceleyin.',INVOICE_RECONCILIATION_REQUIRED:'Fatura satırları ve toplamı eksiksiz uyuşmadan satın alma kaydı oluşturulmaz.',PURCHASE_SOURCE_CONFLICT:'Bu faturanın daha önce kaydedilen kaynak kanıtı değişmiş. Kayıt değiştirilmedi.',PRODUCT_NOT_FOUND:'Ürün artık bu şubede bulunmuyor.',MANAGER_REQUIRED:'Bu kayıt için işletme sahibi veya yönetici yetkisi gerekiyor.'};
const wire=(command:CostLedgerCommand)=>({action:command.action,...command.payload});
async function request(command?:CostLedgerCommand){const r=await fetch('/api/studio/cost-ledger',{method:command?'POST':'GET',headers:command?{'Content-Type':'application/json'}:{},body:command?JSON.stringify(wire(command)):undefined,credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)});let v:any={};try{v=await r.json();}catch{}if(!r.ok)throw new RequestError(v.error?.code||'REQUEST_FAILED',r.status);return v;}
function explain(e:unknown){return e instanceof RequestError?(ERRORS[e.code]||'Kayıt tamamlanamadı. Mevcut menü, fiyat ve stok değiştirilmedi.'):'Yanıt doğrulanamadı. Bekleyen işlem aynı kimlikle tekrar kontrol edilebilir.';}
function money(v:string|undefined|null){if(v==null)return '—';const n=BigInt(v);return `${(n/100n).toLocaleString('tr-TR')},${String(n%100n).padStart(2,'0')} ₺`;}
function validLedger(v:any):v is Ledger{return !!v&&typeof v.scopeKey==='string'&&/^([a-f0-9-]{36}:){2}[a-f0-9-]{36}$/i.test(v.scopeKey)&&Array.isArray(v.purchases)&&Array.isArray(v.recipes)&&Array.isArray(v.catalogue);}
function clearOnDefinitive(e:unknown){return e instanceof RequestError&&[400,401,403,404,409,410,422].includes(e.status);}

export function InvoicePurchasePosting({job}:{job:any}){
 const [ledger,setLedger]=useState<Ledger|null>(null),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState<PurchasePostCommand|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),mounted=useRef(false),key=useRef<string|null>(null);
 async function refresh(){try{const v=await request();if(!mounted.current)return;if(!validLedger(v))throw Error('INVALID_LEDGER');setLedger(v);const k=`menugo-cost-invoice:${v.scopeKey}:${job.id}`;if(key.current!==k){key.current=k;setPending(null);try{const raw=sessionStorage.getItem(k);if(raw){const parsed=readCostLedgerCommand(JSON.parse(raw));if(parsed.action!=='post-invoice'||parsed.payload.jobId!==job.id||parsed.payload.revision!==String(job.revision))throw Error('STALE');setPending(parsed);}}catch{sessionStorage.removeItem(k);}}}catch(e){if(mounted.current)setError(explain(e));}}
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;};},[job.id,job.revision]);
 const existing=ledger?.purchases.find(x=>x.jobId===job.id);
 function setIntent(c:PurchasePostCommand|null){if(key.current){try{if(c)sessionStorage.setItem(key.current,JSON.stringify(wire(c)));else sessionStorage.removeItem(key.current);}catch{if(c){setError('Güvenli tekrar kaydı oluşturulamadı; satın alma kaydı gönderilmedi.');return false;}}}setPending(c);return true;}
 async function send(c:PurchasePostCommand){if(lock.current)return;if(!setIntent(c))return;lock.current=true;setBusy(true);setError('');setNotice('');try{const v=await request(c);if(!v||v.posted!==true||typeof v.purchaseId!=='string'||typeof v.totalMinor!=='string')throw Error('INVALID_RECEIPT');setIntent(null);setConfirmed(false);setNotice(v.alreadyPosted?'Bu fatura daha önce onaylı satın alma defterine kaydedilmiş.':'Onaylı fatura satın alma defterine kaydedildi. Stok, muhasebe ve satış fiyatı otomatik değiştirilmedi.');await refresh();}catch(e){if(clearOnDefinitive(e))setIntent(null);setError(explain(e));}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 if(job.kind!=='invoice'||job.state!=='approved')return null;
 return <section className="studio-cost-post"><h4>Onaylı satın alma kaydı</h4>{error&&<p className="notice" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {existing?<p className="notice">Bu fatura satın alma defterinde kayıtlı: <strong>{money(existing.totalMinor)}</strong>. Kayıt değiştirilemez; stok veya muhasebe hareketi oluşturulmadı.</p>:pending?<div className="notice"><strong>Satın alma kaydının sonucu belirsiz.</strong><p>Aynı işlem kimliğiyle kontrol edilir; ikinci satın alma kaydı oluşturulmaz.</p><button className="btn" disabled={busy} onClick={()=>void send(pending)}>Aynı satın alma işlemini kontrol et</button></div>:<><p>Faturadaki tutarlar sunucuda yeniden uzlaştırılır. Yalnız onaylı taslağın değişmez kanıtı kaydedilir; istemci tutar gönderemez.</p><label className="studio-checkbox"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Faturayı kaynak belgeyle karşılaştırdım; satırları ve toplamı satın alma defterine kaydet.</label><button className="btn primary" disabled={busy||!confirmed} onClick={()=>void send({action:'post-invoice',payload:{operationId:crypto.randomUUID(),jobId:job.id,revision:String(job.revision),confirmed:true}})}>Onaylı satın alma kaydına işle</button></>}
 </section>;
}

export function StudioCostLedger({demo=false}:{demo?:boolean}){
 const [ledger,setLedger]=useState<Ledger|null>(null),[product,setProduct]=useState(''),[name,setName]=useState(''),[lines,setLines]=useState<RecipeLine[]>([{id:'line-1',name:'',unit:'g',packQuantity:'',packCost:'',used:'',yield:'10000'}]),[portions,setPortions]=useState('1'),[overhead,setOverhead]=useState('0'),[result,setResult]=useState<any>(null),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState<RecipeSaveCommand|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const mounted=useRef(false),lock=useRef(false),key=useRef<string|null>(null);
 async function load(){if(demo)return;try{const v=await request();if(!mounted.current)return;if(!validLedger(v))throw Error('INVALID_LEDGER');setLedger(v);setProduct(p=>p||v.catalogue[0]?.id||'');const k=`menugo-cost-recipe:${v.scopeKey}`;if(key.current!==k){key.current=k;setPending(null);try{const raw=sessionStorage.getItem(k);if(raw){const parsed=readCostLedgerCommand(JSON.parse(raw));if(parsed.action!=='save-recipe')throw Error('INVALID');setPending(parsed);}}catch{sessionStorage.removeItem(k);}}}catch(e){if(mounted.current)setError(explain(e));}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[demo]);
 function update(id:string,k:keyof RecipeLine,value:string){setResult(null);setConfirmed(false);setLines(old=>old.map(x=>x.id===id?{...x,[k]:value}:x));}
 function payload(operationId:string):RecipeSaveCommand{const ingredients=lines.map(l=>({name:l.name.trim(),unit:l.unit,packQuantity:l.packQuantity,packCostMinor:decimalToScaled(l.packCost).toString(),recipeQuantity:l.used,edibleYieldBps:Number(l.yield)}));return readCostLedgerCommand({action:'save-recipe',operationId,productId:product,name:name.trim(),portions:Number(portions),overheadMinor:decimalToScaled(overhead).toString(),ingredients,confirmed:true}) as RecipeSaveCommand;}
 function calculate(e:FormEvent){e.preventDefault();setError('');setNotice('');setConfirmed(false);try{const data=lines.map(l=>({id:l.id,unit:l.unit as Ingredient['unit'],packQuantity:l.packQuantity,packCostMinor:decimalToScaled(l.packCost).toString(),recipeQuantity:l.used,edibleYieldBps:Number(l.yield)}));if(!name.trim()||!product||lines.some(l=>!l.name.trim()))throw Error('INPUT');setResult(costRecipe(data,Number(portions),decimalToScaled(overhead).toString()));}catch{setResult(null);setError('Ürün, reçete adı ve malzeme adlarını doldurun. Miktarlar tam sayı g / ml / adet; fiyatlar en fazla iki ondalık basamak; randıman 1–10000 olmalıdır.');}}
 function setIntent(c:RecipeSaveCommand|null){if(key.current){try{if(c)sessionStorage.setItem(key.current,JSON.stringify(wire(c)));else sessionStorage.removeItem(key.current);}catch{if(c){setError('Güvenli tekrar kaydı oluşturulamadı; reçete sürümü gönderilmedi.');return false;}}}setPending(c);return true;}
 async function save(c:RecipeSaveCommand){if(lock.current)return;if(!setIntent(c))return;lock.current=true;setBusy(true);setError('');setNotice('');try{const expected=costRecipe(c.payload.ingredients.map((x,i)=>({id:String(i),unit:x.unit,packQuantity:x.packQuantity,packCostMinor:x.packCostMinor,recipeQuantity:x.recipeQuantity,edibleYieldBps:x.edibleYieldBps})),c.payload.portions,c.payload.overheadMinor);const v=await request(c);if(!v||v.saved!==true||typeof v.recipeId!=='string'||v.totalMinor!==expected.totalMinor||typeof v.version!=='string')throw Error('INVALID_RECEIPT');setIntent(null);setConfirmed(false);setNotice(`Reçete maliyeti sürüm ${v.version} olarak kaydedildi. Menü fiyatı, stok ve muhasebe kayıtları değiştirilmedi.`);await load();}catch(e){if(clearOnDefinitive(e))setIntent(null);setError(explain(e));}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 if(demo)return <Card><Empty title="Gerçek işletme oturumu gerekli" description="Maliyet hesaplayıcıyı kullanabilirsiniz; kalıcı satın alma ve reçete kayıtları gerçek işletme oturumunda açılır."/></Card>;
 return <div className="studio-cost-ledger"><Card><h3>Reçetenizin gerçek maliyetini hesaplayın</h3><p>Aynı vergi esasındaki doğrulanmış alış tutarlarını kullanın. Hesap kuruş hassasiyetinde yapılır; kaydetmek stok, menü fiyatı veya muhasebe hareketi oluşturmaz.</p>{error&&<p role="alert" className="notice">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{pending&&<div className="notice"><strong>Reçete kaydının sonucu belirsiz.</strong><p>Aynı işlem kimliği ve aynı maliyet girdileriyle doğrulanır; ikinci sürüm oluşturulmaz.</p><button className="btn" disabled={busy} onClick={()=>void save(pending)}>Aynı reçete kaydını kontrol et</button></div>}
 <form onSubmit={calculate}><label>Menü ürünü<select required disabled={busy||!!pending} value={product} onChange={e=>{setProduct(e.target.value);setResult(null);setConfirmed(false);}}><option value="">Ürün seçin</option>{ledger?.catalogue.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Reçete adı<input required maxLength={120} disabled={busy||!!pending} value={name} onChange={e=>{setName(e.target.value);setResult(null);setConfirmed(false);}} placeholder="Örn. Standart porsiyon"/></label>
 {lines.map((l,i)=><div className="recipe-row" key={l.id}><strong>Malzeme {i+1}</strong><label>Malzeme adı<input required maxLength={160} disabled={busy||!!pending} value={l.name} onChange={e=>update(l.id,'name',e.target.value)}/></label><label>Birim<select disabled={busy||!!pending} value={l.unit} onChange={e=>update(l.id,'unit',e.target.value)}><option value="g">Gram</option><option value="ml">Mililitre</option><option value="piece">Adet</option></select></label><label>Paket miktarı<input required inputMode="numeric" disabled={busy||!!pending} value={l.packQuantity} onChange={e=>update(l.id,'packQuantity',e.target.value)}/></label><label>Paket maliyeti (TL)<input required inputMode="decimal" disabled={busy||!!pending} value={l.packCost} onChange={e=>update(l.id,'packCost',e.target.value)}/></label><label>Reçetede kullanılan<input required inputMode="numeric" disabled={busy||!!pending} value={l.used} onChange={e=>update(l.id,'used',e.target.value)}/></label><label>Randıman (10000 = %100)<input required inputMode="numeric" disabled={busy||!!pending} value={l.yield} onChange={e=>update(l.id,'yield',e.target.value)}/></label><button type="button" className="btn" disabled={busy||!!pending||lines.length===1} onClick={()=>{setLines(v=>v.filter(x=>x.id!==l.id));setResult(null);setConfirmed(false);}}>Kaldır</button></div>)}
 <button type="button" className="btn" disabled={busy||!!pending||lines.length>=100} onClick={()=>{setLines(v=>[...v,{id:crypto.randomUUID(),name:'',unit:'g',packQuantity:'',packCost:'',used:'',yield:'10000'}]);setResult(null);setConfirmed(false);}}>Malzeme ekle</button><div className="inline-form"><label>Porsiyon sayısı<input required type="number" min="1" max="1000" disabled={busy||!!pending} value={portions} onChange={e=>{setPortions(e.target.value);setResult(null);setConfirmed(false);}}/></label><label>Reçete başına diğer maliyet (TL)<input required inputMode="decimal" disabled={busy||!!pending} value={overhead} onChange={e=>{setOverhead(e.target.value);setResult(null);setConfirmed(false);}}/></label></div><button className="btn primary" disabled={busy||!!pending}>Maliyeti hesapla</button></form>
 {result&&<div className="studio-cost-result"><strong>Reçete toplamı: {money(result.totalMinor)}</strong><p>Porsiyon: {money(result.portionCostsMinor.at(-1))}–{money(result.portionCostsMinor[0])}</p><small>Kuruş farkları ilk porsiyonlara dağıtıldı. Satış fiyatı veya kâr tahmini oluşturulmadı.</small><label className="studio-checkbox"><input type="checkbox" checked={confirmed} disabled={busy||!!pending} onChange={e=>setConfirmed(e.target.checked)}/>Bu miktar ve maliyet girdilerini doğruladım; yeni, değişmez bir reçete maliyet sürümü kaydet.</label><button type="button" className="btn primary" disabled={busy||!!pending||!confirmed} onClick={()=>{try{void save(payload(crypto.randomUUID()));}catch(e){setError(explain(e));}}}>Reçete sürümünü kaydet</button></div>}
 </Card><Card><div className="section-heading"><h3>Maliyet geçmişi</h3><button className="btn" disabled={busy} onClick={()=>void load()}>Geçmişi yenile</button></div><h4>Satın alma kayıtları</h4>{ledger?.purchases.length?ledger.purchases.map(p=><details key={p.id} className="studio-cost-history"><summary>{p.invoiceNumber||'Fatura'} · {money(p.totalMinor)}</summary><p>{p.invoiceDate||'Tarih yok'} · {new Date(p.postedAt).toLocaleString('tr-TR')}</p>{p.lines.map(l=><p key={l.lineNo}>{l.name}: {money(l.grossMinor)} <small>· kaynak sayfa {l.page}</small></p>)}</details>):<p className="helper">Henüz onaylı satın alma kaydı yok.</p>}<h4>Reçete sürümleri</h4>{ledger?.recipes.length?ledger.recipes.map(r=><details key={r.id} className="studio-cost-history"><summary>{r.productName} · {r.name} · sürüm {r.version}</summary><p>{money(r.totalMinor)} / {r.portions} porsiyon · {new Date(r.createdAt).toLocaleString('tr-TR')}</p>{r.ingredients.map(i=><p key={i.lineNo}>{i.name}: {i.recipeQuantity} {i.unit} · paket {money(i.packCostMinor)}</p>)}</details>):<p className="helper">Henüz kaydedilmiş reçete maliyet sürümü yok.</p>}</Card></div>;
}