'use client';
import {useRef,useState} from 'react';
import {api,explain,money} from './transport';

type DraftLine={productId:string;productName:string;quantity:number;option:string|null;unitPriceMinor:string;lineTotalMinor:string};
type DraftIssue={productName:string;code:string;detail:string};
type Draft={transcript:string;lines:DraftLine[];issues:DraftIssue[];totalMinor:string;reviewRequired:true;autoSubmitted:false};
type RecognitionLike={lang:string;interimResults:boolean;continuous:boolean;maxAlternatives:number;start:()=>void;stop:()=>void;onresult:((e:any)=>void)|null;onerror:((e:any)=>void)|null;onend:(()=>void)|null};
type RecognitionCtor=new()=>RecognitionLike;

export function VoiceOrderDraft({checkId,disabled,onApply}:{checkId:string;disabled:boolean;onApply:(line:DraftLine)=>Promise<void>}){
 const[open,setOpen]=useState(false),[transcript,setTranscript]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[listening,setListening]=useState(false),[error,setError]=useState(''),[applied,setApplied]=useState<Record<string,boolean>>({});const recognition=useRef<RecognitionLike|null>(null);
 async function createDraft(value=transcript){const text=value.trim();if(!text)return;setBusy(true);setError('');setDraft(null);try{setDraft(await api('/api/guest/'+checkId+'/voice-draft',{transcript:text}));}catch(e){setError(explain(e));}finally{setBusy(false);}}
 function microphone(){setError('');const w=window as any;const Ctor=(w.SpeechRecognition||w.webkitSpeechRecognition) as RecognitionCtor|undefined;if(!Ctor){setError('Bu tarayıcı doğrudan ses tanımayı desteklemiyor. Siparişinizi aşağıdaki alana yazabilirsiniz.');return;}try{const r=new Ctor();recognition.current=r;r.lang='tr-TR';r.interimResults=false;r.continuous=false;r.maxAlternatives=1;r.onresult=e=>{const text=String(e?.results?.[0]?.[0]?.transcript??'').trim();if(!text)return;setTranscript(text);void createDraft(text);};r.onerror=()=>setError('Ses anlaşılamadı. Tekrar deneyebilir veya siparişinizi yazabilirsiniz.');r.onend=()=>{setListening(false);recognition.current=null;};setListening(true);r.start();}catch{setListening(false);setError('Mikrofon başlatılamadı. Tarayıcı kamera/mikrofon izinlerini kontrol edin veya siparişinizi yazın.');}}
 async function apply(line:DraftLine){const key=line.productId+'|'+(line.option??'');setBusy(true);setError('');try{await onApply(line);setApplied(v=>({...v,[key]:true}));}catch(e){setError(explain(e));}finally{setBusy(false);}}
 function reset(){try{recognition.current?.stop();}catch{}recognition.current=null;setListening(false);setTranscript('');setDraft(null);setError('');setApplied({});}
 return <section className="guest-card" aria-label="Sesli sipariş taslağı"><button className="btn" type="button" disabled={disabled} onClick={()=>{setOpen(v=>!v);if(open)reset();}}>{open?'Sesli taslağı kapat':'🎙️ Sesle seçim oluştur'}</button>{open&&<div><h2>Sesli seçim taslağı</h2><p>Söyledikleriniz yalnızca taslak oluşturur. Hiçbir ürün kendiliğinden sepete veya siparişe eklenmez.</p><div className="guest-assist"><button type="button" className="btn" disabled={disabled||busy||listening} onClick={microphone}>{listening?'Dinleniyor…':'🎙️ Konuşmaya başla'}</button>{listening&&<button type="button" className="btn" onClick={()=>recognition.current?.stop()}>Durdur</button>}</div><label className="guest-search"><span>⌕</span><input aria-label="Sesli sipariş metni" value={transcript} maxLength={1000} onChange={e=>setTranscript(e.target.value)} placeholder="Örn. iki çay ve bir kaşarlı tost"/></label><button type="button" className="guest-primary full" disabled={disabled||busy||!transcript.trim()} onClick={()=>void createDraft()}>{busy?'Hazırlanıyor…':'Taslağı kontrol et'}</button>{error&&<p className="notice" role="status">{error}</p>}{draft&&<div aria-live="polite"><p className="helper">Katalogdaki güncel ve onaylı fiyatlar kullanılır. Seçenekli ürünlerde seçenek net değilse sistem ürünü eklemez.</p>{draft.lines.length?draft.lines.map(line=>{const key=line.productId+'|'+(line.option??'');return <div className="guest-line" key={key}><div><strong>{line.quantity} × {line.productName}</strong><small>{line.option?line.option+' · ':''}{money(line.unitPriceMinor)} · toplam {money(line.lineTotalMinor)}</small></div><button className="btn" type="button" disabled={disabled||busy||applied[key]} onClick={()=>void apply(line)}>{applied[key]?'Seçimlerimde':'Seçimlerime ekle'}</button></div>}):<p className="guest-empty">Siparişe açık bir ürün eşleşmedi.</p>}{draft.issues.map((issue,i)=><p className="notice" key={issue.code+i}><strong>{issue.productName}:</strong> {issue.detail}</p>)}<div className="guest-total"><span>Taslak toplamı</span><strong>{money(draft.totalMinor)}</strong></div><p className="helper">Taslak toplamı tahsilat değildir. Sepete ekledikten sonra fiyat ve ürün uygunluğu sunucuda yeniden doğrulanır; siparişi ayrıca siz gönderirsiniz.</p></div>}</div>}</section>;
}
