import 'server-only';
import {createServerClient} from '@supabase/ssr';
import {cookies} from 'next/headers';
import {BRANCH,trustedHost} from './config';
export class Failure extends Error{constructor(public code:string,public status=400){super(code);}}
export async function client(){const jar=await cookies();return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{cookies:{getAll:()=>jar.getAll(),setAll(values){for(const c of values)jar.set(c.name,c.value,c.options);}}});}
export async function actor(){const s=await client();const {data,error}=await s.auth.getUser();if(error||!data.user)throw new Failure('UNAUTHENTICATED',401);return {s,user:data.user};}
export function origin(req:Request){const u=new URL(req.url);if(!trustedHost(u.host))throw new Failure('UNKNOWN_HOST',403);if(req.method!=='GET'&&req.headers.get('origin')!==u.origin)throw new Failure('ORIGIN_NOT_ALLOWED',403);if(req.headers.get('sec-fetch-site')==='cross-site')throw new Failure('CROSS_SITE',403);}
export async function body(req:Request){if(!req.headers.get('content-type')?.startsWith('application/json'))throw new Failure('JSON_REQUIRED',415);const reader=req.body?.getReader();if(!reader)throw new Failure('BODY_REQUIRED');let length=0;const chunks:Uint8Array[]=[];const timer=setTimeout(()=>{void reader.cancel();},6000);try{while(true){const v=await reader.read();if(v.done)break;length+=v.value.length;if(length>16384){await reader.cancel();throw new Failure('BODY_TOO_LARGE',413);}chunks.push(v.value);}const bytes=new Uint8Array(length);let pos=0;for(const c of chunks){bytes.set(c,pos);pos+=c.length;}const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(!value||Array.isArray(value)||typeof value!=='object')throw new Failure('OBJECT_REQUIRED');return value as Record<string,unknown>;}catch(e){if(e instanceof Failure)throw e;throw new Failure('INVALID_JSON');}finally{clearTimeout(timer);}}
export function uuid(v:unknown){if(typeof v!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw new Failure('INVALID_ID');return v;}
export function revision(v:unknown){if(typeof v!=='string'||!/^(0|[1-9][0-9]{0,18})$/.test(v)||BigInt(v)>9223372036854775807n)throw new Failure('INVALID_REVISION');return v;}
export async function rpc(s:Awaited<ReturnType<typeof client>>,name:string,args:Record<string,unknown>={}){const{data,error}=await s.schema('ops').rpc(name,args);if(error){const status=/^PT[0-9]{3}$/.test(error.code)?Number(error.code.slice(2)):500;throw new Failure(/^[A-Z0-9_]+$/.test(error.message)?error.message:'DATABASE_UNAVAILABLE',status);}return data;}
export function json(data:unknown,status=200){return new Response(JSON.stringify(data,(_,v)=>typeof v==='bigint'?v.toString():v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'}});}
export function failed(e:unknown){if(e instanceof Failure)return json({error:{code:e.code}},e.status);console.error('MENUGO_REQUEST_FAILED');return json({error:{code:'TEMPORARILY_UNAVAILABLE'}},503);}
export const scope={p_business_id:BRANCH.businessId,p_branch_id:BRANCH.branchId};
