"""Second half of the one-time source transition; run after backend transition."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def read(p):return (root/p).read_text()
def w(p,s):
 f=root/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(s)
p='components/LlmAssistant.tsx';s=read(p)
s=s.replace("useState<'openai'|'gemini'>('openai')","useState<'self_hosted'>('self_hosted')").replace("useState('gpt-4.1-mini')","useState('qwen3.5:4b')")
s=s.replace("setProvider(s.provider||'openai');setModel(s.model||'gpt-4.1-mini');", "setProvider('self_hosted');setModel(s.provider==='self_hosted'&&s.model?s.model:'qwen3.5:4b');")
s=s.replace("const ready=!!status?.enabled&&!!status?.verified;", "const ready=status?.provider==='self_hosted'&&!!status?.enabled&&!!status?.verified;")
s=s.replace("status?.model||'OpenAI / Gemini'","status?.provider==='self_hosted'?status.model:'Qwen · Kendi sunucunuz'")
s=s.replace("<h2>Sağlayıcı bağlantısı</h2><p>Vercel Gateway kredisine bağlı kalmadan kendi OpenAI veya Gemini API hesabınızı bağlayın. Menü Stüdyosu da bu bağlantıyı kullanır.</p>","<h2>Açık kaynak model bağlantısı</h2><p>Qwen modellerini kendi Ollama veya vLLM sunucunuzda çalıştırın. Menü fotoğrafı okuma, açıklama, çeviri ve işletme asistanı aynı güvenli bağlantıyı kullanır. Ücretli API’ye otomatik geçiş yok.</p><p className=\"notice\">Model lisansı ücretsizdir; bilgisayar, elektrik ve sunucu barındırması ayrıca gereklidir. Bu ekran model sunucusu kurmaz. Önce ai.menugo.app üzerinde HTTPS ve erişim anahtarıyla korunan model servisi hazırlanmalıdır.</p>")
s=s.replace("<option value=\"openai\">OpenAI</option><option value=\"gemini\">Google Gemini</option>","<option value=\"self_hosted\">Kendi sunucum · Açık kaynak</option>")
s=s.replace("as 'openai'|'gemini'","as 'self_hosted'")
s=s.replace("Sağlayıcı API anahtarını girin","Kendi model sunucunuzun erişim anahtarı")
s=s.replace("kullanımın kendi API hesabıma yansıyabileceğini onaylıyorum.","verilerin kendi model sunucumda işleneceğini onaylıyorum.")
s=s.replace("Test, gerçek modele tek küçük istek gönderir ve kullanım sayılır. Günlük limit istek sayısıdır; parasal bütçe limiti değildir. Kredi satın alınmaz, otomatik yükleme yapılmaz.","Test, kendi sunucunuzdaki modele tek küçük istek gönderir. Başarılı model yanıtı gelmeden üretim açılmaz. Günlük sınır kaynak tüketimini kontrol eder; ücretli API, kredi alımı veya buluta otomatik geçiş yapılmaz.")
s=s.replace("<details open={!status.configured}>","<details open={!status.configured||status.provider!=='self_hosted'}>")
s=s.replace("(!status.configured&&!key)","((!status.configured||status.provider!=='self_hosted')&&!key)")
s=s.replace("disabled={busy||!status.configured||!status.enabled}","disabled={busy||!status.configured||!status.enabled||status.provider!=='self_hosted'}");w(p,s)
p='components/BusinessStudio.tsx';s=read(p)
s=s.replace("'use client';","'use client';\nimport {llmMessages} from '@/lib/llm/messages';",1)
s=s.replace("useState<StudioKind>('photo-enhance')", "useState<StudioKind>('product-copy')")
s=s.replace("ERRORS[data.aiReason]||'AI Gateway erişimi doğrulanmadı. Üretim düğmesi kapalı; mevcut menü ve siparişler etkilenmez.'", "llmMessages[data.aiReason]||ERRORS[data.aiReason]||'Açık kaynak model bağlantısı doğrulanmadı. LLM Asistanı bölümünde kendi model sunucunuzu bağlayın; mevcut menü ve siparişler etkilenmez.'")
s=s.replace("{kind==='photo-enhance'?<label>","{kind==='photo-enhance'&&data?.imageReady===false&&<p className=\"notice\">Ürün fotoğrafını üretmek veya düzenlemek ayrı bir görsel model sunucusu gerektirir. Qwen metin/görsel-okuma modeli yeni fotoğraf üretmez. Ücretli modele geçilmez.</p>}\n {kind==='photo-enhance'?<label>")
s=s.replace("accept={kind==='invoice'?'image/png,image/jpeg,image/webp,application/pdf':'image/png,image/jpeg,image/webp'}", "accept=\"image/png,image/jpeg,image/webp\"")
s=s.replace("Fatura fotoğrafı / PDF", "Fatura fotoğrafı")
s=s.replace("En fazla 2 MB. PDF en fazla 8 sayfa.", "En fazla 2 MB. PDF sayfalarını önce görüntüye dönüştürün; doğrudan PDF desteği henüz bağlı değil.")
s=s.replace("!data?.aiReady||needsFile", "!data?.aiReady||(kind==='photo-enhance'&&data?.imageReady===false)||needsFile")
s=s.replace("Üretim sağlayıcınızın kullanım kotasına dahildir. Günde en fazla 10 işlem, bunun en fazla 3’ü görsel.", "Üretim kendi model sunucunuzun kaynaklarını kullanır. Günde en fazla 10 işlem. Harici ücretli API’ye otomatik geçilmez.")
s=s.replace("disabled={busy||!data?.aiReady}","disabled={busy||!data?.aiReady||(selected.kind==='photo-enhance'&&data?.imageReady===false)}")
s=s.replace("ERRORS[e.message]", "llmMessages[e.message]||ERRORS[e.message]");w(p,s)
p='lib/ai-menu/contracts.ts';s=read(p)
s=s.replace("return messages[code]||", "return ({LLM_SERVER_REQUIRED:'Kendi açık kaynak model sunucunuz henüz bağlı değil. LLM Asistanı bölümünden bağlantıyı kurun.',LLM_OPEN_SOURCE_REQUIRED:'Bu sürüm yalnız açık kaynak model bağlantısını kullanır; ücretli API’ye geçilmez.',LLM_PDF_PAGES_REQUIRED:'PDF sayfalarını fotoğraf/görüntü olarak yükleyin. Doğrudan PDF dönüştürme henüz bağlı değil.'} as Record<string,string>)[code]||messages[code]||")
w(p,s);w('supabase/functions/menugo-llm/menu-contracts.ts',s)
p='components/AiMenuStudio.tsx';s=read(p).replace('image/png,image/jpeg,image/webp,application/pdf','image/png,image/jpeg,image/webp')
s=s.replace('PNG, JPG, WebP veya PDF','PNG, JPG veya WebP').replace('Fotoğraf / PDF seç','Menü fotoğrafı seç')
pos=s.find('<Card')
if pos>=0:s=s[:pos]+"<p className=\"notice\">Açık kaynak bağlantısı: menü fotoğrafları kendi model sunucunuzda işlenir. PDF sayfalarını görüntü olarak yükleyin. Model erişimi doğrulanmadan analiz başlamaz.</p>"+s[pos:]
w(p,s)
p='app/api/studio/[action]/route.ts';s=read(p).replace("let reason:string|null=null;try{await credential(s);}","let reason:string|null=null;let model:string|null=null;try{model=(await credential(s)).model;}")
s=s.replace('models:{text:TEXT_MODEL,image:IMAGE_MODEL}','models:{text:model||TEXT_MODEL,image:IMAGE_MODEL}').replace("import {PDFDocument} from 'pdf-lib';\n",'');w(p,s)
p='app/api/ai-menu/[action]/route.ts';s=read(p).replace("import {PDFDocument} from 'pdf-lib';\n",'').replace("provider=b.provider","provider='self_hosted'");w(p,s)
p='tests/llm.test.mjs';s=read(p).replace("['core','menu-contracts']", "['core','menu-contracts','open-source','studio-contracts','studio-operations']")
s=s.replace(".replace(\"'./menu-contracts.ts'\",\"'./menu-contracts.mjs'\")", ".replaceAll(\".ts'\",\".mjs'\")");w(p,s)
p='tests/sql.integration.mjs';s=read(p).replace("provider:'openai',model:'gpt-4.1-mini',apiKey:syntheticKey", "provider:'self_hosted',model:'qwen3.5:4b',apiKey:syntheticKey");w(p,s)
w('public/open-models-release.json',json.dumps({'version':'menugo-open-models-20260919-r21','policy':'self_hosted_only','connectionEndpoint':'https://ai.menugo.app/v1/chat/completions','models':['qwen3.5:4b','qwen3.5:9b','Qwen/Qwen3.5-4B','Qwen/Qwen3.5-9B'],'modelLicense':'Apache-2.0','imageGenerationReady':False,'directPdfReady':False,'realInferenceAcceptance':'not_run','completeAiSuite':False},ensure_ascii=False,indent=2)+'\n')
